### ISSUE TITLE
[Auditbeat] System module 6.7 / 7.0

### ISSUE THREAD

**Issue by cwurm** [elastic/beats#10103]
Meta issue to track the features making it into a release of the Auditbeat system module.

Further tasks are tracked in the [backlog issue](https://github.com/elastic/beats/issues/9344).

## General
- [x] Kibana dashboards (done: https://github.com/elastic/beats/pull/10511)
- [x] Add entity IDs (done: https://github.com/elastic/beats/pull/10500)

## 1. Package
- [x] Initial implementation (done: https://github.com/elastic/beats/pull/8436)
- [x] RPM support (done: https://github.com/elastic/beats/pull/9092)
- [x] Rename to `package`, implement scheduled state reporting, and change to single documents (done: https://github.com/elastic/beats/pull/10225)
- [x] Detect package updates (done: https://github.com/elastic/beats/pull/10508)
- [x] Documentation (done: https://github.com/elastic/beats/pull/9512)

## 2. Process
- [x] Add owner information (`uid`/`gid` at least) (addded to `elastic/go-sysinfo`: https://github.com/elastic/go-sysinfo/pull/34, done: https://github.com/elastic/beats/pull/9963)

## 4. Login
- [x] Implement metricset (done: https://github.com/elastic/beats/pull/9327)
- [x] Tests with sample `/var/log/wtmp` file (done: https://github.com/elastic/beats/pull/9327)

**Comment by cwurm** [comment]
Updated and moved items to the [backlog](https://github.com/elastic/beats/issues/9344).
