### ISSUE TITLE
AWS Metricbeat Module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#10115]
This is a meta issue to track the work on adding AWS metricbeat module including varies metricsets. 
This checklist is intended for Devs which create or update a module to make sure modules are consistent.

* [x] EC2 metricset (https://github.com/elastic/beats/pull/9257)
* [x] SQS metricset (https://github.com/elastic/beats/issues/10053)
* [x] RDS metricset (https://github.com/elastic/beats/issues/10054)
* [x] S3 metricset (https://github.com/elastic/beats/issues/10055)
* [x] EBS metricset (https://github.com/elastic/beats/issues/11699)
* [x] ELB metricset (https://github.com/elastic/beats/issues/11701)
* [x] Cloudwatch metricset (https://github.com/elastic/beats/issues/11734)

**Comment by kaiyan-sheng** [comment]
One enhancement issue: https://github.com/elastic/beats/issues/11820

**Comment by kaiyan-sheng** [comment]
Adding tags support in AWS module: https://github.com/elastic/beats/issues/12263

**Comment by Giaco9** [comment]
Hi @kaiyan-sheng, I don't know if this is the right place to ask questions, but I'm very interested in the AWS module especially for EC2 metrics, this is a really cool feature! My question is: Is there any way to collect only selected metrics and get them only for a subset of my ec2 instances running in a region? Would be great filter them by tags or name. Should I open an issue for that?

Thanks!

**Comment by kaiyan-sheng** [comment]
Hi @Giaco9, thanks for reaching out! If you only want to collect metrics from a specific region, then you can use 
```
- module: aws
  period: 300s
  metricsets:
    - ec2
  regions:
    - us-east-1
```

If you want to specify both ec2 instances and regions, then you can try `cloudwatch` metricset:
```
- module: aws
  period: 300s
  metricsets:
    - cloudwatch
  metrics:
    - namespace: AWS/EC2
      name: ["CPUUtilization", "DiskWriteOps"]
      tags.resource_type_filter: ec2:intance
      dimensions:
        - name: InstanceId
          value: i-0686946e22cf9494a
```

For ec2 metricset, tags will be collected by default so if you have tags for the instances you are interested, you can also collect all metrics and then filter by tags in Kibana for visualization.

**Comment by kaiyan-sheng** [comment]
@Giaco9 Filtering by tags/names to decide what are the metrics should be collected (before collecting all metrics) is a feature we don't have right now. Please correct me if I understood wrong 😄
