### ISSUE TITLE
Update Developer Guide

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#1077]
The developer guide needs an update that includes https://github.com/elastic/beat-generator

 * [x] Document beat-generator and how to use it
 * [ ] Document on how to add a vendor library (remove .git folder)
 * [ ] Document recommendations for .editorconfig (how to use it)
 * [ ] Document on how to use travis
 * [ ] Document how `fields.yml` is used

**Comment by monicasarbu** [comment]
I would include the beat-generator documentation under the `Developer Guide: Creating a New Beat` section. As of https://github.com/elastic/beats/pull/1172, we need to update the developer guide anyway to replace Topbeat with some other simple beat.

**Comment by ruflin** [comment]
Agree. For the guide I was thinking to take only the beat that is generated by beat-generator.

**Comment by monicasarbu** [comment]
I think we should add a link to David's blog post about soundbeat as it describes the full experience of a Beat creator: http://david.pilato.fr/blog/2016/03/17/and-the-beats-go-on/

**Comment by ruflin** [comment]
Closing this issue as @kimjmin did a blog post (https://www.elastic.co/blog/build-your-own-beat) and the dev guide got updated accordingly.
