### ISSUE TITLE
[Metricbeat] ReporterV2 migration meta-issue

### ISSUE THREAD

**Issue by sayden** [elastic/beats#10774]
Using `grep` I managed to find this modules/metricset using `Fetch() (common.Mapstr, error)`, `Fetch () ([]common.Mapstr, error)`, `Run(reporter mb.PushReporter)` or `Run(reporter mb.PushReporterV2)`

* [X] aerospike/namespace https://github.com/elastic/beats/pull/10984
* [X] apache/status https://github.com/elastic/beats/pull/10986
* [X] ceph/cluster_disk https://github.com/elastic/beats/pull/10990
* [X] ceph/cluster_health https://github.com/elastic/beats/pull/10991
* [X] ceph/cluster_status https://github.com/elastic/beats/pull/10993
* [X] ceph/monitor_health https://github.com/elastic/beats/pull/11012
* [X] ceph/osd_df https://github.com/elastic/beats/pull/11013
* [X] ceph/osd_tree https://github.com/elastic/beats/pull/11048
* [X] ceph/pool_disk https://github.com/elastic/beats/pull/11049
* [X] couchbase/bucket https://github.com/elastic/beats/pull/11045
* [X] couchbase/cluster https://github.com/elastic/beats/pull/11046
* [X] couchbase/node https://github.com/elastic/beats/pull/11047
* [X] couchdb/server https://github.com/elastic/beats/pull/11043
* [X] docker/container https://github.com/elastic/beats/pull/10927
* [X] docker/cpu https://github.com/elastic/beats/pull/10927
* [X] docker/diskio https://github.com/elastic/beats/pull/10927
* [X] ~docker/event (it uses mb.PushReporterV2)~
* [X] docker/healthcheck https://github.com/elastic/beats/pull/10927
* [X] docker/image https://github.com/elastic/beats/pull/11478
* [X] docker/info https://github.com/elastic/beats/pull/10927
* [X] docker/memory https://github.com/elastic/beats/pull/10927
* [X] dropwizard/collector https://github.com/elastic/beats/pull/11743
* [X] envoyproxy/server https://github.com/elastic/beats/pull/11044
* [X] etcd/leader https://github.com/elastic/beats/pull/10817
* [X] etcd/self https://github.com/elastic/beats/pull/10816
* [X] etcd/store https://github.com/elastic/beats/pull/10815
* [X] golang/expvar https://github.com/elastic/beats/pull/11103
* [X] golang/heap https://github.com/elastic/beats/pull/11074
* [X] ~graphite/server (it uses mb.PushReporter)~
* [X] http/json https://github.com/elastic/beats/pull/10960
* [X] ~http/server (it uses mb.PushReporterV2)~
* [X] jolokia/jmx https://github.com/elastic/beats/pull/11104
* [X] kubernetes/container https://github.com/elastic/beats/pull/10855
* [X] ~kubernetes/event (it uses mb.PushReporter)~
* [X] kubernetes/node https://github.com/elastic/beats/pull/10856
* [X] kubernetes/pod https://github.com/elastic/beats/pull/10857
* [X] kubernetes/state_container https://github.com/elastic/beats/pull/10858
* [X] kubernetes/state_deployment https://github.com/elastic/beats/pull/10961
* [X] kubernetes/state_node https://github.com/elastic/beats/pull/10962
* [X] kubernetes/state_pod https://github.com/elastic/beats/pull/10973
* [X] kubernetes/state_replicaset https://github.com/elastic/beats/pull/10974
* [X] kubernetes/state_statefulset https://github.com/elastic/beats/pull/10976
* [X] kubernetes/system https://github.com/elastic/beats/pull/10977
* [X] kubernetes/volume https://github.com/elastic/beats/pull/10978
* [X] memcached/stats https://github.com/elastic/beats/pull/10983
* [X] mongodb/collstats https://github.com/elastic/beats/pull/10851
* [X] mongodb/dbstats https://github.com/elastic/beats/pull/10852
* [X] mongodb/metrics https://github.com/elastic/beats/pull/10853
* [X] mongodb/replstatus https://github.com/elastic/beats/pull/10854
* [X] mysql/galera_status #11324
* [X] mysql/status https://github.com/elastic/beats/pull/11295
* [X] nginx/stubstatus https://github.com/elastic/beats/pull/11051
* [X] postgresql/activity https://github.com/elastic/beats/pull/10828
* [X] postgresql/bgwriter https://github.com/elastic/beats/pull/10831
* [X] postgresql/database https://github.com/elastic/beats/pull/10830
* [X] postgresql/statement https://github.com/elastic/beats/pull/10829
* [X] rabbitmq/metricset_test https://github.com/elastic/beats/pull/10827
* [x] uwsgi/status #11153
* [X] vsphere/datastore #11401
* [x] vsphere/host #11403
* [x] vsphere/virtualmachine https://github.com/elastic/beats/pull/11475
* [X] windows/service https://github.com/elastic/beats/pull/11477

**Comment by kaiyan-sheng** [comment]
Do we need to regenerate the `data.json` file just to be sure that the migration didn't break anything?

**Comment by sayden** [comment]
I'm regenerating `data.json` files but they aren't changing at all, which is a good sign, BTW :slightly_smiling_face:

**Comment by sayden** [comment]
## Guide to migration

* [ ] **Check state of current Metricset**: This is to avoid potential environment errors. Let's say that we are testing ETCD so let's run its tests first:
```shell
(python-env) metricbeat ➜ make python-env
(python-env) metricbeat ➜ source build/python-env/bin/activate
(python-env) metricbeat ➜ MODULE=etcd make test-module
# Navigate to the Metricset being migrated and
(python-env) metricbeat ➜ cd module/etcd/store
(python-env) metricbeat ➜ go test ./...
(python-env) metricbeat ➜ go test -tags=integration -data ./...
```

If everything is green, continue to the next step:

* [ ] **Add new `logger` variable for logging**. In most modules we use an old `logp` implementation for logging and must be updated. For example for `leader` Metricset in ETCD module just place this at the top of the `leader.go` file:
```go
var logger = logp.NewLogger("etcd.leader")
```
And then use `logger.Debug` or `logger.Error` instead of `logp`.
* [ ] **Replace `func (m *MetricSet) Fetch() (common.MapStr, error) {`** with `func (m *MetricSet) Fetch(reporter mb.ReporterV2) {`. Most of the times that function is in a file with the same name than the Metricset (file `leader.go` in ETCD leader Metricset, for example). At the same time, some `Fetch` methods didn't have comments so the default one is used (pasting here for quick reference):
For example, a `Fetch` method like this:
```go
func (m *MetricSet) Fetch() (common.MapStr, error) {
	content, err := m.http.FetchContent()
	if err != nil {
		return nil, err
	}
	return eventMapping(content), nil
}
```
Will end up looking like this:
```go
// Fetch methods implements the data gathering and data conversion to the right
// format. It publishes the event which is then forwarded to the output. In case
// of an error set the Error field of mb.Event or simply call report.Error().
func (m *MetricSet) Fetch(reporter mb.ReporterV2) {
	content, err := m.http.FetchContent()
	if err != nil {
		logger.Error(err)
		reporter.Error(err)
		return
	}

	reporter.Event(mb.Event{
		MetricSetFields: eventMapping(content),
	})
}
```
> We can see that 3-liner of _logger-report-return_ that we are trying to avoid but if all modules have the same 3-liner, maybe we can make something to change them all with a script and start using https://github.com/elastic/beats/pull/10727
* [ ] **Replace `TestFetch` code in integration tests**: Often we will find this code (taken from PostgreSQL bgwriter) that declares an `event` variable to assert against it:
```go
func TestFetch(t *testing.T) {
	compose.EnsureUp(t, "postgresql")

	f := mbtest.NewEventFetcher(t, getConfig())
	event, err := f.Fetch()
	if !assert.NoError(t, err) {
		t.FailNow()
	}

	t.Logf("%s/%s event: %+v", f.Module().Name(), f.Name(), event)

	assert.Contains(t, event, "checkpoints")
	assert.Contains(t, event, "buffers")
	assert.Contains(t, event, "stats_reset")

        //continue...
```
So look for the line `f := mbtest.NewEventFetcher(t, getConfig())` and from there, replace with:
```go
	f := mbtest.NewReportingMetricSetV2(t, getConfig())
	events, errs := mbtest.ReportingFetchV2(f)
	if len(errs) > 0 {
		t.Fatalf("Expected 0 error, had %d. %v\n", len(errs), errs)
	}
	assert.NotEmpty(t, events)
	event := events[0].MetricSetFields

	// test continue untouched...
```
> `getConfig()` might be also called `getConfig(string)` or `getConfigWithData()` or any other variant of it. Just check on the same file because you'll find that function somewhere there.

* [ ] **Replace `TestData` function:** `TestData` can be almost fully replaced with a copy-paste. Just change the name of the service that compose is checking in `compose.EnsureUp` and check `getConfig()` call like in the previous point:
```go
func TestData(t *testing.T) {
	compose.EnsureUp(t, "postgresql")

	f := mbtest.NewReportingMetricSetV2(t, getConfig())
	events, errs := mbtest.ReportingFetchV2(f)
	if len(errs) > 0 {
		t.Fatalf("Expected 0 error, had %d. %v\n", len(errs), errs)
	}
	assert.NotEmpty(t, events)

	if err := mbtest.WriteEventsReporterV2(f, t, ""); err != nil {
		t.Fatal("write", err)
	}
}
```
* [ ] **Check for uses in Unit Tests and replace them too:** I have also found that some unit tests files use (or files without the `_integration` name on it) might have some tests using the reporter V1 interface. For example, this was on the `store_test.go` of the `store` Metricset of ETCD module:
```go
func TestFetchEventContent(t *testing.T) {
	absPath, err := filepath.Abs("../_meta/test/")

	response, err := ioutil.ReadFile(absPath + "/storestats.json")
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(200)
		w.Header().Set("Content-Type", "application/json;")
		w.Write([]byte(response))
	}))
	defer server.Close()

	config := map[string]interface{}{
		"module":     "etcd",
		"metricsets": []string{"store"},
		"hosts":      []string{server.URL},
	}
	f := mbtest.NewEventFetcher(t, config)
	event, err := f.Fetch()
	if err != nil {
		t.Fatal(err)
	}

	t.Logf("%s/%s event: %+v", f.Module().Name(), f.Name(), event)
}
```
So the approach is the same than `TestFetch` function, replace everything from `f := mbtest.NewEventFetcher(t, config)` with this:
```go
	f := mbtest.NewReportingMetricSetV2(t, config)
	events, errs := mbtest.ReportingFetchV2(f)
	if len(errs) > 0 {
		t.Fatalf("Expected 0 error, had %d. %v\n", len(errs), errs)
	}
	assert.NotEmpty(t, events)

	t.Logf("%s/%s event: %+v", f.Module().Name(), f.Name(), events[0])
}
```
> Here you don't need to extract `MetricsetFields` from the `event[0]`

* [ ] **Run tests and regenerate `data.json` file: Quick ref:
```shell
# Replace etcd with the module you are testing
(python-env) metricbeat ➜ MODULE=etcd make test-module
# Navigate to the Metricset being migrated and
(python-env) metricbeat ➜ cd module/etcd/store
(python-env) metricbeat ➜ go test ./...
(python-env) metricbeat ➜ go test -tags=integration -data ./...
```
Everything is OK if
* No errors happened during the test
* `data.json` file isn't changed or its changes only reflects changes in the Root fields. For example `beat` field should change to `agent` and full objects like `event` or `service` should appear.
```json

```

So, at the end, just 2 to 4 `files are uploaded in the PR, like here https://github.com/elastic/beats/pull/10817

**Comment by kaiyan-sheng** [comment]
> I'm regenerating `data.json` files but they aren't changing at all, which is a good sign, BTW 🙂
> 
> Correction, some of them are changing https://github.com/elastic/beats/pull/10817/files#diff-5a9cef679c0694a2ace62a1ffc7159ad

Yes!

**Comment by kaiyan-sheng** [comment]
Sorry, clicked the wrong button...

**Comment by sayden** [comment]
I'm wondering if the migration must be "backported" to any branch like `7.0` or `7.x` apart from being merged into master. @andrewkroh maybe you can help us in this, please?

**Comment by sayden** [comment]
Examples and tutorials have been updated after merging https://github.com/elastic/beats/pull/11106

**Comment by sayden** [comment]
`TestData` function have been updated in the tutorial too

**Comment by sayden** [comment]
Guide updated again to use https://github.com/elastic/beats/commit/45074a3efb74592505f90c9fc70e5dd75d898c1f

**Comment by sayden** [comment]
Thanks to everybody for helping with this migration. Good work!
