### ISSUE TITLE
[Filebeat] [Meta] Netflow input improvements

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#10943]
A few issues are being identified in the released NetFlow input (beta):

- [x] ~~Fix field snake-case conversion bug (`postNATSourceIPv4Address` => `post_nast_ource_ipv4_address` vs `post_nat_source_ipv4_address`)~~ #10950
- [x] ~~Support custom field definitions. Allow users to add and/or override NetFlow V9/IPFIX fields using files in [custom field definitions in Logstash format.](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-netflow.html#plugins-codecs-netflow-ipfix_definitions)~~ #10945
- [x] ~~Add support for [Cisco ASA devices.](https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/guide/asa_netflow.html): NetFlow fields missing / `acl_id_asa` datatype.~~ #11201
- [x] Add missing fields for vendors (Streamcore, Palo Alto, Netstream, ...) (see testdata)

**Comment by kaiyan-sheng** [comment]
@adriansr Is this issue still valid?

**Comment by adriansr** [comment]
Closing as we added most of the missing fields from vendors.
