### ISSUE TITLE
Beats Developer Guide meta-issue

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#11102]
All of our overarching developer docs issues are kind of old (#4059 was a bit dated so we decided to close it)  so @jsoriano And I decided to open a new meta-issue, as I in particular had some problems with the [Beats developer guide](https://www.elastic.co/guide/en/beats/devguide/current/index.html) before I got here.

- [ ] The Guide briefly mentions `_meta/data.json` [once](https://github.com/elastic/beats/blob/fbc2ddaacf87a818a0d24ad690c086cfc0348a0f/docs/devguide/create-metricset.asciidoc#creating-a-metricset) in the context of it being an autogenerated file, but I can't find any further information on what it does, why it's there, etc.
- [ ] Data transformation for metricsets is mentioned in two places, [here](https://github.com/elastic/beats/blob/fbc2ddaacf87a818a0d24ad690c086cfc0348a0f/docs/devguide/create-metricset.asciidoc#parsing-and-normalizing-fields) and [here](https://github.com/elastic/beats/blob/master/docs/devguide/metricset-details.asciidoc#data-transformation). The first page demonstrates a typical example of a `data.go` file, but `data.go` itself and usage of the standard `eventMapping()` function is explicitly called out in the second page. Maybe this should all be in one place?
- [ ] `make fmt` should probably be mentioned, as CI will test this.
- [ ] We do mention [testing for metricsets](https://github.com/elastic/beats/blob/master/docs/devguide/metricset-details.asciidoc#testing) but we don't mention the standard `TestData()` and `TestFetch()` integration tests that most metricsets have. Maybe we should have some sort of "style guide" for metricsets, in terms of testing, layout, etc, since there's so many?
- [ ] [The testing section for adding a protocol to packetbeat needs to be filled](https://github.com/elastic/beats/blob/master/docs/devguide/new_protocol.asciidoc#testing). May be covered by #1111
- [ ] New Beat docs updates  #7159
- [ ] Beats testing guide #2052 
- [ ] More complete documentation of `fields.yml` #6049
Older issues that need looking at:
- [ ] #6093  
- [ ] #5658
- [ ] #4598 has an uncompleted item for developer docs

**Comment by jlind23** [comment]
Backlog grooming: Closing for now until further update
