### ISSUE TITLE
Update 'new protocol guide'

### ISSUE THREAD

**Issue by urso** [elastic/beats#1111]
with PR #1101 changes have been made to packetbeat protocol registration, turning the guide somewhat out of data. Plus we might want to provide some cookiecutter templates for generating boilerplate code.

checklist:
- [ ] ProtocolPlugin has been renamed to Plugin
- [ ] TcpProtocolPlugin has been renamed to TcpPlugin
- [ ] UdpProtocolPlugin has been renamed to UdpPlugin
- [ ] configuration local to plugin in config.go, based on ucfg. No changes in packetbeat/config/config.go required.
- [ ] fields.yml to become local to each protocol (see #1110)
- [ ] protocol registration via protos.Register (no more EnabledPlugins in packetbeat.go)
- [ ] optional: mention or create doc based on cookiecutter (still in progress) templates (different templates based on protocols) => explain templates
