### ISSUE TITLE
[Metricbeat] ReporterV2 with error migration tracking meta-issue

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#11374]
@ruflin and I decided to make a meta-issue for this now that elastic/beats#10727  has been merged. Our hope is that this will simplify a lot of metricset code floating around, as we now have a cleaner way to handle errors in `Fetch()` 

I generated a simple list with `grep -rn "Fetch(.*mb.ReporterV2) {" . | grep -o './[a-z_]*/[a-z_]*' | sed 's/\.\//- [ ] /g'`

- [x] ceph/cluster_health
- [x] ceph/cluster_status
- [x] ceph/osd_df
- [x] ceph/osd_tree
- [x] ceph/pool_disk
- [x] consul/agent #11440
- [X] couchbase/bucket #11396
- [X] couchbase/cluster #11396
- [X] couchbase/node elastic/beats#11396
- [X] couchdb/server #11411
- [x] docker/container #11462
- [x] docker/cpu #11462
- [x] docker/diskio #11462
- [x] docker/healthcheck #11462
- [x] docker/memory #11462
- [x] docker/network #11462
- [x] elasticsearch/ccr
- [x] elasticsearch/cluster_stats
- [x] elasticsearch/index
- [x] elasticsearch/index_recovery
- [x] elasticsearch/index_summary
- [x] elasticsearch/ml_job
- [x] elasticsearch/node
- [x] elasticsearch/node_stats
- [x] elasticsearch/pending_tasks
- [x] elasticsearch/shard
- [x] envoyproxy/server #11412
- [X] etcd/leader #11413
- [X] etcd/self #11413
- [X] etcd/store #11413
- [X] golang/expvar elastic/beats#11382
- [X] golang/heap #11382
- [x] haproxy/info #11446
- [x] haproxy/stat #11446
- [x] kafka/consumergroup #11868
- [x] kafka/partition #11868
- [x] kibana/stats #11868
- [x] kibana/status #11868
- [x] kubernetes/container  #11374
- [x] kubernetes/node  #11374
- [x] kubernetes/pod  #11374
- [x] kubernetes/state_node  #11374
- [x] kubernetes/system  #11374
- [x] kubernetes/volume  #11374
- [x] kvm/dommemstat #11814
- [x] logstash/node
- [x] logstash/node_stats
- [X] memcached/stats #11415
- [x] mongodb/collstats #11653
- [x] mongodb/dbstats #11653
- [x] mongodb/metrics #11653
- [x] mongodb/replstatus #11653
- [x] mongodb/status #11653
- [x] munin/node #11819
- [x] nats/connections #11881
- [x] nats/routes #11881
- [x] nats/stats #11881
- [x] nats/subscriptions #11881
- [x] nginx/stubstatus #13518
- [x] php_fpm/pool #11459
- [x] postgresql/activity #11636
- [x] postgresql/bgwriter #11636
- [x] postgresql/database #11636
- [x] postgresql/statement #11636
- [x] prometheus/collector #13521
- [x] rabbitmq/connection #12228
- [x] rabbitmq/exchange #12228
- [x] rabbitmq/metricset_test #12228
- [x] rabbitmq/node #12228
- [x] rabbitmq/node #12228
- [x] rabbitmq/queue #12228
- [x] redis/info #11792
- [x] redis/key #11792
- [x] redis/keyspace #11792
- [x] redis/metricset_integration_test #11792
- [x] system/core  #12455
- [x] system/cpu  #12455
- [x] system/diskio  #12455
- [x] system/filesystem  #12455
- [x] system/fsstat  #12455
- [x] system/load
- [x] system/memory
- [x] system/network
- [x] system/process
- [x] system/process_summary
- [x] system/raid
- [x] system/socket
- [x] system/socket_summary
- [x] system/uptime
- [x] traefik/health #11458
- [x] windows/perfmon #13517
- [x] zookeeper/mntr #11659
- [x] zookeeper/server #11659
