### ISSUE TITLE
[Metricbeat] standardize checks of r.Event inside loops

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#11828]
This is a more specific continuation of elastic/beats#11666 
It looks like the best way to handle calling `r.Event` inside a loop is to check the bool return value, and just return from `Fetch` if we get a false. This will only happen when the metricset is closed. This obviously isn't a huge issue, but it would be nice to standardize how we handle this.

- [ ] all of postgres
- [ ]  docker/image
- [ ] all of vsphere
- [ ] ceph/monitor_health
- [ ] jolokia/jmx
- [ ] mongodb/collstats
- [x] most of system
- [ ] consul/agent
- [x] kafka/partition elastic/beats#11868
- [x] kvm/dommemstat
- [ ] aerospike/namespace
- [ ] prometheus/collector
- [ ] windows/perfmon
- [ ] windows/service
- [ ]  couchbase/bucket
- [ ] couchbase/node
- [x] aws (https://github.com/elastic/beats/pull/11775)
