### ISSUE TITLE
Apache Module next Steps

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#1196]
After the first implementation of the apache module in metricbeat (https://github.com/elastic/beats/pull/1192), the following tasks should be taken care of to complete the module:

* [ ] Add Kibana dashboards
* [x] Improve config to make server-status configurable https://github.com/elastic/beats/pull/1203
* [x] Add selectors support in case required https://github.com/elastic/beats/pull/1383
* [x] Add example JSON doc to show what is created
* [x] Add authentication params to config if needed
* [x] Add additional metricset (optional)
* [x] Add fields.yml to generate the index template https://github.com/elastic/beats/pull/1382
* [x] Add documentation for module

@radoondas FYI

**Comment by radoondas** [comment]
Great! I will continue my work on that too. :+1:

**Comment by ruflin** [comment]
@radoondas Great. As soon as we have https://github.com/elastic/beats/pull/1192 in will start on the config part, ok for you?

**Comment by radoondas** [comment]
@ruflin You have 3 'yeses' from me.

**Comment by ruflin** [comment]
@radoondas Looking at the metrics provided by status I was thinking to introduce some nesting. This will make filtering easier and allows to use selectors.

The nested docs I would introduce would be:

* cpu
* connections
* load
* scb

So it would be for example:

```
load:
  load1:
  load5:
  load15:
```
More could be added. Not 100% sure about the names we should use. For example scb or scoreboard?

**Comment by radoondas** [comment]
@ruflin Yes, it would be next step. Nesting is quite obvious to implement. I can start working on it if OK with you.

**Comment by ruflin** [comment]
@radoondas Sounds good to me.

**Comment by radoondas** [comment]
@ruflin PR ready see #1206

**Comment by ruflin** [comment]
@radoondas Currently working on completing apache module. The part I would need your help is adding more metricsets. I remember you mentioned some time ago an extended status? Is that commonly used?

**Comment by radoondas** [comment]
@ruflin we have 2 status versions.
Normal and Extended status. The difference is in amount of fields in response from server-status.
Extended status must be enabled by admin in configuration. 

If you enable extended status in configuration then we would have at least 2 basic metricsets: 
1, Status and 
2, ExtendedStatus.

There is still an option to define more metricsets in case you don't want all the metrics from coming from ExtendedStatus. 
Question is, if this can be covered by filtering of the fields.

**Comment by ruflin** [comment]
I think this can be covered by filtering and selectors.

**Comment by radoondas** [comment]
Good. I thought so. Then we can define only to basic metricsets.

**Comment by ruflin** [comment]
I'm closing this issue as I think apache module is now in a good state. We should still add more things in the future, but that we can handle in separate issues and PR's.
