### ISSUE TITLE
Add additional fields to MySQL module

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#12088]
Add some additional metrics proposed by @seattlegaucho to the MySQL status metricset:
- [ ] `Queries` and `Questions` as total statements counters, complementary to the `com_%` that are already collected
- [ ] `handler_%` for low level database operations
- [ ] `innodb_buffer_pool%` to monitor resources used by innodb buffer pool

We could also consider creating one or more metricsets based on the information in `information_schema`. This can allow for example to monitor the files used by MySQL, the engines used on other schemas, or to make agregations on resources used.

**Comment by jsoriano** [comment]
Added the `good first issue` label for the metrics that can be easily added to the status metricset. The addition of new metricsets based on `information_schema` would require further discussions.

**Comment by Cho1409** [comment]
+1 We're considering moving our database monitoring to Elastic if the MySQL module could be enhanced a little. The mongodb one is quite good, but the MySQL lack some stuff.

**Comment by jsoriano** [comment]
@Cho1409 thanks for your feedback! Could you give more details about what you are missing in the MySQL module? What would you enhance?

**Comment by Cho1409** [comment]
@jsoriano Basically, everything we could get from both InnoDB and Performance_Schema would be awesome. I'm running Percona PMM for my MySQL databases and it's wonderful.
