### ISSUE TITLE
Manage Kibana dashboards per Beat

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#1277]
The idea is to move the dashboards related to a Beat from the elastic/beats-dashboards repository to the Beat repository, so you can import only the Kibana dashboards of a Beat not of all the Beats. 

In addition, provide a script that exports only the dashboards, visualizations, searches and index-pattern associated with a Beat, so you can easily change the dashboards.

Tasks:

- [x] Add script in elastic/libbeat to import only the dashboards, visualizations, searches and index-pattern of a Beat https://github.com/elastic/beats/pull/1288
- [x]  Export all dashboards, visualizations, searches and index-pattern of a Beat https://github.com/elastic/beats/pull/1275
- [x] Adjust Topbeat dashboards and remove Navigation widget https://github.com/elastic/beats/pull/1287
- [x] Adjust Packetbeat dashboards and remove Topbeat from the Navigation https://github.com/elastic/beats/pull/1264
- [x] Include the import script and the dashboards in the Beat packages https://github.com/elastic/beats/pull/1288
- [x] Update beats-dashboards with latest changes https://github.com/elastic/beats-dashboards/pull/109
- [x] Customize Discover view for Flows and transactions in Packetbeat https://github.com/elastic/beats/pull/1293

**Comment by monicasarbu** [comment]
Finished successfully all the tasks.
