### ISSUE TITLE
Improvements in metricbeat modules integration tests

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#12909]
Introduce some improvements in metricbeat modules integration tests to make them easier to run and parallelize.

- [x] Obtain host addresses from container runtime metadata, remove env files (https://github.com/elastic/beats/pull/11925)
- [x] Allow to run tests directly with `go test` (https://github.com/elastic/beats/pull/11925)
- [x] Allow to define multiple docker compose files (https://github.com/elastic/beats/pull/13186)
- [x] Explictly name images so they can be more easily reused (https://github.com/elastic/beats/issues/13471)
- [x] ~~Allow to define configuration matrices for tests~~ (waiting for https://github.com/elastic/metricbeat-tests-poc)
- [x] Move module test files to module directories (https://github.com/elastic/beats/issues/14606)

This meta issue is intended to introduce changes tested in elastic/beats#7957 piece by piece.

Related changes for python system tests were already introduced in #11925.

**Comment by jsoriano** [comment]
Closing this, everything was done except some parts of #14606 that can be done incrementally.
