### ISSUE TITLE
Directory layout and data path

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1371]
This a meta issue for the tasks required to support a "data path" in Beats.

The end goal is to have:

* A clear  location for the Filebeat/Winlogbeat registry files. This fixes the issue where the registry file was created in the home directory of the user.
* Make it possible to load the template when running as a service in Windows. Fixes issue: #1315
* Provide a path for a persistent UUID, which we will need when implementing configuration management.
* Have a clear location for storing the Kibana dashboards

The following configurable "paths" are introduced:

|             | Description                                                                                                    | Default              |
|-------------|----------------------------------------------------------------------------------------------------------------|----------------------|
| path.home   | It’s the default folder for everything that doesn't fit in the categories before                               | `{binary directory}` |
| path.data   | Contains things that are expected to change often during normal operations (“registry” files, UUID file, etc.) | `{path.home}/data`   |
| path.config | Configuration file location                                                                                    | `{path.home}`        |
| path.logs    | Default path for log files.                                                                                    | `{path.home}/logs`   |

This is modeled after [Elasticsearch directory layout](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-dir-layout.html) with some differences:

* Not all path types are present. We might introduce more as we feel the need.
* `path.config` has the same default as `path.home`. This is because in beats we don't have a `config/` folder, and introducing one would be difficult because we have a `config` package.

## Directory layouts

Illustrating these with Filebeat.

### ZIP / TAR.GZ / TGZ

When running directly under the tarball archives, everything is relative to the binary location. This also matches  the organization of the source code repository, so things should work the same when running from a source checkout.
   
```
    filebeat      
    filebeat.yml
    filebeat.template.json
    data/
       registry.json
       filebeat.uuid
    kibana/
      load.sh
      searches/
      visualisations/
      dashboards/
      index-patterns/
```
To run, you typically just start with: `./filebeat`

### DEB/RPM

Debian/Centos packages have their home path set to `/usr/share/filebeat` and their data path set to `/var/lib/filebeat`, to match current installations.

```
/usr/share/filebeat/
   bin/
     filebeat-god
     filebeat
   kibana/
        load.sh
        searches/
        visualisations/
        dashboards/
        index-patterns/
/etc/filebeat/
    filebeat.yml
    filebeat.template.json
/var/lib/filebeat/
    registry.json
    filebeat.uuid
```
The init scripts, start filebeat with:

```
   /usr/share/filebeat/filebeat --path.data /var/lib/filebeat
                                             --path.config /etc/filebeat/
```

The downside of moving the binary out of /usr/bin is that it gets a bit more complex to run in foreground from an installed system. This is because the binary is not in the system `PATH` anymore and because the data path and config paths need to be set correctly. We could mitigate this by providing a shell script in `/usr/bin`.

### Windows 

On Windows there are two options. Either run directly from the unzipped directory, in which case everything works as for the tar/zip case, or you install as a service. If you install as a service, the data path is set to `c:\ProgramData\filebeat`, so the we have the following structure:

```
{extractpath}/
   filebeat
   filebeat.template.json
   filebeat.yml
   dashboards/
        load.sh
        searches/
        visualisations/
c:\programdata\filebeat
   registry.json
   filebeat.uuid
```

The service will start filebeat with:

```
  $extractpath/filebeat -path.data c:\programdata\filebeat
```

This is not ideal yet, but matches pretty much what we have so far, fixes the automatic template loading and can be improved when we get a real Windows installer.

## Required changes

* [x] Add CLI option `-path.home`. #1373
* [x] Add CLI option `-path.data`. #1373
* [x] Add CLI option `-path.config` #1373
* [x] Add CLI option `-path.logs` (lower prio). #1437 
* [x] Change the default of filebeat registry location from `.filebeat` to `{data_path}/registry` #1373
* [x] Provide a libbeat function to open files from one of the location above ("data", "config", "log", or by default from "home") #1373
* [x] Use the config path to look for the template. #1373 
* [x] Change winlogbeat to have use the data path for it's registry file. #1386
* [x] Update DEB/RPM scripts to deploy files under `/usr/share/{beatname}`. #1385
* [x] Update packer to install the dashboards unde the `kibana` folder for all platforms. #1399 
* [x] Update init scripts and unit files to use the new CLI flags. #1385 
* [x] Document new CLI flags and configuration options. #1441 
* [x] Add `namebeat.sh` scripts to `/usr/bin` to make it easy to run beats in foreground. #1446
* [x] Make the confidir option from Filebeat yml file, relative to the config path. #1435

**Comment by ruflin** [comment]
I like the proposal. You state `path.config has the same default as path.data`, this should be `path.home`, right?

Could it make sense to add these also as configuration option to the config file? This would allow to run `beat -c path/config.yml` and the other paths would be read from the config file. 

For the data directory, should we add it to the git repository but ignore all files inside?

**Comment by tsg** [comment]
> I like the proposal. You state path.config has the same default as path.data, this should be path.home, right?

Yep, fixed :-).

> Could it make sense to add these also as configuration option to the config file? This would allow to run beat -c path/config.yml and the other paths would be read from the config file.

Yeah, they are configuration options, see #1373. The plan is that after https://github.com/urso/ucfg/issues/15 is implemented, they will only be configuration file options, which can be overwritten from the command line.

> For the data directory, should we add it to the git repository but ignore all files inside?

I'll add `/data/` to `.gitignore`. The beats are creating the path automatically if it doesn't exist.

**Comment by tsg** [comment]
All PRs merged, yohoo!
