### ISSUE TITLE
Breaking changes for 8.0

### ISSUE THREAD

**Issue by odacremolbap** [elastic/beats#13911]
List of breaking changes we plan to do for `8.0.0`. All items must have an owner.

**Metricbeat**

- [x] `kubernetes`, `state_container`, metric `kubernetes.container.id` being replaced with `container.runtime` and `container.id`.  @MichaelKatsoulis @ChrsMark 
https://github.com/elastic/beats/pull/13884 
- [x] `kubernetes`, `state_container`, metric `kubernetes.container.name` being replaced by `container.name` and `kubernetes.container.name` being replaced by `container.image.name` @MichaelKatsoulis @ChrsMark 
https://github.com/elastic/beats/pull/23802
- [x] Remove deprecated fields from `docker` module. @mtojek https://github.com/elastic/beats/pull/27933/
- [x] Remove deprecated fields from `kafka` module. @jsoriano https://github.com/elastic/beats/pull/27938
- [x] Remove deprecated fields from `kubernetes` module. @MichaelKatsoulis @ChrsMark 
- [ ] Remove deprecated fields from `nats` module. @endorama 
- [ ] Remove deprecated fields from `redis` module. @aspacca https://github.com/elastic/beats/pull/28246
- [x] ~~Refactor jolokia fields (under discussion)
https://github.com/elastic/beats/issues/13316 @jsoriano~~
- [x] Remove `default_region` in aws module config
https://github.com/elastic/beats/issues/13535
@kaiyan-sheng 
- [ ] Remove network and diskio metrics from ec2 metricset
https://github.com/elastic/beats/issues/13359
@kaiyan-sheng
- [x] k8s Metadata TODOs for v8.0.0
https://github.com/elastic/beats/issues/16483
@ChrsMark  @MichaelKatsoulis 
- [x] Remove `aws_partition` from AWS 
https://github.com/elastic/beats/issues/23590
@kaiyan-sheng 
- [ ] Renaming GCP metric names 
https://github.com/elastic/beats/issues/27231
@endorama 

**Filebeat**

- [x] Use the `flattened` type to store attributes from mongodb json logs, and remove `log.original` (see https://github.com/elastic/beats/pull/24774#issuecomment-862153301 for context). (TBD if this is even possible with the current license) @jsoriano 
- [x] Change validation on Filebeat AWS S3 input so that if both var.bucket_arn and var.queue_url are not set Filebeat will exit with an error
#27526
@aspacca 
- [x] Make all filesets disabled by default. @adriansr 
https://github.com/elastic/beats/issues/17256
https://github.com/elastic/beats/pull/27762
https://github.com/elastic/beats/pull/27526
- [x] Remove deprecated coredns fields @efd6
#28196

**Libbeat**

- [x] Remove agent.hostname field from libbeat
https://github.com/elastic/beats/pull/18328
https://github.com/elastic/beats/issues/12983 (remove the alias) @kaiyan-sheng 

- [ ] Make `default_field: false` the default for fields.
https://github.com/elastic/beats/issues/28215

**Comment by odacremolbap** [comment]
Items to consider:

- https://github.com/elastic/beats/issues/11835
- https://github.com/elastic/beats/issues/12983

**Comment by ChrsMark** [comment]
Also this might be related: https://github.com/elastic/beats/issues/13316

cc: @jsoriano, @exekias

**Comment by kaiyan-sheng** [comment]
- [ ] Remove `default_region` in aws module config: https://github.com/elastic/beats/issues/13535

- [ ] Remove network and diskio metrics from ec2 metricset: https://github.com/elastic/beats/issues/13359

**Comment by jsoriano** [comment]
> Also this might be related: #13316

Added to the list so we don't forget, thanks @ChrsMark!

@kaiyan-sheng I have added the topics you mention to the list.

**Comment by aspacca** [comment]
https://github.com/elastic/beats/pull/27612#discussion_r700882058

Change validation on Filebeat AWS S3 input so that if both `var.bucket_arn` and `var.queue_url` are not set Filebeat will exit with an error (changed in 7.15 waiting for https://github.com/elastic/beats/pull/27526)

**Comment by P1llus** [comment]
Removing old module aliases:
Observability: https://github.com/elastic/beats/pull/27919
Security: https://github.com/elastic/beats/pull/27915

**Comment by adriansr** [comment]
Make all filesets disabled by default. @adriansr 
https://github.com/elastic/beats/issues/17256
https://github.com/elastic/beats/pull/27762
https://github.com/elastic/beats/pull/27526

**Comment by adriansr** [comment]
Added:

- [ ] Make `default_field: false` the default for fields.
https://github.com/elastic/beats/issues/28215
