### ISSUE TITLE
meta: Docker log driver plugin, explerimental to GA

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#13990]
We have a branch on feature/dockerbeat. Name is TBD.

This is a docker logging plugin that's installed via `docker plugin install...` and works alongside the docker engine to send logs to elasticsearch. It uses libbeat and supports most of the config options and outputs libbeat does. Initial commit was  elastic/beats#13761

### Experimental Release - 7.6

- [x] We need an actual name
- [x] internal logging is a mess 
- [x] Send out container tags  #14615

- [x] The code that reads from the FIFO pipe is a mess, and copied from docker's example plugin. The protobuf reader is questionable, and we might want to implement our own reader. elastic/beats#14375
- [x] remove trailing `\r` from log lines  elastic/beats#14615
- [x] Potential race with creating new pipelines elastic/beats#14518 
- [x] Go version used on master is enforcing import format comments, breaking `docker/engine` elastic/beats#14523
- [x] We need a test suite elastic/beats#14828
- [x] `make check` and `make fmt` support?
- [x] Use LoadWithSettings elastic/beats#15038
- [x] Use proper dedot/stripping functions
- [x] We need to figure out how to get on the docker plugin store
- [x] Clean up vendor/ and deal with conflicting docker/prometheus dependencies 
- [x] Proper asciidocs working on this with @dedemorton elastic/beats#15799 

### 7.9.0

- [x] Address remaining docs TODOs in https://github.com/elastic/beats/issues/13990
- [x] Create a config shim https://github.com/elastic/beats/pull/18605
- [x] `docker logs` needs to work. This may depend on the spooling features.

### 7.10.0

- [x] ECS compliance and integration with Kibana Logs
- [x] Docker certification 

### Later

- [ ] We need to make some kind of decision about how we'll drop events. If the plugin's FIFO queues get backed up, the container's writes to stdio will block.
- [ ] Create an ingest pipeline manager to ingest documents based on container tags and names. This reduces the need for addtional config flags. Designing this with @urso .
- [ ] Parsing of JSON messages
- [ ] Multiline support
- [ ] Can we get this to send its own logs / health data to ES?
- [ ] some kind of integration test suite.
- [x] Update `documentation` in config.json

## Testing

This is fairly easy to test.

Once you have everything pulled down, run `mage buildAndInstall` to build the plugin. Docker plugins are configured with `--log-opts`, you can start a plugin using the log handler with:

```
$ docker run --log-driver=elastic/elastic-log-driver:8.0.0 \
--log-opt output.elasticsearch.hosts="172.18.0.2:9200" \
--log-opt output.elasticsearch.index="dockerbeat-test" \ 
-it debian:jessie /bin/bash`
```

Almost any option that you would specify with `-E` in filebeat, you could specify with `--log-opt` in the plugin.

**Comment by andresrc** [comment]
Given that this introduces a new artifact, we should also include here the integration in the build pipeline and the release process (/cc @exekias )

**Comment by exekias** [comment]
I just saw the `docker logs` command part. That sounds a bit complex, perhaps we could move it to be done after the initial experimental release? cc @sorantis

**Comment by jlind23** [comment]
@fearful-symmetry any chance you remember what we should do with this one?

**Comment by fearful-symmetry** [comment]
@jlind23 it's technically GA, but heavily on the backburner, due to...everything going on, and also the extreme limitations of docker's plugin API.

**Comment by jlind23** [comment]
@fearful-symmetry thanks, then i'll close this one :)
