### ISSUE TITLE
7.5 Beats documentation roadmap

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#14081]
Changed or deprecated features:

- [x] Deprecate beats central management docs: https://github.com/elastic/beats/issues/14045 [DeDe] - https://github.com/elastic/kibana/pull/49423 and https://github.com/elastic/beats/pull/14104 (in progress)

Release-related docs:

- [x] Document breaking changes: https://github.com/elastic/beats/pull/14398 (in progress)
- [x] Document release highlights. https://github.com/elastic/beats/pull/14398 (in progress)
- [x] Review and, if necessary, edit the release notes (changelog). [DeDe]

Other changes:
- [x] Refactor processor docs by moving processors under the code modules. https://github.com/elastic/beats/pull/14410
- [x] Refactor input docs by moving inputs under code modules. https://github.com/elastic/beats/pull/14724
