### ISSUE TITLE
Kubernetes Autodiscovery Improvements

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#14159]
Meta issue to group the different fixes and enhancements to make in k8s autodiscovery

- [x] Kubernetes Global Autodiscover (#10578)
- [x] Add JSON options to hints (#12634)
- [ ] Move away from kubelet stats/summary (#12792)
- ~[ ] Add single state-metrics metricset (#12938)~
- [x] Make kubernetes autodiscover and metadata work for other resources (#14044)
- [x] Add namespace labels to kubernetes metadata (#13873)

**Comment by exekias** [comment]
@odacremolbap I'm closing this one as #12792 wasn't finally scheduled as part of this effort (as kubernetes 1.18 is not out yet). I guess we will push for that one once 1.18 is out
