### ISSUE TITLE
Configuration refactoring

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1417]
This is a meta issue for reorganizing our default configuration files for 5.0. The problems we're trying to solve are:

* Getting whitespace wrong in YAML is our number one source of issues on discuss. Now the Beats supports dotted notation (e.g. `output.elasticsearch.hosts`) in the configuration file, which greatly reduces the indentation levels required.
* Inconsistent namespacing around Beats. Filebeat has all its options under `filebeat`, Topbeat has/had `input`, Packetbeat has several options toplevel. Correct namespacing is a prerequisite for building more Beats in the same binary/process.
* The Libbeat options are not well organized, we have some stuff top level and some other stuff under `beat`.
* Because we put all available options in the configuration file, the default files have gotten really large and hard to modify for the common options.

TODOs:

* [x] Rename the `input` section to `topbeat` in Topbeat. #1211.
* [X] Move top level Packetbeat sections (`interfaces`, `flows`, `protocols`, `procs`) under the `packetbeat` namespace #1490
* [x] Move settings from the `beat` namespace to top level. #1570
* [x] Change libbeat configuration file to use the dotted notation #1544 #1624
* [x] Change topbeat configuration file to use the dotted notation #1544 #1624
* [x] Change filebeat configuration file to use the dotted notation #1544 #1624
* [x] Change packetbeat configuration file to use the dotted notation #1544 #1624
* [x] Change winlogbeat configuration file to use the dotted notation #1544 #1624
* [x] Change metricbeat configuration file to use the dotted notation #1544 #1624
* [x] Create migration guide/tool: #1488
* [x] Update the system tests with the latest format of the config files. #1688 
* [x] Create a minimized version of each config file. Make it the default. #1637 #1674 #1682
* [x] Add Kafka and Redis outputs to the "full" config files. #1690 
* [x] Review all docs to update examples from configuration files. #1709

**Comment by tsg** [comment]
All done. 😎
