### ISSUE TITLE
Support for setting the document ID

### ISSUE THREAD

**Issue by urso** [elastic/beats#14363]
For helping users to reduce duplicates in Elasticsearch, Beats should have some opt-in support to configure the document ID. If the field `@metadata.id` is set, Beats will already use said ID as document ID. But this feature is still well hidden, because we currently have no support for setting this field.

If the document ID is set, Beats will publish using the `op_type` `create`.

- [x] Add support to read IDs from existing JSON logs elastic/beats#5844 
- [x] fingerprint processor elastic/beats#14205
- [x] processor adding a randomized UUID like ID (for example for metrics data) https://github.com/elastic/beats/pull/14524

**Comment by urso** [comment]
@ycombinator Can we close this issue?

**Comment by ycombinator** [comment]
Yep! Resolved via #5844, #14205, and #14524.

**Comment by urso** [comment]
Testing:
While testing I found that we are missing support for setting the document ID via the json_decode_fields processor. The processor is used when JSON documents/events are embedded as strings. Fix is available in https://github.com/elastic/beats/pull/15859

**Comment by mdelapenya** [comment]
Hi! 👋 Does this issue need to be added to the `v7.6.0` test plan? Then I'd see convenient to add that label.

Thanks!

**Comment by urso** [comment]
Added missing v7.6.0 label. All found issues have been resolved in 7.6.
