### ISSUE TITLE
Add condition to a filtering rule

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#1447]
Related to #451 

> If more filtering rules are defined, then they are executed in the order they are defined. The initial event is passed to the first filtering rule and what results from it is passed to the second filtering rule until all the filtering rules are applied. The condition that is used in the following filtering rules is running against the event that is received as input and it might defer from the original event.

Condition types:

- [x] equals
- [x] contains
- [x] regexp
- [x] range
- [x] and
- [x] or
- [x] not

### Equals
Accepts only integers and strings.

```
equals:
  type: process

equals:
  proc.name: test

equals:
  http.response.code: 200

```

### Contains
Accepts only strings.

```
contains:
  proc.name: topbeat
```

### Regexp
Accepts only strings that include a regular expression.

```
regexp:
  proc.name: "$beat"
```

### Range
Accepts only integers and floats.

```
range:
  proc.cpu.total_p:
    gte: 0.5

range:
  responsetime:
    gte: 30
```

### Combine two conditions
You can specify a list of conditions under each type and they are combined with `and`. For example, the following conditions selects the `type=process and proc.name=test:

```
equals:
  type: process
  proc.name: test
```

### OR/AND/NOT operators

```
or/and/not:
  - <condition>
  - <condition>
  - <condition>
```

where `<condition>` can contain any of the actions vailable including other `or`, `not`, `and`.

### Required changes:

- [x] Add conditions #1395 
- [x] Pluggable filtering rules #1623 
- [x] Add operators #1983 
- [x] Add drop_event action #1623 
- [ ] Add include_event action
- [x] Be able to pass fields that contain `.` in the condition #1623 
- [x] Add a sample example in libbeat.yml
- [x] Add system tests for Topbeat, Packetbeat, Filebeat #1623 
- [ ] Update documentation to include conditions
- [x] Add system tests for Metricbeat #1623
