### ISSUE TITLE
Move all test files of metricbeat modules to their own directories

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#14606]
Currently there are some test files that are in a common directory, and we also have big shared docker compose files used for tests. After some changes done lately we could move all this data to the module itself, so all test information resides in the same place as the module code. This will help to identify what files are associated to each module, and to better know what files will need to be added when creating a new module. This will also help on development and CI to identify what tests need to be run for each module.

This includes:
- [x] Move python tests to the module directories. (#14624)
- [x] Move docker-compose definitions to a new `docker-compose.yml` file in each module directory. (#14624)
- [ ] Add a `_meta/supported-versions.yml` file to the module.
- [x] Use `_meta/supported-versions.yml` for the versions used in system tests. (#14624)
- [ ] Update dev documentation

Secondary goals
- [ ] Add templates for files to the module generator for integration and system tests, `supported-versions.yml` and `docker-compose.yml`.
- [ ] Use `supported-versions.yml` as input for docs.

For more context, look at these issues:
- elastic/beats#12909 and elastic/beats#13186 - Support for separated docker compose definition and example migration of Apache module.
- elastic/beats#14520 - Use of `supported-versions.yml` file for running system tests on all the supported versions of a service, examples with mysql and apache.
- elastic/beats#14355 and elastic/beats#14587 - Use of `supported-versions.yml` file to prebuild docker images in CI for integration, system and E2E tests.

**Comment by jsoriano** [comment]
Closing this as we have the focus on integrations now. If further changes are done in modules testing it will be done from the point of view of integrations.
