### ISSUE TITLE
[Agent] Allow the agent to retrieve configuration from fleet

### ISSUE THREAD

**Issue by ph** [elastic/beats#14951]
- [x] Update the Authentication elastic/beats#14867 
- [x] Change the enroll elastic/beats#14869 
- [x] Create a Fakewebapi to simulare the endpoint elastic/beats#14945 
- [x] Create the necessary calls in the fleetapi elastic/beats#14871
- [ ] Add the new "Fleet manager"
  - [x] Create action dispatcher
  - [x] Refactor the emitter to receive a concrete *config.Config
  - [x] Create initial handlers for PolicyChange, Default and Unknown.
  - [x] Create the gateway for fleet command
  - [x] Encapsulate the "Tick" we can easily swap it out or change the frequency.
  - [x] Refactor reporter to use the gateway. @michalpristas 
  - [x] Cleanup in the Agent application initialization.
  - [x] Followup PR for error reporting. @ph
  - [x] Followup add variable to the API Call so not all request are done at the same time.

---

Current architecture idea.

![fleet-communication](https://user-images.githubusercontent.com/640/70274715-a0d53e00-177a-11ea-8c6e-cb748f728eb8.png)

**Comment by ph** [comment]
@michalpristas If you can take a look at the above design, this is what I am currently working on, but there is a caveat or I would say questions for the `ActionDispatch` implementation. Lets consider the fact the Fleetapi Packages takes care of unmarshaling the response from raw response into concrete type of Action, like the "ActionPolicyChange", Maybe `AgentConfigurationChange`, `ActionPause` etc.

There are two ways that we could make it works.

1. We add a register method in the `ActionDispatch` with a signature similar to this, and we do the typecasting to the appropriate action in Handle method. Sadly, we lose a bit of type safety and this require us to loop at worst through all the actions.

```golang
type handler interface {
 Handle(fleetapi.Action) error
}

RegisterAction(actionType string, h handler)
```

2. Good old switch case on type, where the action dispatch is mostly just a big static router. The problem with that approach is DI is hard to do in that case.

I wonder if we could have option 2 while keeping the benefit of having DI of the ActionHandler.

**Comment by michalpristas** [comment]
@ph switch case i think is ok but is not dynamic, option 1 is dynamic but resolution is slow in a need of iteration through many actions.

how about something like this https://play.golang.org/p/fVG7nOhlTrl

it uses reflect thought but it is dynamic. allows registration and resolution is one step map lookup.

in the diagram above is Gateway a client? is it responsible for anything but communication? otherwise it looks like what we discussed so i think it's ok

**Comment by ph** [comment]
I like the idea of the reflection in that case, this is not something I usually take.

The gateway is responsible of the following:

- Enqueue events to be send on the next Tick() / fetch of configuration.
- Periodically Poll the configruation endpoint.
-Send events to the action handler.

**Comment by ph** [comment]
updated description with current tasks.

**Comment by ph** [comment]
I think there one thing that changes from the above graph is we could the reporter to the gateway and the pseudo will becomes likes this.

- on each ticks
- Ask reporter for Events (Take X, remaining Y)
- Create a checkinRequest.
- Post the Request.
- Unserialized the request.
- Send the Actions to the ActionDispatcher.
- Executes Action in order.
- Add new events to the reporter.
- loop.

One question I do have is we have the notion of dropping events and I don't think it's possible to keep that unless we have some kind or priority in the event.

**Comment by michalpristas** [comment]
we can drop dropping for now and think it through, create a followup issue. I think dropping is not critical for MVP but we need to get back to it after it for sure. Maybe dropping is not the right solution to the problem of extensive reporting. We can rethink it

**Comment by ph** [comment]
Fixed for the memory leak in ecslog is ready for review https://github.com/urso/ecslog/pull/17

**Comment by ph** [comment]
@michalpristas is working into moving the fleet reporting to use the Gateway above.

Myself, I am working on testing the real API and add support for acking the action received from the API.

**Comment by ph** [comment]
Follow up issue for Jitter / distributes call https://github.com/elastic/beats/issues/15283
