### ISSUE TITLE
Generic SQL module

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#15048]
Add a generic SQL module so metrics and other data can be collected using custom SQL queries, the module will support the different drivers included in Metricbeat binary.

This is a follow-up of the initial implementation in https://github.com/elastic/beats/pull/13257.

Other related issues:
* Allow custom queries for MySQL and PostgreSQL https://github.com/elastic/beats/issues/2987
* Add a Metricbeat helper for SQL https://github.com/elastic/beats/issues/9416
* Add support for IBM DB2 https://github.com/elastic/beats/issues/13106
* Add support for "key/value" responses https://github.com/elastic/beats/issues/15770

## Modules

For a metricset to go GA, the following criterias should be met:

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [x] Integration tests exist, for several drivers in this case
* [x] System tests exist, also for several drivers
* [x] Automated checks that all fields are documented
* [ ] Documentation https://github.com/elastic/beats/issues/18743
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] ~~Dashboards exists (if applicable)~~
* [ ] ~~Kibana Home Tutorial (if applicable)~~
  * ~~Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).~~

## Metricbeat module

* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [x] Test environment in Docker exist for integration tests

## SQL module

* [x] Review vendorization of sql drivers, move them to common vendor directories and use released tags when possible (done as part of migration to go modules).
* [ ] Consider importing drivers from the sql module so dependency is more easily tracked.
* [ ] Add support for `username` and `password` options as best effort (it is going to depend on the DSNs supported by the driver, see #15686)
* [ ] Add support for sanitization of more DSN formats (see #15686)
* [ ] Include DSN examples in the documentation for each one of the supported databases
* [x] Reuse connections between fetches. elastic/beats#16001
* [ ] Reconsider the use of `sqlx`, it doesn't seem to be needed with current implementation
