### ISSUE TITLE
Filebeat input v2 API

### ISSUE THREAD

**Issue by urso** [elastic/beats#15324]
This meta issue tracks all PRs, issues and tasks for a new input API in Filebeat. The new API also introduces a generic key-value store as registry, for reuse by other inputs. Development targets the feature branch [feature-new-registry-file](https://github.com/elastic/beats/tree/feature-new-registry-file). Related issues/PRs will be labeled the `Project:Filebeat-Input-v2`.

### Initial Phase

- [x] Generic Registry as key-value store:
  - [x] Introduce statestore package #19117 
  - [x] Registry migration: https://github.com/elastic/beats/pull/12908
  - [x] Filebeat registrar using new registry type: https://github.com/elastic/beats/pull/12908
- [x] State Store
 - [x] Define and implementation API: https://github.com/elastic/beats/pull/14079
 - [x] Testing
- [ ] Input API
  - [x] Define API for inputs: https://github.com/elastic/beats/pull/14229
  - [x] Input Loading support for new style inputs:
  - [x] Integrate with config reloading and autodiscovery
  - [ ] Integrate with Agent/Fleet status reporting
  - [x] Testing
- [x] Registry garbage collection support

### Next

- [ ] Convert existing inputs to the new API
  - [x] kafka https://github.com/elastic/beats/pull/27335
  - [ ] redis
  - [ ] syslog
  - [ ] udp
  - [ ] TCP
  - [x] aws s3 https://github.com/elastic/beats/pull/20005
  - [x] aws cloudwatch https://github.com/elastic/beats/pull/29695
  - [ ] azure eventhub
  - [ ] gcp pubsub

The inputs log, container, docker and stdin are not going to be moved. Instead these should be replaced by filestream or dropped altogether.
~~- [ ] log/container/docker/stdin~~
~~- [ ] factor out file watcher emiting events~~
~~- [ ] update to new API~~
~~- [ ] split up into independent inputs~~

- [x] Add existing Beats as new inputs
  - [x] Journaldbeat
  - [x] Winlogbeat
 
We decided to keep log input around so users are not forced to update.
~~- [ ] Remove old input API and supporting architecture~~
~~- [ ] remove filebeat/channel package~~
~~- [ ] remove state support from input/file package~~
~~- [ ] remove registrar package~~

**Comment by ph** [comment]
Thanks @urso for pushing this effort!

**Comment by jlind23** [comment]
Needs to be closed by @kvch

**Comment by kaiyan-sheng** [comment]
I'm adding `aws-cloudwatch`, `gcppubsub` and `azureeventhub` input into the `Convert existing inputs to the new API` list.

**Comment by jlind23** [comment]
@rameshelastic it seems that the missing input are on your plate, am I correct?

**Comment by rameshelastic** [comment]
@jlind23 ..hmm..I'm not sure. 

+ @masci ..could you help clarify?

**Comment by jlind23** [comment]
@rameshelastic you are right, not all of them.

- redis must belong to you.
- syslog must belong to @elastic/security-external-integrations 

All the three below belongs to @elastic/obs-cloud-monitoring 
- aws cloudwatch
- azure eventhub
- gcp pubsub

**Comment by kvch** [comment]
We are moving to the new input system, so I think this can be closed. @jlind23 WDYT?
