### ISSUE TITLE
[Agent] TODO from the POC

### ISSUE THREAD

**Issue by ph** [elastic/beats#15474]
- [x] Round tripper  #15472
- [x] setup ILM disable #15468
- [x] Disable template setup #15472 
- [x]  Investigate permissions required for api key. https://github.com/elastic/beats/issues/15403 Followup on Kibana https://github.com/elastic/kibana/pull/54658
- [x] Investigate scheduler panic on halt #15481
- [x] Investigate backoff jitter error concerning the random wait.  Retry options cause a panic to `rand.Int63n`
- [x] The configuration is not always received from Fleet or applied. (when ack config is not received again) https://github.com/elastic/beats/issues/15507 @ph
- [x] When datasources are unassigned the beats are not stopped? (bad config or bad operator behavior? @michalpristas #15615
- [x] Investigate why the host is not visible in the ui. #15465
- [x] Removing all datasources in the UI doesn't stop the processes https://github.com/elastic/beats/pull/15510
- [x] worker loop exit when the client doesn't have the right credentials? fixed
- [ ] Send data of Filebeat to "logs" https://github.com/elastic/beats/issues/15391
- [ ] Send data of Metricbeat to "metrics" https://github.com/elastic/beats/issues/15391
- [x] Relative path are not supported in the configuration. https://github.com/elastic/beats/issues/15328 @michalpristas 
- [x] Small cleaning / typos #15573 @michalpristas

**Comment by ph** [comment]
fyi @michalpristas

**Comment by ph** [comment]
cc @ruflin just to keep you in the loop, almost done

**Comment by ph** [comment]
item`worker loop exit when the client doesn't have the right credentials?` is linked to the int63n issue.

**Comment by ph** [comment]
@michalpristas do you mind to look at the following?

```
Investigate backoff jitter error concerning the random wait. Retry options cause a panic to rand.Int63n
```

There are two places which are incorrect, the default values received by the FleetGateway and the retry for the operator.

**Comment by ph** [comment]
I've looked at the `Removing all datasources in the UI doesn't stop the processes`, we have an explicit assert to error on empty streams in the `program.Program`. I think just removing that assert would be fine with the stateresolver but I will still check.

**Comment by michalpristas** [comment]
@ph i will check the backoff issue

**Comment by ph** [comment]
Added names next to the items.

**Comment by michalpristas** [comment]
trying to reproduce unassigned data source with local config changes 
periodic watcher over agent.yml - beats are correctly stopped on darwin and ubuntu 
i need to verify with kibana

**Comment by ph** [comment]
@michalpristas maybe we could add more logging on the data received from the API, I was on the fence about that because it's an easy way to leak unwanted information like credentials.

**Comment by michalpristas** [comment]
maybe we can filter out data or provide just a summary, something like `received 3 streams...`

**Comment by ph** [comment]
> maybe we can filter out data or provide just a summary, something like received 3 streams...

Maybe numbers of outputs and the hash of the configuration? If we see multiple time the same hash we know that we receive the same config.

**Comment by ph** [comment]
Going to close this meta-issue and keep only the index issues open.
