### ISSUE TITLE
[Meta] Istio Metricbeat Module

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#15505]
# Istio Metricbeat Module
This is issue aims to track any implementation, concern, discussion, proposal around Istio integration with Metricbeat. 

Istio: https://istio.io/
Istio Metrics: 

- https://istio.io/docs/tasks/observability/metrics/collecting-metrics/ 
- https://istio.io/docs/tasks/observability/metrics/querying-metrics/#about-the-prometheus-add-on
- https://istio.io/docs/reference/config/policy-and-telemetry/metrics/

# Metricbeat Module / Dataset release checklist

This checklist is intended for Devs which create or update a module to make sure modules are consistent.

## Modules

For a metricset to go GA, the following criterias should be met:

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] Integration tests exist
* [ ] System tests exist
* [ ] Automated checks that all fields are documented
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).

## Metricbeat module

* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests

cc: @exekias

**Comment by ChrsMark** [comment]
# Sample metrics

Setting up the [sample application](https://istio.io/docs/examples/bookinfo/) of Istio to collect [sample metrics](https://istio.io/docs/tasks/observability/metrics/collecting-metrics/) the following Istio specific metrics can be captured:

Prom querry: `http://localhost:9090/federate?match[]={__name__=~%22istio.*%22}`

Metrics:

**Comment by ChrsMark** [comment]
# Metricsets

- [ ] Istio mesh metrics: https://github.com/elastic/beats/pull/15535
- [ ] Pilot metrics
- [ ] Galley metrics
- [ ] Citadel metrics

**Comment by ioandr** [comment]
Hi folks,

this issue seems very interesting and I would like to contribute some dev cycles on this. For a start, I could take on some of the proposed metricsets, e.g., the Pilot metrics.

@ChrsMark WDYT?

**Comment by ChrsMark** [comment]
This is great @ioandr, feel free to work on this!

**Comment by ChrsMark** [comment]
We may need to revisit this one after the introduction of the Istiod (https://istio.io/latest/news/releases/1.5.x/announcing-1.5/#introducing-istiod).

**Comment by ChrsMark** [comment]
I did an investigation on the new `istiod` regarding monitoring. The thing here is that all standalone prometheus exporters of the previous microservices are not existent any more with this new monolithic approach. Currently all metrics are exposed by a central Prometheus server and not all of the internal endpoints from where Prometheus scrapes are exposed outside directly. 

Maybe in order to support the newer versions we should go with a solution based on a light weight module on top of Prometheus module which will collect all the related metrics from the Prometheus `federate` API.

**Comment by exekias** [comment]
@ChrsMark I'm wondering... is Prometheus server a mandatory piece in Istio deployments?

**Comment by ChrsMark** [comment]
> @ChrsMark I'm wondering... is Prometheus server a mandatory piece in Istio deployments?

From https://preliminary.istio.io/latest/docs/ops/best-practices/observability/#using-prometheus-for-production-scale-monitoring, it seems so:

```
In default deployments of Istio, a deployment of Prometheus is provided for collecting metrics generated
for all mesh traffic. This deployment of Prometheus is intentionally deployed with a very short retention
window (6 hours). 
```

**Comment by ChrsMark** [comment]
However, installing `1.7.1`  (https://istio.io/latest/docs/setup/getting-started/) seems that `istiod` exposes metrics at `15014` port:
```
Port:              http-monitoring  15014/TCP
TargetPort:        15014/TCP
Endpoints:         172.17.0.14:15014
```
In order to access metrics endpoint: `kubectl -n istio-system port-forward svc/istiod 15014:15014`
And then hit `localhost:15014/metrics`.
Sample metrics:
[istiod.txt](https://github.com/elastic/beats/files/5223681/istiod.txt)

`pilot`, `mixer`, `galley` and `citadel` metrics are exposed. So, we can create a new metricset called `istiod` to cover the new versions?

cc: @masci

**Comment by exekias** [comment]
Does `istiod` provide the same level of detail? IIRC mixer and others were pretty verbose

**Comment by ChrsMark** [comment]
Latest implementations to support new versions of Istio (>=1.5):

- #21751 -> proxy metricset (replacing Mixer metrics: https://istio.io/v1.5/docs/reference/config/telemetry/metrics/)
- #21519 -> istiod metricset (replacing pilot, citadel, galley metrics)


Dashboards have been added for these new metricsets.

**Note** The above metricsets are BETA. The reason of this is that they are implemented as leight-weight modules on top of `prometheus` module and make use of `use_types` setting. This setting is still in BETA and hence we cannot move these metricsets to GA before moving the setting to GA (the setting is expected to change in the near future because of https://github.com/elastic/elasticsearch/issues/61939)
