### ISSUE TITLE
[Meta] Filebeat mqtt input

### ISSUE THREAD

**Issue by faec** [elastic/beats#15602]
This is a tracking issue for the in-progress MQTT input .

Pending requirements:
- [x] Initial draft checkin (#15287)
- [x] Reconnection after errors (#15982)
- [x] Clean shutdown / reliable `Stop` and `Wait` (#15982)
- [ ] Ack handling (#15610)
  * (Need more background here, it's not clear to me yet if / how we need to handle this)
- [x] Documentation (for all new config fields and emitted event fields) (https://github.com/elastic/beats/issues/16126)
- [x] Tests 
  * [x] Unit tests (#15982)
    - code that translates configuration + raw MQTT input to beats events should be refactored into a standalone function and unit tested.
  * [x] System tests (#16125)
    - bring up the input with a live connection to localhost and pass it test events. This is usually done in the python tests, but if we can get good coverage in go instead I'd be happy (that usually makes verification simpler since you can pass in a mocked outlet for outgoing events instead of requiring a real backend index, but if library support or other context makes it easier in python then that's fine).
- [x] Merge to master and update changelog (https://github.com/elastic/beats/pull/16204)

**Comment by mtojek** [comment]
I will take a look at ACK handling.

**Comment by mtojek** [comment]
The branch has been rebased and merged (also licensing script has been updated). I'm proceeding with https://github.com/elastic/beats/issues/15982 .

**Comment by mtojek** [comment]
I'm working on the integration test to verify the module.

**Comment by tonygunter** [comment]
Why not just allow the handler to call Ack() manually?  Hander { unmarshall message -> process message -> forward to next receiver -> ACK}?   At this point, the mqtt.Message.Ack() function, wrapping a sync.once.Do function like it does, never actually executes any code except once inside matchAndDispatch.
