### ISSUE TITLE
Remove global logging functions in libbeat

### ISSUE THREAD

**Issue by urso** [elastic/beats#15699]
In order to better support structured logging, we want to get rid of the global logger functions. The API of the global logger functions is not in line with the methods defined by `(*logp).Logger`.

For now we will focus on libbeat first.

## Refactoring Notes/Tips:

- replace `logp.Debug/Info/Warn/...` with `f` variants like `(*Logger).Debugf/Infof/Warnf/...` if a format string has been used. Otherwise stick with `(*Logger).Debug/Info/...`
- Use `%+v` when logging an error using a format string. Some logger libraries implement fmt.Formatter and will print the wrapped error only if `+` is given.
- `logp.Debug` accepts as first argument the `selector` name. `*logp.Logger` instances have a name and the selector name must be removed when switching to `(*Logger).Debugf` 
- use `(*Logger).Named` (prefer `(*Logger).Named`) to create a logger instance in order to replace logp.MakeDebug. For now in unit tests you can use `logp.L()` if you need to pass a logger you don't care about
- use `logp.NewLogger` to reduce the amount of transitive changes. `NewLogger` will be removed in the future as well, but for now it can help to reduce PR sizes.
- store/pass logger instances locally. Do not store logger instances in private package  global variables.
- Use the compiler:
  - use `tags=nologpglobal` to compile/test a package without logp global logging functions being available
  - Do dependend packages still build?
- Consider error values.
  - If we log a message without context and return an error value to be logged with a similar message, consider to just return the error value
  - If we log a message, but return the original error consider to remove the log message and wrap the error using an appropriate error message.

## Tasks

- [x] Add nologpglobal build tag to logp elastic/beats#15700 
- [ ] libbeat cleanups:
  - [ ] libbeat/autodiscover
    - [ ] appenders/config
    - [ ] builder
    - [x] providers
      - [x] docker  #16003   
      - [x] kubernetes #16003   
      - [x] jolokia #16003   
    - [ ] template
  - [ ] libbeat/cfgfile
  - [ ] libbeat/cloudid #18500
  - [ ] libbeat/cmd/instance
  - [x] libbeat/common/bus #16003   
  - [ ] libbeat/common/config.go
  - [x] libbeat/common/docker #16003   
  - [ ] libbeat/common/event.go elastic/beats#16149 
  - [x] libbeat/common/fmtstr elastic/beats#15943 
  - [x] libbeat/common/kubernetes #16003   
  - [x] libbeat/common/jsontransform #18550
  - [ ] libbeat/common/safemapstr
  - [ ] libbeat/common/schema
  - [ ] libbeat/common/schema/mapstriface
  - [x] libbeat/common/streambuf elastic/beats#15945
  - [x] libbeat/common/transport/tlscommon (https://github.com/elastic/beats/pull/16761)
  - [ ] libbeat/dashboards
  - [x] libbeat/keystore elastic/beats#15946
  - [ ] libbeat/kibana #18258
  - [ ] libbeat/metric/system
    - [ ] memory #18500
    - [ ] process #18500
  - [x] libbeat/mock https://github.com/elastic/beats/pull/18552
  - [x] libbeat/monitoring/ (https://github.com/elastic/beats/pull/16761)
    - [x] adapter
    - [x] report/elasticsearch
  - [x] libbeat/outputs (https://github.com/elastic/beats/pull/16761)
    - [x] libbeat/outputs/console
    - [x] libbeat/outputs/elasticsearch
    - [x] libbeat/outputs/fileout
    - [x] libbeat/outputs/kafka
    - [x] libbeat/outputs/logstash
    - [x] libbeat/outputs/outil
    - [x] libbeat/outputs/redis
    - [x] libbeat/outputs/transport
  - [x] libbeat/plugin https://github.com/elastic/beats/pull/18552
  - [ ] libbeat/processors/
    - [x] actions elastic/beats#16654
    - [x] add_cloud_metadata elastic/beats#16654
    - [x] add_host_metadata elastic/beats#16654
    - [x] add_docker_metadata #16003   
    - [x] add_kubernetes_metadata elastic/beats#16003 
    - [x] add_locale#16654
    - [x] add_observer_metadata elastic/beats#16654
    - [ ] script/javascript/module/console
  - [ ] libbeat/publisher/ https://github.com/elastic/beats/pull/16886
    - [x] pipeline
    - [x] pipeline/stress
    - [x] processing
    - [ ] queue/queuetest
  - [x] libbeat/reader https://github.com/elastic/beats/pull/16886
    - [x] multiline
    - [x] readfile
    - [x] readjson
  - [x] libbeat/service #17028
  - [ ] libbeat/template #18258
  - [ ] libbeat/tests/compose

**Comment by jlind23** [comment]
Closing for now as all tasks listed were achieved.
