### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by kvch** [elastic/beats#15868]
Go modules is going to be the dependency management system from Go 1.14. To enable a seamless update from the current `.go-version` (1.13.x), we should adopt the system before 1.14 is released.

## TODO

- [x] add minimal version requirements #15688 
- [x] generate `NOTICE.txt` from `modules.txt` #15688 
- [x] add tools (goimports, mage) and install it from vendor folder elastic/beats#15998
- [x] add dependencies with non v1 major versions elastic/beats#16100
- [x] find version information for dependencies which does not have any https://github.com/elastic/beats/issues/15868#issuecomment-582457979
- [x] add C files to `vendor` (e.g. `go-daemon`, `godror`) #16127 
- [x] use our for of `go-plugins-helpers` #16191
- [x] follow-up changes in the CIs (`Jenkinsfile`, `.travis.yml`) #16216
- [x] migrate beat generators to go modules #16288
- [x] include major version in import path in beats #16331
- [x] build from local vendor folder #16127 #16236
- [x] build beats inside `$GOPATH` #16329
- [x] build beats outside `$GOPATH` #16329
- [x] package beats inside `$GOPATH` #16329
- [x] package beats outside `$GOPATH` #16329
- [x] pass on all automated tests
- [x] knowledge share
- [x] run beats-tester

**Comment by kvch** [comment]
The following packages lack version information:
- `github.com/aerospike/aerospike-client-go/pkg/bcrypt `
- `github.com/klauspost/compress/snappy `
- `github.com/klauspost/compress/zstd/internal/xxhash `
- `github.com/vmware/govmomi/vim25/xml `
- `google.golang.org/api/internal/third_party/uritemplates `
- `gopkg.in/mgo.v2/bson `
- `gopkg.in/mgo.v2/internal/json `
- `honnef.co/go/tools/lint `
- `honnef.co/go/tools/ssa `

All of the packages contain a LICENSE file which is included in our `NOTICE.txt`. The version information is present implicitly in the file. As all packages are part of a module, their versions are the same as the module they are part of.
