### ISSUE TITLE
Add support for nanosecond timestamps

### ISSUE THREAD

**Issue by urso** [elastic/beats#15871]
The `@timestamp` field only has microsecond precisions. Internally, or when collecting from external sources, timestamps might have higher precisions. Elasticsearch supports the `date_nano` type, and allows to store timestamps with higher precision even if `date` is used.

The `feature-timestamp-nano` branch is used for development.
In progress PR merging the feature branch into master: https://github.com/elastic/beats/pull/15872

- [x] Support for parsing timestamp with different permissions. #9818     
- [x] Update dtfmt to support higher precision. #9818
  - [x] Add `n` formatter to always print nanoseconds. #9818     
  - [x] Allow `S` formatter to be used for higher precisions. #9818     
  - [x] Add `f` formatter. elastic/beats#15911 
- [x] Update unit tests. elastic/beats#9818 
- [x] Update integration tests. elastic/beats#16005 
- [x] Update system tests. #16005,
- [ ] Check timestamp parsing in individual beats/modules/inputs:
  - Can the input/module parse the timestamp with higher precision than is currently the case?
  - [ ] Metricbeat modules
  - [ ] Filebeat inputs
  - [ ] Filebeat modules
  - [ ] Heartbeat monitors
  - [ ] Auditbeat modules
  - [ ] Packetbeat
- [ ] Check whether we can change the template in a backwards compatible way.
  - Do we need to use `date_nano`, or can keep `date` for timestamps?
- [ ] Check Kibana works correctly with nano types (according to https://github.com/elastic/kibana/issues/31424 it works but we would need to do some testing):
  - [ ] do visualizations work without updates?
  - [ ] do visualizations/dashboards work when mixing data from indices with millisecond and microsecond precision.

Other related issues:
- [ ] Support log4j format for timestamps (comma-milliseconds) #17794
- [ ] filebeat docker-json timestamp support nanoseconds? #17660

**Comment by LotoQ** [comment]
Hi guys, was just wondering if there was a planned release date for this feature? I was just noticing that it looked like most of the tasks were complete, so really looking forward to being able to use it soon! :^)

**Comment by pytimer** [comment]
> filebeat docker-json timestamp support nanoseconds? #17660

Like issue #17660, libbeat docker-json reader not support nanoseconds, it maybe occur some problem, because i have a container and this container logs like below, i have no way to sort by the correct `@timestamp`.

```json
{"log": "Starting web...", "stream":"stderr", "time":"2020-06-15T05:26:22.521012484Z"}
{"log": "Starting web middleware...", "stream":"stderr", "time":"2020-06-15T05:26:22.521012490Z"}
```

**Comment by pytimer** [comment]
> > filebeat docker-json timestamp support nanoseconds? #17660
> 
> Like issue #17660, libbeat docker-json reader not support nanoseconds, it maybe occur some problem, because i have a container and this container logs like below, i have no way to sort by the correct `@timestamp`. So filebeat support nanoseconds is necessary for me.
> 
> ```json
> {"log": "Starting web...", "stream":"stderr", "time":"2020-06-15T05:26:22.521012484Z"}
> {"log": "Starting web middleware...", "stream":"stderr", "time":"2020-06-15T05:26:22.521012490Z"}
> ```

I read the source code about [docker_json.go](https://github.com/elastic/beats/blame/feature-timestamp-nano/libbeat/reader/readjson/docker_json.go#L108), i found parse docker log via `time.RFC3339`, it can parse `2020-06-15T05:26:22.521012484Z` to `2020-06-15 05:26:22.521012484 +0000 UTC` . I also test `time.Parse()` it return nanoseconds, so i think docker-json reader can support nanoseconds. If something wrong, please point out.

**Comment by jlind23** [comment]
8.3 goal - understand where we are at and take a decision based on it.

**Comment by jlind23** [comment]
@kvch as you will be working on the analysis of that one, could you please provide us as an outcome:
- The estimated time left to merge this PR into master https://github.com/elastic/beats/pull/15872 (It seems to be the only PR left)
- The list of inputs on which there is still work to do.

cc @ph @cmacknz in case you see something else to add

**Comment by kvch** [comment]
I have opened a new PR https://github.com/elastic/beats/pull/31553 in favour of the old one (https://github.com/elastic/beats/pull/15872). At the moment it is a draft because the tests are still failing.

I tested a few modules in Filebeat and Metricbeat manually. Pipelines and visualizations seem to work. I am confident once the tests pass on the CI we could get this in a few days. However, I would like to ask for additional manual testing from either QA source or others on our team.

**Comment by jlind23** [comment]
@dikshachauhan-qasource could you please consider it for the 8.3 testing scope?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 @kvch 
As per our understanding we have validated this by installing Metricbeat with System module enabled on latest 8.3 Snapshot Kibana cloud environment.
Further, we have observed the data from Metricbeat under Discover tab.
- Currently data is available with `@timestamp: 10:09:03.365Z`

**Screenshots:**
![6](https://user-images.githubusercontent.com/77374876/167828414-c7474fe3-bcfc-4d33-a50c-874e3f6beec9.JPG)
![7](https://user-images.githubusercontent.com/77374876/167828431-d24e565b-6519-4a3e-8bc6-81a8066e67b8.JPG)

## Queries:
Could you please confirm:
- If these changes are just for Beats and no impact on Elastic-Agent logs.
- Validation requires to be covered only Discover tab.

Please let us know if we are missing any other scenario to be covered.
Thanks

**Comment by amolnater-qasource** [comment]
Hi @kvch 
Thanks for looking into this, we haven't validated this upon feature branch. We attempted to test current behaviour of `@timestamp` on cloud-staging kibana for metricbeat and wanted to confirm if this is the testing area.

Further we had few queries related to this feature which we have shared under https://github.com/elastic/beats/issues/15871#issuecomment-1123554253
We will be retesting this once the related PR will be merged.

Thanks

**Comment by amolnater-qasource** [comment]
Hi @kvch 
We have attempted to validate this on 8.3 Snapshot Kibana cloud environment and followed below steps:
1. Setup Kibana cloud environment.
2. Installed Metricbeat with system module enabled and Auditbeat.
3. Observed data with `@timestamp` under Discover tab.
![7](https://user-images.githubusercontent.com/77374876/170036610-bdc88c43-6396-4d4b-a557-082dd1def9da.JPG)
4. We observed that data is still available with timestamp: `@ 17:22:57.955`

**Build details:**
BUILD: 52935
COMMIT: 5d5603a57237d8fe9cf186916c713b9ddddf039d
(MAY 19, 2022 3:42 PM)


### Question

**Could you please share some more testing details or could confirm if we are missing anything here?**

cc: @jlind23 
Thanks

**Comment by amolnater-qasource** [comment]
Hi @kvch @joshdover 
Thanks for the feedback.
We have revalidated this on latest 8.3 Snapshot kibana cloud environment and followed below steps:
- We have added `timestamp.precision: nanosecond` under metricbeat-reference.yml and winlogbeat-reference.yml.
- We then observed the data under Discover>JSON tab of the "Expanded document" flyout.
- We observed nanosecond data under `_source: @timestamp`.

**OS& Beats covered:**
Platform: Windows 10 x64
Winlogbeat
Metricbeat

**Screenshots:**
![2](https://user-images.githubusercontent.com/77374876/170485428-472e8a48-01f9-4013-b9c4-a21edfd34d52.JPG)
![3](https://user-images.githubusercontent.com/77374876/170485438-cf45b10f-545c-4267-a6ac-42f4c182e759.JPG)

### Question:

**Please let us know if we need to validate this on any other beats or platforms.**

Thanks

**Comment by axw** [comment]
There are still some open issues regarding `date_nanos` in Kibana. Shouldn't we wait for them to be addressed before switching field types?

 - https://github.com/elastic/kibana/issues/88290
 - https://github.com/elastic/kibana/issues/40183

**Comment by kvch** [comment]
I agree with @axw. Also, the default `@timestamp` granularity is still milliseconds, so we do not have to hurry with the change.
Also, all of the vizualizations work with the current template even if the timestamp precision is set to nanoseconds.
