### ISSUE TITLE
[Meta] Add haveibeenpwned module

### ISSUE THREAD

**Issue by philippkahr** [elastic/beats#16300]
# Filebeat Module / Dataset release checklist

Why:
* Improving the SIEM context.
Usually, everyone is already collecting the Windows Event Logs for security, or Linux audit logs, or any other logs that contain usernames. Why not map the list of breached usernames to that list? Creating an easy report over "how many of my users have been breached and which service?" is something that will add more context to security incidents. Especially when searching for brute-force attacks on public authentication realms (e.g. we are seeing a lot of authentication requests against Azure AD using IMAP, with various users). 
Additionally, by pulling that data frequently, a diff can be done on a daily basis. 
Furthermore, if a breach is announced the SIEM rules could be rerun with the added data.

[API Reference guide](https://haveibeenpwned.com/API/v3)

<details><summary>Checklist </summary>
<p>
This checklist is intended for Devs which create or update a module to make sure modules are consistent.

## Modules

For a metricset to go GA, the following criterias should be met:

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] Integration tests exist
* [ ] System tests exist
* [ ] Automated checks that all fields are documented
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials).

## Filebeat module

* [ ] Test log files exist for the grok patterns
* [ ] Generated output for at least 1 log file exists

## Metricbeat module

* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Test environment in Docker exist for integration tests
</p>
</details>
