### ISSUE TITLE
Beats use of non-ECS field `agent.hostname` causing user confusion

### ISSUE THREAD

**Issue by MikePaquette** [elastic/beats#16377]
During the introduction of ECS-support with the 7.0 release, some breaking changes were made in certain fields populated by beats.

Specifically, a new field `agent.hostname` was introduced - however this field is not an ECS field, and it's continued use and documentation are creating user confusion.

A recent SIEM discuss topic highlights the issue: [219088](https://discuss.elastic.co/t/hosts-table-host-name-alias-of-beat-name-used-instead-of-agent-hostname/219088) 

**Assumptions:**

- All module dashboards, apps, and other ECS data consumers should use the ECS field `host.name` to display general information about the host object.  
- In special cases, such as DNS, where the visualization is specifically looking for the hostname field, `host.hostname` may be used.
- All beats that operate locally on a host should be populating `host.name` and `host.hostname` in their default configurations, either by enabling add_host_metadata, or some other means.
- Beats that operate remotely, such as heartbeat, should be populating `observer.hostname` 

**Recommended changes:**

- [ ] Remove mention of `agent.hostname` from the [beats docs](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-beat-common.html) and replace it with `host.name` and optionally `host.hostname`.
- [ ] Change target of alias `beat.hostname` from `agent.hostname` to `host.hostname` in https://github.com/elastic/beats/blob/master/libbeat/_meta/fields.common.yml
- [ ] Consider marking `agent.hostname` as deprecated and stop populating it in 8.0
- [ ] Consider adding a new alias from `agent.hostname` to `host.hostname` once it is no longer populated, to enable any analysis content that used the `agent.hostname` field to continue to operate

**Comment by jsoriano** [comment]
Should `observer.hostname` be used too for the hostname of beats that forward data from other hosts? (https://github.com/elastic/beats/issues/13920)

**Comment by MikePaquette** [comment]
@jsoriano Yes.  (I tried to capture that in the 4th assumption bullet above).

**Comment by MikePaquette** [comment]
There is a related behavior that is also causing problems for the user who posted in discuss [219088](https://discuss.elastic.co/t/hosts-table-host-name-alias-of-beat-name-used-instead-of-agent-hostname/219088).

It appears that when the user sets the `name:` in the beats .yml file,  that value not only gets populated to `agent.name` (expected), but also gets populated in `host.name` (not expected).

For example, this setting (happens to be in auditbeat.yml):
![image](https://user-images.githubusercontent.com/22619280/74834950-6fd0c800-52ea-11ea-844f-7b86602d52f4.png)

Results in this document being indexed in auditbeat-7.6.0-*:
![image](https://user-images.githubusercontent.com/22619280/74835224-e1a91180-52ea-11ea-8ae3-0c3fe95ce8bf.png)

In addition, there is an existing alias in https://github.com/elastic/beats/blob/master/libbeat/_meta/fields.common.yml that likewise seems to map the legacy `beat.name` to `host.name`.  I think this should be mapped to `agent.name`.

![image](https://user-images.githubusercontent.com/22619280/74835509-81ff3600-52eb-11ea-9e4d-a0ea00b37726.png)

**Comment by andrewkroh** [comment]
We want to ensure that we continue to have an identifying name for the agent in events when we remove `agent.hostname`. So in https://github.com/elastic/beats/pull/18000 I have modified the code to set `agent.name` to the hostname by default. It can be overwritten with a custom identifer by setting `name` in the config. This change will be merged in to 7.x too.

Then for master (8.0) I will remove the `agent.hostname`.

**Comment by andrewkroh** [comment]
I have open the PR to remove `agent.hostname` for 8.0. See #18328.
