### ISSUE TITLE
Implement new naming structure for Metricbeat

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#1639]
To bring Metricbeat field names in line with other beats and make the naming more user friendly, the following changes are required:

* [x] Rename `moduleName-metricSetName` to `moduleName.metricSetName`. metricSetName will be a sub document https://github.com/elastic/beats/pull/1638
* [x] Introduce new naming standard for all fields
* [x] Update documentation with all above changes

Related PR's to simplify migration:
* https://github.com/elastic/beats/pull/1636

**Comment by ruflin** [comment]
Closing as all changes were implemented.
