### ISSUE TITLE
[Agent] [Meta] Support for constraints

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#16415]
Effort for constraints support is split into few steps:

- [ ] Initial support for constraints elastic/beats#16409 also a `POC`
- [ ] Support for sets in constraints elastic/beats#16410
- [ ] Support for maps in constraints elastic/beats#16411
- [ ] Support for HAS operator in constraints elastic/beats#16412
- [ ] Support for top level constraint elastic/beats#16413

**Comment by ph** [comment]
I think we have enough initial work with https://github.com/elastic/beats/issues/16409, I will close this issue we can revisit later if we need to do more work on constraints.
