### ISSUE TITLE
[Meta] Cloud Foundry Support

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#16520]
## Overview

Cloud Foundry loggregator provides a gRPC stream to receive a combined logs and metrics about the applications running inside of Cloud Foundry. Loggregator provides selectors on connection to gRPC to split up the logs vs metrics.

Filebeat and metricbeat can use the gRPC stream with selectors to split up the events to process the appropriate events respectively as inputs to send to elasticsearch.

## Libbeat work to complete

* [X] Add common loggregator connection to share between metricbeat and filebeat.
* [X] Add common `add_cloudfoundry_metadata` to add application metadata to events shared between metricbeat and filebeat.
* [x] Add support for V1 #19125 #19268
* [ ] Add integration tests https://github.com/elastic/beats/issues/17539
* [x] Throttling per organization https://github.com/elastic/beats/issues/21020

## Filebeat work to complete

* [X] Add `cloudfoundry` input to filebeat.
* [X] Add documentation for `cloudfoundry` input.
* ~~Test log files exist for the grok patterns~~ (Logs come from gRPC protocol buffer events)
* ~~Generated output for at least 1 log file exists~~
* [x] Add a cloudfoundry module

## Metricbeat work to complete

* [X] Add `cloudfoundry` module.
* [X] Add documentation for `cloudfoundry` module.
* [X] Example `data.json` exists ~~and an automated way to generate it exists (`go test -data`)~~ (Currently no way to autogenerate)
* ~~Test environment in Docker exist for integration tests~~ (Cannot run Cloud Foundry in Docker)
* [ ] Test environment based on kind and kubecf
* [ ] Add a metricset with metrics grouped https://github.com/elastic/beats/issues/21532
* [x] Some metrics are received twice in the same timestamp, but with different values, confirm if they have different tags

## Usage work to complete

* [X] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [X] Add documentation on how to run filebeat and metricbeat for Cloud Foundry.
  * [x] Extend documentation to cover use cases with persistent cache. https://github.com/elastic/beats/issues/21560
* [x] Add dashboard for Kibana. #20798

**Comment by exekias** [comment]
cc @andresrc @mukeshelastic

**Comment by kate-jq** [comment]
When will the dashboards be ready?

**Comment by masci** [comment]
Closing as we only have #17539 and #21532 left that will be scheduled later.
