### ISSUE TITLE
Kerberos support for Beats

### ISSUE THREAD

**Issue by kvch** [elastic/beats#16565]
In #15619 we decided to use `github.com/jcmturner/gokrb5` to support Kerberos in Beats. The goal of this effort is to add support for the following:

- [x] Kerberos authentication for Elasticsearch #7404
    - [x] Elasticsearch output
    - [x] Add end to end tests #18127 
    - [x] Update documentation of ES output
- [ ] Kerberos authentication for Kafka #5413
   - [x] Kafka input #16871
   - [x] Kafka output #16871
   - [ ] Add end to end tests #16904
   - [x] Update documentation of Kafka output
   - [x] Update documentation of Kafka input

**Comment by fbaligand** [comment]
Great new feature!
I'm very interested, particularly for Kafka authentication!

**Comment by jlind23** [comment]
Closing it in favour of #5413 which is the only task left.
