### ISSUE TITLE
Complete support for  SCRAM-SHA-256/512 in Kafka output

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#16723]
Initial support for SCRAM-SHA-256 and SCRAM-SHA-512 was introduced in https://github.com/elastic/beats/pull/12867

There are some follow ups that would need to be done before considering this feature ready:

- [x] Add changelog entry #23103.
- [x] Add documentation for the new `mechanism` option #23103.
- [ ] Add automatic tests (we could try to add a listener in current docker compose service with this authentication method). Moved to https://github.com/elastic/beats/issues/23112.

After that:

- Backport to 7.x
- Consider reusing the code for other kafka features (kafka input, metricbeat module)

**Comment by jsoriano** [comment]
Docs and changelog added, some manual test done and backport to 7.x ready, closing this.

Leaving https://github.com/elastic/beats/issues/23112 as follow up for integration tests.
