### ISSUE TITLE
Add support for Kubernetes Windows nodes (or containers in Windows in general)

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#16814]
Docker can be run natively on Windows and this way it can run native containers, this allows to have Windows nodes in Kubernetes clusters running native Windows applications.
GKE allows to create Kubernetes clusters with Windows nodes (see [this blog post](https://cloud.google.com/blog/products/containers-kubernetes/how-to-deploy-a-windows-container-on-google-kubernetes-engine)).

Running Beats as proposed now in Kubernetes guides is not possible there because this requires to run Beats as containers, but so far Beats containers are only created for Linux.

A possible workaround now is to run Beats directly on the hosts, but this makes a complete different experience to the one with usual Linux-based clusters.

Some things that could be done to support this use case:
- [ ] Distribute Beats as Windows containers too
- [ ] Update documentation and reference manifests to use these images if needed (maybe different OSs can have images with the same name)
- [ ] Improve testing of Docker and Kubernetes features on Windows
- [ ] Support deployment of beats using daemonsets in mixed clusters (with Linux and Windows nodes)

Related issues:
* [Question on discuss about this](https://discuss.elastic.co/t/windows-containers-logging/221997)

**Comment by junneyang** [comment]
+1

**Comment by cwarnke** [comment]
I'd really like to see this. 
"Support deployment of beats using daemonsets in mixed clusters (with Linux and Windows nodes)"

**Comment by joproulx** [comment]
We did our own docker images for metricbeat for Windows Nano Server and some of the modules do work. 

**Kubernetes** module seems to work ok. The **System** module on the other hand doesn't work. So I cannot get CPU for the Host (Node) from metricbeat on a Windows Node. 

If I understand correctly on Linux, we map the Host filesystem on the container and therefore metricbeat can read system metrics ([reference](https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html#monitoring-host)).

Any idea how we can support this on Windows? Is there any plan on supporting this?

**Comment by akshay-saraswat** [comment]
Thanks for the ping and reminder @joproulx! We definitely want to support this but "when?" would be answered after we have prioritized it against all the other tasks we plan to work on. Since this issue involves participation from multiple teams at Elastic, it's difficult to provide a concrete timeline right now. We will keep you posted as we make progress.

**Comment by derbl4ck** [comment]
Hey @akshay-saraswat ,
I also maintain several Kubernetes clusters with Windows nodes and would benefit from this feature.

Is there already a roadmap for this feature?

Best regards

**Comment by mloskot** [comment]
Please, don't drop it 👍

**Comment by PatrickSpies** [comment]
👍

**Comment by derbl4ck** [comment]
👍

**Comment by PatrickSpies** [comment]
👍

**Comment by helbros86** [comment]
:+1

**Comment by OldScratchy** [comment]
+1

**Comment by LBoraz** [comment]
+1

**Comment by chandrashekharpatil1** [comment]
+1

**Comment by EvelienSchellekens** [comment]
+1

**Comment by scholtz** [comment]
+1

**Comment by amoradiaz** [comment]
+1

**Comment by DanielBrown2023** [comment]
+1
