### ISSUE TITLE
Add support for Nomad

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#16853]
[Nomad](https://nomadproject.io/) is an orchestrator for heterogeneous workloads maintained by [Hashicorp](https://www.hashicorp.com/).

This issue keeps track of efforts to support Nomad in Beats.

Nomad support could follow a similar approach to the available support for Kubernetes, for that the following components should be implemented:
- [ ] `nomad` autodiscover provider.
- [ ] `add_nomad_metadata` processor.
- [ ] `nomad` metricbeat module.

The code for these features should be placed under `x-pack` (licensed as Basic).

At the moment of creating this issue there are some open community PRs that provide some of the required components, we have to review and continue with them:
* #14500 - Adds an `add_nomad_metadata` processor.
* #14954 - Adds an `add_nomad_metadata` processor too, and a `nomad` autodiscover provider.

There are also some known issues regarding Nomad support (though they can be general issues):
* #12988 - Filebeat fails to collect logs from containers started by nomad
* #12178 - Problems reaching non-published ports with Docker autodiscover

// cc: @jorgelbg and @jorgemarey as authors of current open PRs

**Comment by jsoriano** [comment]
Hey @jorgelbg and @jorgemarey,

I have been taking a look to your pull requests and the truth is that both look great, I would love to see Nomad support in Beats. Thanks both for your efforts!

Both PRs contain an `add_nomad_metadata` processor, and they both work pretty well, but #14954 is more complete, it has support for indexers and matchers, what I think will help to support more Beats and nomad runtimes in the future, and it also includes an autodiscover provider. So I think that it'd be better to go on with this PR only.
In any case, @jorgemarey, if you have some time, it'd be great if you could also take a look to #14954, I am sure you can give some ideas there! For example I like that your processor in #14500 automatically gets the node ID of the local agent.

Thanks again!

**Comment by jsoriano** [comment]
Initial support merged, what includes an autodiscover provider and an `add_nomad_metadata` processor. It will be released in principle as experimental feature in 7.12.

**Comment by JakeCover** [comment]
Thank you! Really looking forward to this being fully released.

**Comment by joaquinjsb** [comment]
👍🏼

**Comment by matya** [comment]
The hope dies last 😅
