### ISSUE TITLE
Backlog of content that needs an edit

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#17163]
This content was merged without writer review and requires an edit.

- [ ] Edit section about [schedule](https://www.elastic.co/guide/en/beats/heartbeat/master/monitor-options.html#monitor-schedule) option in the Heartbeat docs (added in https://github.com/elastic/beats/pull/14891)
- [ ] Edit topic about the [copy_fields processor](https://www.elastic.co/guide/en/beats/filebeat/master/copy-fields.html) (added in https://github.com/elastic/beats/pull/14423)
- [ ] Edit section about [indexers and matchers](https://www.elastic.co/guide/en/beats/filebeat/master/add-kubernetes-metadata.html#kubernetes-indexers-and-matchers) in the add_kubernetes_metadata docs (added in https://github.com/elastic/beats/pull/17139)
- [ ] Edit topic about [replace processor](https://github.com/elastic/beats/blob/master/libbeat/processors/actions/docs/replace.asciidoc) and add it to the [processors-list](https://github.com/elastic/beats/blob/master/libbeat/docs/processors-list.asciidoc) to get it building. (added in https://github.com/elastic/beats/pull/17342)
- [ ] Edit topic about [decode_json_fields](https://www.elastic.co/guide/en/beats/filebeat/master/decode-json-fields.html) processor (see related issue: https://github.com/elastic/beats/issues/18400).

**Comment by dedemorton** [comment]
Removed the following issues from the list of items to edit:

- [x] https://github.com/elastic/beats/pull/16731 - content will be edited when moved to the agent settings docs
- [x] https://github.com/elastic/beats/pull/18748 -  content was edited in the agent settings docs

**Comment by leahleahy** [comment]
Hi, I can take this!

**Comment by dedemorton** [comment]
Closing because this issue is old and no longer relevant.
