### ISSUE TITLE
[Auditbeat][Meta] System/socket dataset improvements

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#17444]
**Describe the enhancement:**

This issue is created to track all the improvements that we would like to see in the`system/socket` dataset since it was renewed in 7.4.0.

- [ ] New dashboard (#17346): The current dashboards are not updated for the new flow-based information that the dataset provides.
- [ ] Make process enrichment more reliable (#17165). Some parts of the tcp/ip stack can be run in the context of a process other than the one generating the traffic, causing a flow to be attributed to the wrong process. We can either investigate is some particular kprobes are a more reliable source of origin PID, or find a better method to assign a PID to a flow other than last-seen.

Less priority:
- [ ] kprobe-based DNS enrichment, currently uses af_packet capture with a port 53 UDP filter.
