### ISSUE TITLE
Enhance Elasticsearch Filebeat module to handle ECS-compatible logs

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#17715]
With https://github.com/elastic/elasticsearch/pull/47105 merged, starting 8.0.0, Elasticsearch will emit ECS-compatible logs. The `elasticsearch` Filebeat module must be enhanced to handle such logs, while also keeping it backwards-compatible to handle `7.x`-style logs.

Filesets to update:
- [x] `server`: elastic/beats#17714
- [x] `deprecation`: elastic/beats#17728
- [x] `slowlog`: elastic/beats#17729

**Comment by ycombinator** [comment]
FYI: @pgomulka

**Comment by pgomulka** [comment]
totally forgot about beats testcases. thank you for looking into this @ycombinator !

**Comment by ycombinator** [comment]
Resolved via #17714, #17728, and #17729.
