### ISSUE TITLE
[Ingest Management] Allow checkin to be controlled by the remote server

### ISSUE THREAD

**Issue by ph** [elastic/beats#18623]
By default the checkin frequency of the Agent is 30s, this values is configurable locally by it should also be configurable remotely on the kibana side.

## Task:
- [ ] Modify the UI to configure that frequency.
- [ ] Allow the fleet gateway to be reloadable on change.
- [ ] Allow the local configuration to come from fleet.
