### ISSUE TITLE
Review, edit, and publish ingest management docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#19036]
This is a meta issue for tracking:

- ingest management docs that require writer review or edit
- other writer tasks to support the documentation effort

**Reviews required by writer:**
- [x] Review/edit "Basic Elastic Agent documentation" https://github.com/elastic/beats/pull/19030
- [x] Review/edit "Fleet configuration flags" https://github.com/elastic/kibana/pull/66736
- [x] Review "Ingest Management Guide" https://github.com/elastic/stack-docs/pull/1126
- [x] Approve Ingest Manager topic https://github.com/elastic/kibana/pull/68785
- [x] Light review of Ingest management overview (will do full edit in a separate PR) https://github.com/elastic/stack-docs/pull/1144
- [x] Light review of troubleshooting topic https://github.com/elastic/stack-docs/pull/1148

**Writer PRs waiting for review:**
- [x] Ingest Manager edits https://github.com/elastic/kibana/pull/68824
- [x] Add shared attributes https://github.com/elastic/docs/pull/1867
- [x] Get ingest management docs ready for publishing https://github.com/elastic/stack-docs/pull/1147
- [x] Get ingest management docs building https://github.com/elastic/docs/pull/1864
- [x] Edit Elastic Agent docs https://github.com/elastic/beats/pull/19146
- [x]  Edit Ingest Manager topic in Kibana https://github.com/elastic/kibana/pull/68980
- [x] Edit troubleshooting topic https://github.com/elastic/stack-docs/pull/1160
- [x] Get agent docs building https://github.com/elastic/stack-docs/pull/1163
- [x] Edit the overview https://github.com/elastic/stack-docs/pull/1168
- [x] Edit getting started guide https://github.com/elastic/stack-docs/pull/1175
- [x] Fix problems in ingest management docs found during testing https://github.com/elastic/stack-docs/pull/1194
- [x] Fix problems in Elastic Agent docs found during testing https://github.com/elastic/beats/pull/19252

**Other tasks:**
- [x] Turn on attribute resolution for example described here: https://github.com/elastic/stack-docs/pull/1192
- [x] Add x-pack role to all Elastic Agent docs.
- [x] Global change: use "the Agent" (uppercase) instead of "the agent" (lowercase).
- [x] Point to Ingest Management guide from https://www.elastic.co/guide/en/kibana/7.8/ingest-manager-settings-kb.html
- [x] Fix typo in troubleshooting: https://github.com/elastic/beats/issuess
- [x] Fix this (from Sonja): the Kibana server must be able to connect to http://epr-experimental.elastic.co on port 80. (in the troubleshooting section) should be https and port 443
- [x] Fix issues identified by Jason:
  - [x] Link the limitations of this release to the top of the getting started guide?
  - [x] Move the fleet instructions above standalone on the getting started guide? I'd like to encourage people to use Fleet, and flows nicely from the section above on setting up integrations.
- [x] Make sure content about Ingest Manager from closed PR is covered in the docs https://github.com/elastic/beats/pull/19136/
- [x] Edit troubleshooting topic
- [x] Edit the overview and uncomment it.
- [x] Edit Ingest Manager topic (added by https://github.com/elastic/kibana/pull/68785) - rename file, get it hooked up to the navigation, etc
- [x] Edit "Ingest Management Guide" (added by https://github.com/elastic/stack-docs/pull/1126)
  - [x Fix linking in the Ingest Management Guide and make the task flow clearer.
- [x] Hook up all ingest management topics and adjust the topic hierarchy, as required.
- [x] Fix asciidoc coding in the Ingest Management Guide.
- [x] Fix table formatting in https://github.com/elastic/kibana/pull/66736.
- [x] Add ingest management docs to the doc build. (draft) https://github.com/elastic/docs/pull/1864
- [x] Add shared attributes for ingest management. https://github.com/elastic/docs/pull/1862
- [x] Finalize terminology and possibly remove "Elastic Package Manager".
- [x] Change heading levels to use level offsets (control the TOC hierarchy from the index file).
- [x] Clean up all source files to use asiidoc attributes for product and feature names.

**Testing**
- [x] Test all the procedures.
  - [x] Getting started [DeDe][Brandon]
  - [x] Beats agent docs [DeDe]
  - [x] Troubleshooting
- [x] Global checks and fixes:
  - [x] Make sure xpack role is correctly assigned.
  - [x] Make sure "experimental" label is applied
  - [x] Clean up file structure:
    - [x] Make sure every topic has an explicit anchor name and fix potential SEO issues with naming.
    - [x] Make sure each HTML file maps to a single asciidoc source file and refactor, as needed.

**Docs that are published and ready for alpha:**
- Ingest management Guide:
  - [x] Overview
  - [x] Getting started with ingest management
  - [x] Agent docs
  - [x] Troubleshooting
- Kibana Guide:
  - [x] Ingest Manager settings
  - [x] Ingest Manager stub

**Remaining work (after 7.8 docs are merged):**
- [x] In getting started, reword the steps that tells users that the required settings are enabled. https://github.com/elastic/stack-docs/pull/1197
- [x] Update the discuss forum link to: https://discuss.elastic.co/tags/c/elastic-stack/81/stack-ingest-management
- [x] Add widget code and single source commands. Opened [draft PR](https://github.com/elastic/stack-docs/pull/1217), but we won't merge until we get the final design for the widgets in place. 
- [x] Remove reviewer notes and cleanup todo comments.
- [x] Remove release state overrides.
- [x] Document configuration setting details or provide full example file (currently commented out because the info was outdated). We will add documentation about config settings in 7.9.
- [x] Some flags are missing from the CLI docs. Is that intentional? (see https://github.com/elastic/observability-dev/issues/922#issuecomment-645469486). Yes. We will document remaining flags in 7.9.
- [x] Open issue to edit Ingest Manager text strings.
- [x] Figure out what to do with the dev docs under x-pack/plugins/ingest_manager/dev_docs/ in Kibana. Not sure whether they can stay there.
- [x] Follow up on terminology decision to capitalize Agent when used alone. I think it's awkward and isn't consistent other guidelines. Created issue #176 in the style-guide repo.

Related meta issue:
https://github.com/elastic/integrations-dev/issues/11

**Comment by dedemorton** [comment]
Closing this out for the alpha. I'll create issues to track any future cleanup work that we need to do in 7.9.
