### ISSUE TITLE
Elasticsearch Metricbeat module: performance improvements

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#19040]
Tracking various memory and performance optimizations we should consider for the Elasticsearch Metricbeat module:

* [x] Reduce memory usage in `index` metricset: https://github.com/elastic/beats/issues/16503
* [ ] Consider caching the cluster state API response: https://github.com/elastic/beats/issues/18997
* [ ] Consider using a `struct` instead of `map[string]interface{}` to store cluster state: https://github.com/elastic/beats/issues/18998
* [ ] Consider applying `index` metricset optimizations to the `cluster_stats` metricset: https://github.com/elastic/beats/issues/18999
