### ISSUE TITLE
Filebeat Cleanup

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#1913]
This issue is intended as meta issue to track several filebeat cleanups
# Harvester separation

Log and stdin harvester should be separated and made independent potentially with separate readers.
- [x] Remove Continuable() interface as readers are separated (will no happen as not needed at the moment)
# Harvester
- [x] Unify error message and make them more consistent. For example `err_inactive`.
- [ ] Use `common.Backoff` in file harvester.
- [x] Improve handling of encoding https://github.com/elastic/beats/pull/1975#discussion_r70256218
- [x] Merge shared variables between harvester and state (path/Source, offset) https://github.com/elastic/beats/pull/2020
# Prospectors
- [x] Prospectors must be able to send state updates to the registrar directly (no need to initialised harvester) https://github.com/elastic/beats/pull/1978
- [x] `startHarvester` returns an error which is not checked by all implementations #2240
# Testing
- [x] Clean up inconsistent variable naming in `filebeat.yml.j2`. All should be with _ and not cameCase. https://github.com/elastic/beats/pull/1975
# General
- [x] Introduce expvar to track open files https://github.com/elastic/beats/pull/2020
- [x] Add additional expvar to track states
# Docs
- [x] Write "How Filebeat works" documentation guide. Explain crawler, prospector, harvestor https://github.com/elastic/beats/pull/1963

**Comment by urso** [comment]
Use `common.Backoff` in file harvester.

**Comment by ruflin** [comment]
All changes implement except for `common.Backoff`. @urso I suggest if we sitll want to have a `common.Backoff` we should open a separate issue?
