### ISSUE TITLE
[Elastic Agent] Add support for dynamics inputs

### ISSUE THREAD

**Issue by ph** [elastic/beats#19225]
In beats today we have a feature called **Autodiscovery** that allows you to generate inputs based on labels or other information coming from a provider like the k8s, docker stream. We want to add the same functionality in the Elastic Agent. We are calling that new feature _Dynamic input_.

As an example, we would create a dynamic input template like this. And the system would run through the data it has to define if a template should be used or not.

```yaml
inputs:
- type: log
  dataset.type: logs
  streams:
    - paths: /var/log/${host.platform}.log
      dataset.name: foo
  condition: ${host.platform} == "windows"
```
## Use cases:

- Do an input need to run on this OS (aka syslog should not work on Windows).
- Do an input need to run based on the environment.
- Do an input need to run based on data from a provider (k8s hints)
- Allow defining a cross platform integration that will use journald on Linux but winlogbeat on Windows 

### Phase 1: Elastic Agent
- [x] Write a **proposal** for conditionals language previous discussion at https://github.com/elastic/beats/issues/20784
- [x] Allow Elastic-Agent to evaluate templates based on defined conditions. #20784
- [x] Define concepts of input templates and provider in Elastic Agent. #20781
- [x] System Provider: Allow to retrieve information about the current host. #20781

## Phase 2 (beyond 7.10)
- [ ] Debugging Tools: Add ability to debug a provider easily. #21148
- [ ] Add Keystore support in the Elastic-Agent https://github.com/elastic/beats/issues/14454
- [x] Refactor autodiscovery/docker https://github.com/elastic/beats/pull/20842
- [x] Refactor autodiscovery/kuberbetes https://github.com/elastic/beats/issues/19271

**Comment by ph** [comment]
cc @andresrc @exekias @ruflin @roncohen @urso

**Comment by exekias** [comment]
I've created https://github.com/elastic/beats/issues/19271 to discuss the changes in current autodiscover

**Comment by ph** [comment]
@ruflin @blakerouse One thing that I think our idea doesn't cover is a default case. Lets assume that an integration ships with 3 inputs.

```
- type: A
    conditions: 
      - {{os.platform}} == windows

- type: B
    conditions: 
      - {{journald_detected}} == true

- type: C
    conditions: 
      - Run only is A/B is not enabled.
```

The use case would be use the windows events, journald if it exist, otherwise fallback to file on disk? Do we need to support that kind of condition or we assume that everything is a single "unit" with only his own view on the world? The later really simplify any use case.

**Comment by ph** [comment]
Closing this, added the remaining items in the project board.
