### ISSUE TITLE
Reduce Warn verbosity, switch to Info by default

### ISSUE THREAD

**Issue by tsg** [elastic/beats#1931]
The current state is that we log at Error level by default. The historical reason is that Packetbeat could generate a lot of valid warnings (e.g. when traffic contains invalid patterns) which result in slowing it down for the rest of traffic, or filling up the disk, or rotating the logs too fast, etc.

But printing only errors by default is also not great, because:

* the user gets no feedback that the Beat correctly started
* in some cases, critical information is hidden. See #1734 for an example
* very low logging defaults means that for almost any troubleshooting we need to ask the user to increase verbosity

In general, we want to avoid warnings all together, as they are [not friendly to the ops people](http://blog.schlomo.schapiro.org/2015/04/warning-is-waste-of-my-time.html). For us, warnings (and to some extent INFO messages) are essentially debug messages that we want to have always on. The plan is to replace Warnings with expvar metrics, which can be inspected in realtime via the `-httpprof` option and for which we can also write periodic summaries to the logs.

This is a meta ticket to:

* [x] Review and reduce over-verbose warnings and infos in each beat:
  * [x] Packetbeat #1948 
  * [x] Filebeat #1970
  * [x] Metricbeat
  * [x] Winlogbeat
  * [x] libbeat #1973 
* [x] Change the default logging level from Error to Info. #1952 #2364 
* [x] Periodically log expvar counters #1955 #1969 
* [x] Rename our expvars from camelCase to dotted.case #1967
* [x] Review winlogbeat expvars, if they can use the naming convention above
* [x] Log total expvar metrics at the end in all beats, like Metricbeat currently does it. #2349

**Comment by tsg** [comment]
Compared to the other Beats, Filebeat is a bit more verbose at INFO level. For example, it prints a message on each bulk publish:

```
2016/06/29 10:50:49.536775 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:50.406032 publish.go:111: INFO Events sent: 2048
2016/06/29 10:50:50.407090 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:51.227240 publish.go:111: INFO Events sent: 2048
2016/06/29 10:50:51.228463 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:52.017300 publish.go:111: INFO Events sent: 2048
2016/06/29 10:50:52.018828 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:53.086974 publish.go:111: INFO Events sent: 2048
2016/06/29 10:50:53.096369 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:53.862119 publish.go:111: INFO Events sent: 2048
2016/06/29 10:50:53.864995 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:54.688896 publish.go:111: INFO Events sent: 2048
2016/06/29 10:50:54.690475 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:55.461237 publish.go:111: INFO Events sent: 2048
2016/06/29 10:50:55.463595 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:56.321635 publish.go:111: INFO Events sent: 2048
2016/06/29 10:50:56.322822 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:57.372060 publish.go:111: INFO Events sent: 2048
2016/06/29 10:50:57.373635 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:57.970777 prospector.go:128: INFO Run prospector
2016/06/29 10:50:58.285754 publish.go:111: INFO Events sent: 2048
2016/06/29 10:50:58.286825 registrar.go:239: INFO Registry file updated. 12 states written.
2016/06/29 10:50:59.011178 publish.go:111: INFO Events sent: 2048
```

Also it prints an Info on each prospector run, on each file open, etc.

@elastic/beats Do we generally want Beats to print stuff periodically by default to help with troubleshooting, or should we move stuff like the above to debug level? Note that a more aggresive `scan_frequency` setting (to give an example) will result in even more logs.

**Comment by ruflin** [comment]
There are definitively messages which should be moved to debug like `Run Prospector`. I somehow like the "Events sent" and "states written" in here as it shows progress, but in high load environment that could become too much. At the same time these could switch to WARN or ERR?

In general I think each beat should print some info messages at startup to say that all configs were read and startup is correct, and then during running send some status updates every few seconds so it can be seen that something happens. For the publisher, it could be interesting that every 10 seconds for example `x events sent` is logged (summary).

**Comment by tsg** [comment]
Yeah, we could replace filebeat specific Events sent with a libbeat debug statement that prints selected expvars. That would be quite nice.

**Comment by tsg** [comment]
All done, now.
