### ISSUE TITLE
[meta][filebeat] Replacing null value checks in set processors for all modules

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#19407]
This is a meta issue to track the progress of replacing null value checks in set processors to the new built-in null value check, removing a large amount of script compilations.

This is all possible now due to: https://github.com/elastic/elasticsearch/pull/57030

**Changelog**

**Module List**

OSS:

- [x] apache module - 1 processor changed - PR: #19411
- [x] auditd module - 2 processor changed - PR: #19412 
- [x] haproxy module - No processors needed update
- [x] iis module - No processors needed update
- [x] kibana module - 1 processor changed - PR: #19413
- [x] mongodb module - No processors needed update
- [x] nats module - No processors needed update
- [x] osquery module - 15 processors changed and updated test logs with removed empty values: #19414
- [x] redis module - No processors needed update
- [x] system module - 1 processor changed - PR: #19415
- [x] apache2 module - No processors needed update
- [x] elasticsearch module - 10 processors changed - PR: #19416
- [x] icinga module - No processors needed update
- [x] kafka module - No processors needed update
- [x] logstash module - No processors needed update
- [x] mysql module  - No processors needed update
- [x] nginx module  - No processors needed update
- [x] postgresql module - No processors needed update
- [x] santa module - 2 processors changed - PR: #19417
- [x] traefik module - No processors needed update

X-Pack:

- [x] checkpoint module - 20 processors changed: #19418
- [x] activemq module - 1 processor changed - PR: #19419
- [x] suricata module -  4 processors changed - PR: #19420
- [x] fortinet module - 2 processors changed - PR: #19421
- [x] rabbitmq module  - No processors needed update
- [x] aws module - 17 processors changed - PR: #19424 
- [x] panw module - 1 processor changed - PR: #19425
- [x] cef module - 4 processors changed - PR: #19426
- [x] azure module - No processors needed update
- [x] envoyproxy module - 5 processors changed - PR: #19427
- [x] o365 module - No processors needed update
- [x] misp module - No processors needed update
- [x] mssql module - No processors needed update
- [x] crowdstrike module - No processors needed update
- [x] coredns module - 6 processors changed - PR: #19428
- [x] ibmmq module - No processors needed update
- [x] okta module - No processors needed update
- [x] iptables module - 4 processors changed - PR: #19429
- [x] netflow module - No processors needed update
- [x] zeek module - No processors needed update
- [x] cisco module - 19 processors changed - PR: #19430
- [x] googlecloud module - No processors needed update

**Comment by vi-or-die** [comment]
@P1llus 
I saw CrowdStrike is in this list but showing "No processors needed update". I wanted to make a note of an issue with that module here. If the fix being made in this meta issue is completely different please let me know. 

The CrowdStrike Filebeat module appears to be throwing parse errors due to null / non-existent values in the original data. Please see the example below. 


## Original Log Format
```
{
    "metadata": {
        "customerIDString": "...redacted...",
        "offset": 22865,
        "eventType": "UserActivityAuditEvent",
        "eventCreationTime": 1593186952000,
        "version": "1.0"
    },
    "event": {
        "UserId": "Crowdstrike",
        "UserIp": "",
        "OperationName": "quarantined_file_update",
        "ServiceName": "quarantined_files",
        "AuditKeyValues": [
            {
                "Key": "quarantined_file_id",
                "ValueString": "35b35a53da374816a6b471cf09e12019_a076d3121743755f2d4f8d4d5807f0bc013177f7847d09b48e76de88ace08c78"
            },
            {
                "Key": "action_taken",
                "ValueString": "quarantined"
            }
        ],
        "UTCTimestamp": 1593186952
    }
}
```

## Filebeat Parsed Event 
```
{
  "_index": "filebeat-7.8.0-2020.06.22-000001",
  "_type": "_doc",
  "_id": "0fdX8XIBwKcnb42G66Yn",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-06-26T15:55:52.000Z",
    "service": {
      "type": "crowdstrike"
    },
    "input": {
      "type": "log"
    },
    "event": {
      "module": "crowdstrike",
      "dataset": "crowdstrike.falcon"
    },
    "fileset": {
      "name": "falcon"
    },
    "crowdstrike": {
      "metadata": {
        "eventType": "UserActivityAuditEvent",
        "eventCreationTime": 1593186952000,
        "version": "1.0",
        "customerIDString": "...redacted...",
        "offset": 22865
      },
      "event": {
        "OperationName": "quarantined_file_update",
        "ServiceName": "quarantined_files",
        "AuditKeyValues": [
          {
            "Key": "quarantined_file_id",
            "ValueString": "35b35a53da374816a6b471cf09e12019_a076d3121743755f2d4f8d4d5807f0bc013177f7847d09b48e76de88ace08c78"
          },
          {
            "Key": "action_taken",
            "ValueString": "quarantined"
          }
        ],
        "UTCTimestamp": 1593186952,
        "UserId": "Crowdstrike",
        "UserIp": ""
      }
    },
    "error": {
      "message": "GoError: failed in processor.convert: conversion of field [crowdstrike.event.UserIp] to type [ip] with target field [source.ip] failed: unable to convert value []: value is not a valid IP address"
    },
    "host": {
      "mac": [
        "...redacted..."
      ],
      "hostname": "...redacted...",
      "architecture": "x86_64",
      "os": {
        "codename": "bionic",
        "platform": "ubuntu",
        "version": "18.04.3 LTS (Bionic Beaver)",
        "family": "debian",
        "name": "Ubuntu",
        "kernel": "5.0.0-1036-azure"
      },
      "id": "...redacted...",
      "name": "...redacted...",
      "containerized": false,
      "ip": [
        "...redacted...",
        "...redacted..."
      ]
    },
    "log": {
      "flags": [
        "multiline"
      ],
      "offset": 29298,
      "file": {
        "path": "/var/log/crowdstrike/falconhoseclient/output"
      }
    },
    "tags": [
      "_js_exception"
    ],
    "agent": {
      "version": "7.8.0",
      "hostname": "...redacted...",
      "ephemeral_id": "...redacted...",
      "id": "...redacted...",
      "name": "...redacted...",
      "type": "filebeat"
    },
    "ecs": {
      "version": "1.5.0"
    },
    "cloud": {
      "region": "...redacted...",
      "provider": "az",
      "instance": {
        "id": "...redacted...",
        "name": "...redacted..."
      },
      "machine": {
        "type": "Standard_B4ms"
      }
    }
  },
  "fields": {
    "@timestamp": [
      "2020-06-26T15:55:52.000Z"
    ],
    "crowdstrike.event.UTCTimestamp": [
      "1970-01-19T10:33:06.952Z"
    ],
    "crowdstrike.metadata.eventCreationTime": [
      "2020-06-26T15:55:52.000Z"
    ],
    "suricata.eve.timestamp": [
      "2020-06-26T15:55:52.000Z"
    ]
  },
  "highlight": {
    "event.module": [
      "@kibana-highlighted-field@crowdstrike@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1593186952000
  ]
}
```

## Code with issue
`/usr/share/filebeat/module/crowdstrike/falcon/config/pipeline.js`
```
var convertFields = new processor.Convert({
        fields: [
            // DetectionSummaryEvent
            { from: "crowdstrike.event.LocalIP", to: "source.ip", type: "ip" },
            { from: "crowdstrike.event.ProcessId", to: "process.pid" },
            // UserActivityAuditEvent and AuthActivityAuditEvent
            { from: "crowdstrike.event.UserIp", to: "source.ip", type: "ip" },
        ],
        mode: "copy",
        ignore_missing: true,
        ignore_failure: true
    });
```

While `ignore_missing` and `ignore_failure` exist within this function it doesn't seem to do it. Please note the tag `_js_exception` and the error written to the document. 
```
GoError: failed in processor.convert: conversion of field [crowdstrike.event.UserIp] to type [ip] with target field [source.ip] failed: unable to convert value []: value is not a valid IP address
```

**Comment by P1llus** [comment]
@vi-or-die hello!

Thanks for the feedback, unfortunately this change was not related to your issue but rather just some cleanup from mostly older modules. The reason it mentioned that no processor was changed is that it did not have any of the set processors I was changing.

If you are experiencing issues then the appropriate place would be to create a brand new issue then someone can take a look :)

**Comment by vi-or-die** [comment]
@P1llus thanks for the context! I have a support case open and will ask if it’s necessary to have it in both places.

**Comment by P1llus** [comment]
All changes has been merged successfully so this meta ticket is now closed.
