### ISSUE TITLE
Remaining cleanup items from #17007

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#19471]
These tasks are remaining from the work started in https://github.com/elastic/beats/pull/17007:

- [x] Update links:
  - [x] apm-server https://github.com/elastic/apm-server/pull/3939
  - [x] security-docs https://github.com/elastic/security-docs/pull/43
  - [x] stack-docs https://github.com/elastic/stack-docs/pull/1234
  - [x] kibana (includes uptime docs) https://github.com/elastic/kibana/pull/70380
  - [x] observability-docs - https://github.com/elastic/observability-docs/pull/15
  - [x] logstash - https://github.com/elastic/logstash/pull/12068
  - [x] logstash-docs - created issue - https://github.com/logstash-plugins/logstash-input-log4j/issues/45
  - [x] elasticsearch - https://github.com/elastic/elasticsearch/pull/58790
  - [x] cloud - https://github.com/elastic/cloud/pull/61452
- [x] Set up redirects (see redirects.asciidoc for the list). See https://github.com/elastic/website-www.elastic.co/issues/6371.
- [x] Update commands to show sudo only when necessary. (Current docs are a mix and a bit consistent.)

**Comment by dedemorton** [comment]
Created https://github.com/elastic/beats/issues/19575 to track the addition of tabbed panels to other topics. We want to hold off until we get some user feedback before we propagate the widgets to other docs.

**Comment by dedemorton** [comment]
Created https://github.com/elastic/beats/issues/19577 to track work needed to make the What's Next section more graphical.

**Comment by dedemorton** [comment]
Created https://github.com/elastic/beats/issues/19578 to track improvements required to how-to topics.

**Comment by dedemorton** [comment]
Added js and CSS requirements to the tracking issue about the tabbed panel widgets: https://github.com/elastic/docs/issues/260#issuecomment-652722804

**Comment by dedemorton** [comment]
Closing because all the required PRs are in place (some can't be merged until 7.9 is GA).
