### ISSUE TITLE
Organize docs folder into subfolders

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#19579]
The docs folder is bloated with too many files. To help contributors, we need to organize the files better:

- [ ] Move shared files to logically named folders:
  - [ ] Put all configuration option topics into configuration folder.
  - [ ] Move misc shared files to a folder called `shared` and remove "shared" from names
  - [ ] Move all topics under "how to guides" section to a howto folder
- [ ] Move content used to build the Platform Reference into a separate folder.
