### ISSUE TITLE
[Meta] [Ingest Manager] elastic-agent .rpm (and .deb) usage fails for Fleet enroll command, docs need update, README.md needs update

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#20037]
This is found using the 7.9 BC2 .RPM file install against CentOS7

Here is the enroll command attempt:
[root@atlcolo-10-6-46-245 bin]# ./elastic-agent enroll https://b034192bc7194df8a82b4b440dd1f323.europe-west1.gcp.cloud.es.io:443 U0tMTlhITUJmSnMwRngyQXo2Ul86UDQ0ZTV1OVBTcy1LUUU5VUpQcF92UQ==
The Elastic Agent is currently in BETA and should not be used in production
could not read configuration file /usr/share/elastic-agent/bin/elastic-agent.yml: open /usr/share/elastic-agent/bin/elastic-agent.yml: no such file or directory

The command straight from the README.md says to do this:
[root@atlcolo-10-6-46-245 bin]# ./elastic-agent -c elastic-agent.yml -e
 but it doesn't work, the files aren't there.

Here is some research on the file system:
[root@atlcolo-10-6-46-245 bin]# ls -l
total 17032
-rwxr-xr-x. 1 root root 16379904 Jul 16 18:24 elastic-agent
-rwxr-xr-x. 1 root root  1057147 Jul 16 18:24 elastic-agent-god
[root@atlcolo-10-6-46-245 bin]# pwd
/usr/share/elastic-agent/bin
[root@atlcolo-10-6-46-245 bin]# ls ..
bin  LICENSE.txt  README.md
[root@atlcolo-10-6-46-245 bin]# 

Here is a cat output of the README.md file:
[README.md.txt](https://github.com/elastic/beats/files/4939891/README.md.txt)

here is a screenshot of the rpm install attempt:
<img width="1223" alt="fleet-rpm-install-fail" src="https://user-images.githubusercontent.com/12970373/87824882-19899600-c844-11ea-870b-b039d3198d7f.png">

what is this?  and should we be shipping it?  it isn't doc'ed and sounds strange and maybe dangerous
<img width="443" alt="elastic-agent-god" src="https://user-images.githubusercontent.com/12970373/87824889-1d1d1d00-c844-11ea-872b-3a8afbfd4c72.png">
- [ ] figure out g o d file?

- [ ] figure out install of Fleet or confirm that stand-alone mode MUST be executed first?

Then, can we get the requisite pages updated with info that is compliant and inclusive of the .deb and .rpm files?
- [ ] https://www.elastic.co/guide/en/ingest-management/current/ingest-management-getting-started.html
- [ ] https://www.elastic.co/downloads/elastic-agent

**Comment by EricDavisX** [comment]
@dedemorton pinging you for tracking - for Docs for 7.9 improvements for .rpm / Fleet usage for Agent

**Comment by EricDavisX** [comment]
A quick review of a: sudo dpkg -i elastic-agent-7.9.0-amd64.deb 
 call on DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
shows that the .deb file has the same problem, doesn't have all needed files.  updated short desc, image here of initial unarchive / install:
<img width="907" alt="Screen Shot 2020-07-17 at 7 45 24 PM" src="https://user-images.githubusercontent.com/12970373/87838900-8877e680-c866-11ea-8a08-3d3301c77f5d.png">

then, same attempt to start agent:
./elastic-agent enroll https://b034192bc7194df8a82b4b440dd1f323.europe-west1.gcp.cloud.es.io:443 U0tMTlhITUJmSnMwRngyQXo2Ul86UDQ0ZTV1OVBTcy1LUUU5VUpQcF92UQ==

yields:
<img width="1231" alt="Screen Shot 2020-07-17 at 7 51 18 PM" src="https://user-images.githubusercontent.com/12970373/87838993-e6a4c980-c866-11ea-9c62-6e92ab2bfb17.png">

**Comment by blakerouse** [comment]
The issue is how you are executing `elastic-agent`. You should not execute it from `/usr/share/elastic-agent/bin/elastic-agent` that one will not have the paths set correctly with the executable wrapper.

You should be using `/usr/bin/elastic-agent`. Which you can do by just calling `elastic-agent` as `/usr/bin` should be inside of `$PATH`.

This will fix your issue. To understand why you can do `cat /usr/bin/elastic-agent`.

**Comment by blakerouse** [comment]
Just to note the best way to do this from package is this, which probably should be added to the documentation.

```
$ elastic-agent enroll https://mydomain.com ${my-token}
$ systemctl enable elastic-agent
$ systemctl start elastic-agent
```

**Comment by EricDavisX** [comment]
@blakerouse thanks for the updates.  I'm re-opening to ensure Docs get updated, this is the Meta issue for any fixes that need to go in.  I'll go check it out, too

**Comment by ph** [comment]
@EricDavisX I've added a point to the 7.9 doc issues we can close this?

**Comment by EricDavisX** [comment]
sure, if we're linking details here to another ticket for ease of finding them, then sure.
