### ISSUE TITLE
Cleanup and stabilize Beater-API

### ISSUE THREAD

**Issue by urso** [elastic/beats#2005]
Simplify common API for creating a new beat:

- [x] FlagHandler registry instead of beat optionally implementing HandleFlags. FlagHandler will be called after parsing flags, but before reading any config files. #2002 
- [x] simplify Beater interface to consist of: Constructor(Initialization + Config), Run and Stop. #2003
- [x] turn publisher.Publisher into interface  #2009 
- [x] pass beat specific config section to beat on init #2014
- [x] update newbeat docs
