### ISSUE TITLE
Filebeat Configuration Changes

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#2012]
New `close_*` and `clean_*` config options are introduced. This issue is to track the progress. All discussions happened in https://github.com/elastic/beats/issues/1600

* [ ] Implement `close_timeout` https://github.com/elastic/beats/pull/1926
* [x] Rename `close_older` to `close_inactive`
* [x] Rename `clean_idle` to `clean_inactive`
* [x] Create documentation for new configuration options https://github.com/elastic/beats/pull/1963
* [x] Update configuration file with new options
* [x] Close Github issues which are resolved by the new config options
* [x] Change `close_inactive` default to 5min https://github.com/elastic/beats/pull/2157
* [x] Check changes in CHANGELOG file to be correct

**Comment by ruflin** [comment]
Closing this as all work expected for `close_timeout` has been done. All future work for `close_timeout` is tracked in https://github.com/elastic/beats/pull/1926
