### ISSUE TITLE
Log file collector based on v2 input API

### ISSUE THREAD

**Issue by urso** [elastic/beats#20243]
Implement an alternative log file collector (Name: logfile) for use with the agent based on the v2 input API.

The v2 input API allows file state to be stored in a generic key-value store, while requiring the Input type to implement all required logic for state and ACK handling. A generic implementation for stateful inputs is available in the filebeat/input/v2/input-cursor package (currently requires a static set of sources only).

### Phase 1 (feature-parity)
- [x] create a special stateful input for the new `logfile` 
- [x] add harvesters to an input dynamically
- [x] watch for file events
  - [x] create an interface that is responsible for watching changes in the input files
  - [x] refactor the current scanner so it implements the new interface
#### Missing features
- [x] JSON reader
  - [x] add it again
  - [x] rename it to NDJSON
- [x] multiline reader
- [x] configurable cleaner options

### Phase 2 (enhancements)
 
- [x] make the input log rotation aware https://github.com/elastic/beats/pull/23457
- [x] come up with a strategy for handling backpressure (high effort) https://github.com/elastic/beats/pull/25976
- [ ] address globbing issues on Windows (medium effort)
- [ ] add detailed metrics #25045

#### Inputs based on log
- [x] container logs reader (low effort) #26115

### Marking it GA
- [x] mark `filestream` input GA #26127
- [x] write blogpost about it before release
- [x] deprecate log input

~~- [ ] remove log input in 8.x~~

Related: #15324

**Comment by ph** [comment]
@kvch Could you update this issue with the remaining work for the filestream input?

**Comment by jlind23** [comment]
@kvch as discussed could you please update this issue with the missing parts?

**Comment by kvch** [comment]
I am closing this issue. Most of the work is done. The two unfinished task is tracked here separately because they are just enhancements: 
* https://github.com/elastic/beats/issues/9176
* https://github.com/elastic/beats/pull/25045
