### ISSUE TITLE
Support Python 3.9 in developer tools

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#20384]
Python 3.9 is planned to be released on October 2020, on this version some long-time deprecated code will be removed and some old Python libraries will stop working (see [this](https://tirkarthi.github.io/programming/2020/01/27/python-39-changes.html)). Check how this will affect Beats development and prepare the code to work on this version.

Identified issues
===
- [x] Nosetests was discontinued on 2015 and has been reported to stop working on Python 3.9. Migrate tests to pytest (continue with #16883).
- [x] Pillow will stop working on 3.9, 8.0 release planned https://github.com/python-pillow/Pillow/issues/4764 (removed #20407).
- [x] Elasticsearch python library #20405.
- [ ] Review deprecation warnings and address them when possible (see #19915).
- [ ] Consider making deprecation warnings to provoke errors (`filterwarnings = error::DeprecationWarning` in `pytest.ini`) #20603.

**Comment by radarhere** [comment]
'Pillow will stop working on 3.9' - I think you mean Pillow will stop working on 3.5?
