### ISSUE TITLE
Add index pattern, rename index options

### ISSUE THREAD

**Issue by tsg** [elastic/beats#2074]
Meta issue for transforming the Elasticsearch output index option into an index pattern (#921) and for cleaning up the outputs configuration around indices.

Tasks:

* [x] In the Redis output, rename the `index` option to `key`, deprecating `index` for now. #2077.
* [x] In the file output, remove the `index` option. #2077
* [x] In the elasticsearch output, make `index` accept an index pattern #2119
* [x] Remove the index hack from the publisher code, and use the beatName as appropiate
* [x] Update docs
