### ISSUE TITLE
Improve packaging for community Beats

### ISSUE THREAD

**Issue by tsg** [elastic/beats#2128]
#2125 has revealed some issues with the packaging for the community Beats created with the generator. This is a meta ticket for improvements:
- [ ] The generator doesn't encourage people to use a vendor directory, but it is actually required for packaging. I think we will save people time if we run `glide create` and `glide install --strip-vcs` during the setup phase and we default the ES_BEATS Makefile variable to the vendor dir.
- [ ] #2130 The generation of the dev-tools files currently happens at time of make package, but since these files should generally be committed, it would make more sense to include them in the generator template.
- [x] #2129 The current dev-tools/packer/Makefile assumes Cgo, but most community Beats are pure Go. I think it's better to assume pure go, as the compilation is faster and the resulting binaries are static.

**Comment by kaiyan-sheng** [comment]
Closing this issue, generator has been almost rewritten by @fearful-symmetry.
