### ISSUE TITLE
Migrate metricsets in aws module to use cloudwatch input as lightweight module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#21422]
In `aws` module we have several metricsets that are not lightweight modules. This issue is to track the work for converting them into lightweight modules. There are some problems we are facing:

1. Some metricsets are not only calling CloudWatch API. For example, billing metricset is also making CostExplorer API and ec2 metricset is also making DescribeInstances API.

- [ ] ~~* billing: also uses CostExplorer API~~
- [x] * ec2: also uses EC2 DescribeInstances API https://github.com/elastic/beats/pull/25924
- [x] * rds: also uses RDS DescribeDBInstances API https://github.com/elastic/beats/pull/26077
- [x] * s3_daily_storage:  easy migration https://github.com/elastic/beats/pull/21703
- [x] * s3_request: easy migration https://github.com/elastic/beats/pull/21703
- [x] * sqs: also uses SQS ListQueues API https://github.com/elastic/beats/pull/26117

2. How to keep backwards compatibility with metric names. For example, after using lightweight module, `aws.ec2.cpu.total.pct` will be `aws.ec2. CPUUtilization.avg`. @jsoriano suggested that fields can be renamed using processors. This will be a good option to keep both names instead of making a breaking change.

This is a meta issue to track the work for migrating all listed metricsets above to use lightweight modules. 

cc: @exekias @jsoriano @sorantis

**Comment by kaiyan-sheng** [comment]
Migrate `ec2` metricset: https://github.com/elastic/beats/pull/25924

**Comment by kaiyan-sheng** [comment]
Migrate `sqs` metricset: https://github.com/elastic/beats/pull/26117

**Comment by kaiyan-sheng** [comment]
Update: For `ec2`, `rds` and `sqs`, we are adding metadata from separate API calls into the events that are populated from CloudWatch API response. `billing` metricset in `aws` module is not the same as other metricsets because it is not adding _metadata_ into the same events. Instead, `billing` is creating two sets of events: from CloudWatch and from Cost Explorer. 
I will keep `billing` metricset as it is for now. Maybe we should think about separating `billing` into its separate module in the future.
