### ISSUE TITLE
Improve generators

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#2148]
- [ ] Decide on exact usage of vendor directory (what is our recommendation)
- [ ] Decide if glide should be used
- [ ] Decide if we recommend to check in vendor or not
- [ ] Add docs for vendoring
- [ ] Improve location of templates for generation from python code (currently under scripts)
- [ ] Simplify python generator scripts (remove duplicated code)

**Comment by ruflin** [comment]
See also https://github.com/elastic/beats/issues/2128

**Comment by tsg** [comment]
Old issue, cleaning up.
