### ISSUE TITLE
[ECS] Upgrade modules to 1.7

### ISSUE THREAD

**Issue by marc-gr** [elastic/beats#21674]
Required changes to upgrade beats modules to 1.7:

- [x]  After 1.7 is released, update ecs dependency to 1.7 e.g.: #20792

Using https://github.com/elastic/ecs-dev/issues/199 as reference:

**Experimental**

*Use of basic types with wildcard elastic/dev#1508 elastic/ecs#970*:
(important note: **Going with option 2 will require each Beat to implement this fallback mechanism to replace wildcard to keyword, when posting an index template to Elasticsearch.**)

- [x] Auditbeat (https://github.com/elastic/beats/pull/22571)
- [x] Metricbeat (https://github.com/elastic/beats/pull/22571)
- [x] Heartbeat (https://github.com/elastic/beats/pull/22571)
- [x] Packetbeat (https://github.com/elastic/beats/pull/22571)
- [x] Winlogbeat (https://github.com/elastic/beats/pull/22571)
- [x] Auditbeat  (https://github.com/elastic/beats/pull/22571)
- [x] Packetbeat (https://github.com/elastic/beats/pull/22571)
- [x] Winlogbeat (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat auditd (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat rsa2elk modules (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat checkpoint firewall (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat cisco asa (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat cef (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat cisco ftd (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat cisco umbrella (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat citrix netscaler (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat f5 (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat crowdstrike falcon (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat fortinet  (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat googlecloud audit (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat microsoft (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat Gsuite (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat o365 (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat zoom (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat okta (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat aws cloudtrail (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat barracuda (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat s3 (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat juniper (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat netscout (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat panw (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat snort (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat sonicwall (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat sophos (https://github.com/elastic/beats/pull/22571)
- [x] Filebeat zeek (https://github.com/elastic/beats/pull/22571)

<details>
<summary>Multiple users in an event elastic/ecs#914</summary>

- [ ] Auditbeat
- [ ] Packetbeat
- [ ] Winlogbeat
- [ ] Filebeat auditd
- [ ] Filebeat rsa2elk modules
- [ ] Filebeat checkpoint firewall
- [ ] Filebeat cisco asa
- [ ] Filebeat cef
- [ ] Filebeat cisco ftd
- [ ] Filebeat cisco umbrella
- [ ] Filebeat citrix netscaler
- [ ] Filebeat f5
- [ ] Filebeat crowdstrike falcon
- [ ] Filebeat fortinet clientendpoint
- [ ] Filebeat fortinet firewall
- [ ] Filebeat fortinet fortimail
- [ ] Filebeat fortinet fortimanager
- [ ] Filebeat googlecloud audit
- [ ] Filebeat microsoft
- [ ] Filebeat Gsuite
- [ ] Filebeat o365
- [ ] Filebeat zoom
- [ ] Filebeat okta
- [ ] Filebeat aws cloudtrail
- [ ] Filebeat barracuda
- [ ] Filebeat s3
- [ ] Filebeat juniper
- [ ] Filebeat netscout
- [ ] Filebeat panw
- [ ] Filebeat snort
- [ ] Filebeat sonicwall
- [ ] Filebeat sophos
- [ ] Filebeat zeek irc
- [ ] Filebeat zeek kerberos
- [ ] Filebeat zeek ntlm
- [ ] Filebeat zeek radius
- [ ] Filebeat zeek webhook

</details>

**Additions in 1.7**:

*New `ingress` and `egress` allowed values for `network.direction` elastic/ecs#945*:

- [x] Auditbeat auditd (https://github.com/elastic/go-libaudit/pull/80) (#23000)
- [x] Auditbeat system/socket (#22991)
- [x] Metricbeat (#22992)
- [x] Packetbeat (#22996)
- [x] Winlogbeat (#22997)
- [x] Filebeat auditd (#23041)
- [x] Filebeat crowdstrike falcon (#23041)
- [x] Filebeat netflow (#23052)
- [x] Filebeat checkpoint firewall (#23066)
- [x] Filebeat cef (#23066)
- [x] Filebeat cisco asa (#23068)
- [x] Filebeat cisco ftd (#23068)
- [x] Filebeat fortinet firewall (#23072)
- [x] ~~Filebeat cisco umbrella~~ (waiting on CIDR matching processors/painless support in elasticsearch https://github.com/elastic/elasticsearch/issues/60668)
- [x] Filebeat googlecloud firewall (#23081)
- [x] Filebeat googlecloud vpcflow (#23081)
- [x] Filebeat panw panos (elastic/beats#22998)
- [x] Filebeat sophos xg (elastic/beats#22973)
- [x] Filebeat zeek connection (elastic/beats#22967)
- [x] ~~Filebeat rsa2elk modules~~ (@adriansr) (need to add individual module configuration support, see https://github.com/elastic/beats/issues/23114)

*HTTP request/response mime type elastic/ecs#944*:
(important note: **needs to analyze body**)

- [x] Packetbeat (#22940)
- [x] Hearbeat (#22976)
- [x] Filebeat elasticsearch (#22975)
- [x] ~~Filebeat o365~~ (doesn't capture request/response body)
- [x] ~~Filebeat gsuite~~ (doesn't capture request/response body)
- [x] ~~Filebeat suricata eve~~ (doesn't capture request/response body)
- [x] ~~Filebeat rsa2elk modules~~ (doesn't capture request/response body)
- [x] ~~Filebeat checkpoint firewall~~ (doesn't capture request/response body)
- [x] ~~Filebeat cef~~ (doesn't capture request/response body)
- [x] ~~Filebeat cisco ftd~~ (doesn't capture request/response body)
- [x] ~~Filebeat cisco umbrella~~ (doesn't capture request/response body)
- [x] ~~Filebeat fortinet clientendpoint~~ (doesn't capture request/response body)
- [x] ~~Filebeat fortinet firewall~~ (doesn't capture request/response body)
- [x] ~~Filebeat fortinet fortimail~~ (doesn't capture request/response body)
- [x] ~~Filebeat fortinet fortimanager~~ (doesn't capture request/response body)
- [x] ~~Filebeat panw panos~~ (doesn't capture request/response body)
- [x] ~~Filebeat sophos xg~~ (doesn't capture request/response body)
- [x] ~~Filebeat zeek http~~ (doesn't capture request/response body)

*New allowed value `configuration` for `event.category` elastic/ecs#963*:

- [x] Winlogbeat (https://github.com/elastic/beats/pull/22988)
- [x] ~~Auditbeat system~~ (no configuration events to be classified)
- [x] Auditbeat auditd (https://github.com/elastic/go-libaudit/pull/80) (#23000)
- [x] Filebeat auditd (#23010)
- [x] Filebeat GSuite (#23010)
- [x] Filebeat zoom (#23010)
- [x] Filebeat o365 (#23010)
- [x] ~~Filebeat Okta~~ (no configuration events to be classified)
- [x] ~~Filebeat microsoft~~ (check if rsa2elk microsoft modules need updating)
- [x] ~~Filebeat rsa2elk modules~~ (currently we don't do any event categorization)

*Add `subdomain` domain breakdown across all domain breakdowns (currently only in `dns`) elastic/ecs#981*:

- [x] ~~Packetbeat~~ (seems done for `dns`)
- [x] Winlogbeat (#22999)
- [x] Filebeat suricata eve (#23011)
- [x] Filebeat zeek dns (#23011)
- [x] Filebeat rsa2elk modules (@adriansr)

**Comment by webmat** [comment]
@marc-gr If the team would rather tackle only 1/2 of the experimental changes (e.g. only wildcard), you're welcome to do so. 

Me or @ebeahan can help you get the artifacts you need, to only grab the relevant experimental changes, rather than both changes at once.

**Comment by marc-gr** [comment]
@jamiehynds maybe can give some input about what we want to do with the experimental changes

**Comment by jamiehynds** [comment]
> @jamiehynds maybe can give some input about what we want to do with the experimental changes

Discussed with @epixa and @andrewkroh yesterday. Adopting multi-user and wildcard is something we'd like to do. Once we have a clearer picture on affected modules and level of effort, we can prioritise which modules to focus on for 7.11.

**Comment by andrewstucki** [comment]
Closing this since we're done and moving on to 1.8 upgrade
