### ISSUE TITLE
Update docs with #2167 changes

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#2243]
After #2167  is merged we need to update the examples in the docs with the following changes:

- [ ] `http.params` -> `http.request.params`
- [ ] `http.code` -> `http.response.code`
- [ ] `http.phrase` -> `http.response.phrase`
- [ ] `http.request_headers` -> `http.request.headers`
- [ ] `http.response_headers` -> `http.response.headers`
- [ ] `http.content_length` -> `http.response.headers["content-length"]`
- [ ] `http.content_type` -> `http.response.headers["content-type"]`

cc-ed @dedemorton

**Comment by monicasarbu** [comment]
https://github.com/elastic/beats/pull/2241 fixes a few of these examples.
