### ISSUE TITLE
Improve packaging and crosscompiling

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#2251]
Currently community beats have to use `make create-packer` to add the files for building packages. This generates lots of duplicated code which is hard to update at a later stage. In addition the packaging of community beats does not work the same as our own beats. Same code should be use for the internal beats and the community beats.
- [x] Move packaging script to libbeat to be available in each beat. It should use variables for the beats https://github.com/elastic/beats/pull/2185
- [x] Remove package generator as not needed anymore https://github.com/elastic/beats/pull/2185
- [ ] Add `.package.yml` file with all information inside for each beat
- [ ] Reenabled parallel packaging builds
  - Some tricks can be found here: http://stackoverflow.com/questions/1681006/parallelization-of-recursive-jobs-in-gnu-make
- [ ] Rewrite packaging as python script
- [ ] Update developer docs
- [ ] Document how builds for only `packetbeat/deb` work.
- [x] Change `BEAT_PATH` to always include the `BEATNAME`. Currently `BEAT_PATH` has 2 meanings. #2185
- [ ] Test if all build processes with nightly builds and releases work
- [x] Rename `BEATNAME` to `BEAT_NAME` for consistency
- [x] Test it with community beats #2185
- [x] Clean up two meanings of `BEATPATH` #2185
- [x] Move `dev-tools/packer/scripts/Makefile` to `dev-tools/packer/Makefile` #2185

**Comment by tsg** [comment]
Old issue, cleaning up.
