### ISSUE TITLE
Metricbeat PostgreSQL module

### ISSUE THREAD

**Issue by tsg** [elastic/beats#2255]
Meta ticket for adding the Metricbeat PGSQL module
* [x] #2253 Core functionality
* [x] #2253 Activity metricset
* [x] #2266 Database metricset
* [x] #2319 Background writer metricset
* [x] #2266 Clean up default configuration files
* [x] #2266 Add system tests to check for errors and fields

**Comment by tsg** [comment]
All PRs merged.
