### ISSUE TITLE
Add integration tests for authentication methods in Kafka output

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#23112]
Current integration tests in libbeat only cover the use of Kafka without authentication, but Beats support more authentication methods.

These authentication methods should be covered:

- [x] No authentication (should be already covered by current integration tests).
- [x] SASL/PLAIN (plain username/password).
- [x] SSL
- [x] SASL-SCRAM-SHA256/512
- [ ] Kerberos

https://strimzi.io/ is a Kubernetes operator that is able to start Kafka clusters with these configurations (except for Kerberos https://github.com/strimzi/strimzi-kafka-operator/issues/3088). We might try to use it, or prepare different docker compose scenarios as we have done so far. We can also try to add multiple listeners to current docker-compose scenario.

Once we have these tests we can GA Kerberos and SASL-SCRAM authentication methods.

**Comment by faec** [comment]
Closing in favor of https://github.com/elastic/beats/issues/29430 since Kerberos is the only one left outstanding
