### ISSUE TITLE
[Elastic Agent] [Meta] Gathering logs and metrics from Kubernetes without using fleet generated agent config and without central agent management via fleet

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#23613]
## Requirements

We expect Elastic Agent inside of Kubernetes in standalone mode (no connection to fleet-server, not using fleet-server to update agent config) to collect 

- metrics and logs for kubernetes components - master node and the processes it runs, worker node and the processes it runs
- system metrics and logs of master and worker nodes
-  pod metrics and logs to ES via auto-discovery through dynamic inputs and hints based discovery i.e. nginx running on K8s pods can send their metrics and logs to ES auto-magically as long as the agent policy contains appropriate conditional logic

In addition we will provide 
- K8s integration that operator needs to install to observe K8s master and worker nodes and the infrastructure running K8s cluster, when installed it will display the K8s dashboards we provide today with metricbeat
- Documentation guide that walks through steps required to enable K8s and pod level observability with elastic agent in standalone mode 

**Note:**
This issue explicitly ignores Fleet Mode, once standalone mode is working and documented then Fleet Mode will be the next target.

## Core Issues
- [x] Update K8s resource definition to use a host mount point for storing the running `filebeat` registry.
   * At the moment this is nested under the Elastic Agent data directory that changes on every build of Elastic Agent `/usr/share/data/elastic-agent-{{ commit_short }}/run`. Because of the `{{commit_short}}` being changed on every build this causes an issue with using a host mount point. #24160
- [x] Dynamic inputs fail to get validated https://github.com/elastic/beats/issues/23685
- [x] Documentation guide that walks through steps required to enable K8s and pod level observability with elastic agent in standalone mode https://github.com/elastic/beats/issues/21848, PR: https://github.com/elastic/observability-docs/pull/401
- [x] Add Metricbeat `--system.hostfs equivalent` to Elastic Agent https://github.com/elastic/beats/issues/22915 PR: https://github.com/elastic/beats/pull/23831

## Logs & Metrics
- [x] System-level log collection - Logs from nodes of the Kubernetes cluster like `/var/log/syslog', `/var/log/secure`, etc. should be collected by Elastic Agent. PR: https://github.com/elastic/beats/pull/24185
   - [x] Update the K8s resource definition to include the correct host-level mount points to collect these logs.
   - [x] Update the K8s resource definition to enable the system level log collection.
- [x] Pod-level log collection - Logs from the running Pods in the cluster should be collected by Elastic Agent #23938
   - [x] Update the K8s resource definition to include the correct host-level mount points to collect these logs.
   - [x] Update the K8s resource definition to enable the log collection using inputs with variables.
- [x] System-level metrics collection - Metrics (cpu/memory/etc.) from the nodes of the Kubernetes cluster https://github.com/elastic/beats/pull/23938
   - [x] Update the K8s resource definition to include the correct host-level mount points to collect these metrics from `/proc` and `/sys`.
     - Known Issue: #22915
   - [x] Update the K8s resource definition to enable the system metrics collection.
- [x] Pod-level metrics collections - Metrics (cpu/memory/etc.) from the pods running in the Kubernetes cluster https://github.com/elastic/beats/issues/23618
   - [x] Update the K8s resource definition to collect metrics from `kubelet`.
- [x] Kubernetes state metrics collection - Metrics (create/update/delete/etcs.) from the Kubernetes state https://github.com/elastic/beats/issues/23618
   - [x] Update the K8s resource definition to collect metrics from `kube-state-metrics`.
- [x] K8s integrations package (template, dashboard) elastic/integrations#511

## Need to be investigated
- [ ] hints support in K8s provider for agent https://github.com/elastic/beats/issues/23876

**Comment by mukeshelastic** [comment]
@blakerouse thanks so much for writing this issue. I think this covers the K8s control plane observability for worker and master nodes very well. Does it also cover etcd observability? the pod level logs and metrics collection - what use cases does that cover? e.g. If pod runs nginx server then, are we able to collect nginx metrics and logs for it? What does the user need to do to enable that? Also if it's easier, I am happy to divide the issue into two separate ones - one for control plane observability and other for pod level observability.

**Comment by ChrsMark** [comment]
Hi @mukeshelastic ! If I'm not mistaken, Pod level observability will be covered by Dynamic Inputs and more specifically kubernetes provider (https://github.com/elastic/beats/pull/21480), this is the former Autodiscover feature (hints not included yet). I tried to leverage this functionality at https://github.com/elastic/beats/issues/23618 https://github.com/elastic/beats/pull/23679 so as to dynamically collect metrics from k8s core components that are deployed as pods on master nodes. If we manage to make this use case work then we verify that we can support collecting metrics/logs from every pod dynamically, if it is covered by conditions in Agent's config since we don't support hints yet. I think we can add this as an extra/separate point in this Issue's description.

In this regard, we might need to cover this in our docs soon (https://github.com/elastic/beats/issues/21848) cc: @ph

**Comment by ph** [comment]
@ChrsMark @blakerouse make sure if you find any issues related to the implementation please add them to this meta issue so we can prioritize them.

**Comment by ChrsMark** [comment]
@blakerouse about point no1 are we sure that we want it? We don't have something like this enabled by default right now in Filebeat's manifests.

cc: @masci @ruflin

**Comment by blakerouse** [comment]
@ChrsMark Are you talking about `System-level log collection`? I think it would be great to have. Log collection of the underlying host is just as important as collecting logs about the cluster and the workloads.

**Comment by ChrsMark** [comment]
> @ChrsMark Are you talking about `System-level log collection`? I think it would be great to have. Log collection of the underlying host is just as important as collecting logs about the cluster and the workloads.

Yeap, ok then I agree it would be a good insight. Let's add it then.

**Comment by mukeshelastic** [comment]
There are few different layers for K8s here - system host that runs an OS, K8s worker node, pods, containers. And getting metrics and logs for each of them is valuable. Assuming your question was about  "system host", yes it will be valuable to get those logs for troubleshooting system issues that may cause problems to pods running on it. I am assuming these logs are same as what we'd get by running system integration.

**Comment by ChrsMark** [comment]
@ruflin @ph @masci Related to ph's [comment](https://github.com/elastic/observability-docs/pull/401#issuecomment-785291929), since now we have most of the list completed what do you think about backporting the manifest to `7.13`?

**Comment by ruflin** [comment]
++

**Comment by ph** [comment]
@chrsMark +++ Please lets do it, this is super amazing. thanks for thepush on this.

**Comment by ChrsMark** [comment]
👍🏼 Back-ported to `7.x` with https://github.com/elastic/beats/pull/24231

**Comment by blakerouse** [comment]
There is only one issue left that is under "Needs Investigation":

> * [ ]  hints support in K8s provider for agent #23876

I don't know if hints support is required for this to be considered to be complete, but we have made great progress on this issue.

**Comment by blakerouse** [comment]
Being that everything is fixed on this issue minus the hints supports, which has other requirements I am going to close this issue.
