### ISSUE TITLE
[Meta] Migration processor documentation to Elastic Agent

### ISSUE THREAD

**Issue by ph** [elastic/beats#23746]
- [ ] add_cloudfoundry_metadata
- [ ] add_cloud_metadata
- [ ] add_docker_metadata
- [ ] add_formatted_index
- [ ] add_host_metadata
- [ ] add_id
- [ ] add_kubernetes_metadata
- [ ] add_locale
- [ ] add_nomad_metadata
- [ ] add_observer_metadata
- [ ] add_process_metadata
- [ ] communityid
- [ ] convert
- [ ] decode_csv_fields
- [ ] dissect
- [ ] dns
- [ ] extract_array
- [ ] fingerprint
- [ ] ratelimit
- [ ] registered_domain
- [ ] script
- [ ] timeseries
- [ ] timestamp
- [ ] translate_sid
- [ ] urldecode

**Comment by ph** [comment]
@ruflin @andresrc @urso @mostlyjason Anything we should not carry over to Elastic Agent?

**Comment by ruflin** [comment]
As with the inputs, I would suggest we go one by one and keep is as the tracking issue. Whoever is going to transfer it should think through why we need the processor and where. Are all of them already supported today?

**Comment by dedemorton** [comment]
I've opened a PR containing the process docs listed in this issue: elastic/observability-docs#500

I need to know if there are any other processors you want documented (this list leaves out quite a few).
