### ISSUE TITLE
Remove outdated dev guides in old branches and point to master instead

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#2376]
Creating a meta issue to group all the work related to removing dev guide content from all branches except master and pointing to master instead:

- [x]  In 1.2, remove old dev guide, override header, and point to master. See #2360 
- [x]  In 1.3, remove old dev guide, override header, and point to master. See #2361 
- [x]  In 1.0.1, override header. See #2373 
- [x]  In 1.1, override header. See #2374 
- [x]  Create redirects for the pages that we remove from 1.2 and current. see https://github.com/elastic/website-www.elastic.co/issues/1192

NOTE: Decided to keep the docs in master and 5.0 to make it easier to sync.

**Comment by dedemorton** [comment]
@tsg It's a bit strange for us to have changes going on into master that we don't want merged at some point into later branches (like 5.0). I'm not sure how we can handle this easily. Thoughts?

**Comment by tsg** [comment]
Yeah, this could potentially become a maintenance headache, as we're going to have to constantly remove stuff from branches. Ideally would be if asciidoc could have conditionals based on the branch name, but probably that's not the case.

Another option would be to split the dev guides in their own book, which we only ever publish from master.

**Comment by dedemorton** [comment]
I'm leaning towards moving the Dev topics to a separate book. I have this on the list of discussion items for the meeting in Sept, but maybe we should discuss the issue before then.
