### ISSUE TITLE
[Meta] Replace the logfile input with the Filestream input

### ISSUE THREAD

**Issue by ph** [elastic/beats#23822]
There are a few issues with the current logfile implementation: cannot read the same file from two differents inputs, problems when updating the registry, problems when an input is started with autodiscover, problems trying to stop a logfile input. (original PR https://github.com/elastic/beats/pull/21427)

The logfile input is also a building block for the container input and the docker input (which is deprecated). The current implementation is not considered feature complete and doesn't implement the full feature set of the logfile input.

# Filestream's tasks 

- [x] Meta issue https://github.com/elastic/beats/issues/20243 

# Fleet's tasks

- [x] Move internal log collection to the Filestream input
- [ ] Migrate integrations to use the Filestream input instead of the logfile input.

**Comment by urso** [comment]
Related meta issues:
- https://github.com/elastic/beats/issues/20243
- https://github.com/elastic/beats/issues/15324

**Comment by kvch** [comment]
I have created a meta issue for porting Python tests of `log` input: https://github.com/elastic/beats/issues/24246

**Comment by EricDavisX** [comment]
Hi - @ph can you help me understand what this ticket is about?  I don't have context much and would like to see links / info I can research or just read any added description we can add. Thank you in advance.

**Comment by jlind23** [comment]
Needs to be closed by @kvch

**Comment by kvch** [comment]
Closing in favour of https://github.com/elastic/integrations/issues/2518
