### ISSUE TITLE
[ECS] Upgrade modules to ECS 1.9

### ISSUE THREAD

**Issue by epixa** [elastic/beats#23937]
- [x] Update ECS to 1.9 after release

#### Multi user support https://github.com/elastic/ecs/blob/master/rfcs/text/0007-multiple-users.md

- [x] Done in previous release

**Comment by andrewkroh** [comment]
TODO:

- [ ] Sync ecs 1.9 schema to libbeat.
- [ ] `add_cloud_metadata` is affected by the `cloud.service.name` field change.
