### ISSUE TITLE
Add Logstash support to Elastic Agent in standalone mode

### ISSUE THREAD

**Issue by ph** [elastic/beats#24020]
AC
- [x] I should be able to configure Elastic Agent as an output.
- [x] Fix the issue with Monitoring and Logstash https://github.com/elastic/beats/issues/22051
- [x] Logstash usage should be documented  https://github.com/elastic/observability-docs/issues/535
- [ ] I should have end 2 end testing for Logstash https://github.com/elastic/e2e-testing/issues/364

**Comment by EricDavisX** [comment]
@ph @andresrc Hi, do we have any tickets can we link to for coordination with the Logstash (or other) team on this?  And If we can identify how the changes will impact the Agent design or implementation we can figure out if "only" a regression test is desired from the manual test team, or if we want to design additional tests to explicitly cover the Logstash input.

**Comment by EricDavisX** [comment]
I have reviewed and now closed out the 'docs' needs list item above.

And, I don't believe we have an automated test for this yet, so that is why it remains open.  :) 

The effort to support multiple outputs (including Logstash) in Fleet is coming in a future release tracked here: 
https://github.com/elastic/kibana/issues/108968

So I submit when that is achieved we could choose to leapfrog that test and just automate it from Fleet (which is a more inclusive test and still covers the Agent side).  The automation test ticket is here:
https://github.com/elastic/e2e-testing/issues/364

I will expand it to cite it can cover Fleet mode when the above is implemented.

**Comment by jlind23** [comment]
@elastic/elastic-agent-data-plane the work to achieve here is only related to testing. Some more automated testing scenario must be added.

**Comment by jlind23** [comment]
As discussed with @faec, we will close this issue for now as we won't add Logstash e2e-tests for beats inside the e2e repository. 
Other Logstash tests will be added by @lykkin following the work done on the Logstash output under Elastic Agent.
