### ISSUE TITLE
Port Python tests of log input to Golang with filestream input

### ISSUE THREAD

**Issue by kvch** [elastic/beats#24246]
# Why?

The goal of this issue is to move all Python tests related to the `log` input to Golang and use the new `filestream` input. These existing tests cover valuable knowledge about edge cases of the `log` input. To make sure `filestream` input is at least as stable as the `log` input, we need to run the same tests for the new input.

# How?

All end-to-end tests are written in Python for the `log` input. However, some of these test does not require starting Filebeat, asserting that specific log lines are present, etc. It is much faster to run the input itself from Golang and assert that events have arrived and offsets are updated in the registry. Furthermore, these test no longer depend on log messages so changing logging will not break existing tests.

Note: It might turn out that some of the test below are better suited for Python E2E tests. In this case, we are going to run the same test for both input types with the help of `parameterized`.

# What?

- [x] **filebeat/tests/system/test_harvester.py**
  - [x] `test_bom_utf8` #24397
~~- [ ] `test_boms_0_utf_8`~~ duplicate of prev test
  - [x] `test_boms_1_utf_16be_bom` #24397
  - [x] `test_boms_2_utf_16le_bom` #24397
  - [x] `test_close_eof` #24190
  - [x] `test_close_removed` #24250
  - [x] `test_close_renamed` #24190
  - [x] `test_close_timeout` #24397
~~- [ ] `test_debug_reader`~~ asserts debug log contents
~~- [ ] `test_decode_error`~~ assert error log
  - [x] `test_empty_line` #24250
  - [x] `test_empty_lines_only` #24250
  - [x] `test_exceed_buffer` #24250
  - [x] `test_ignore_symlink`
  - [x] `test_symlink_and_file` #24397
  - [x] `test_symlink_removed` #24397
  - [x] `test_symlink_rotated` #24397
  - [x] `test_symlinks_enabled` #24397
  - [x] `test_truncate` #24397
  - [x] `test_truncated_file_closed` #24397
  - [x] `test_truncated_file_open` #24397

- [ ] **filebeat/tests/system/test_input.py**
  - [x] `test_close_inactive` #24706
  - [x] `test_close_inactive_file_removal` #24706
  - [x] `test_close_inactive_file_rotation_and_removal` #24706
  - [x] `test_close_inactive_file_rotation_and_removal2` #24706
  - [ ] `test_disable_recursive_glob`
  - [x] `test_exclude_files`: `fswatch_test.go:TestFileScanner/skip_excluded_files`
  - [ ] `test_files_added_late`
  - [x] `test_harvester_limit` #21631
  - [x] `test_ignore_older_files`: `prospector_test.go:TestProspectorNewAndUpdatedFiles/old_files_with_ignore_older_configured`
  - [ ] `test_inode_marker_based_identity_tracking`
  - [ ] `test_inode_marker_based_identity_tracking_to_path_based`
  - [x] `test_no_paths_defined`: `config_test.go:TestConfigValidate/paths_cannot_be_empty`
  - [x] `test_not_ignore_old_files`
  - [ ] `test_path_based_identity_tracking`
  - [ ] `test_restart_recursive_glob`
  - [x] `test_rotating_close_inactive_larger_write_rate` https://github.com/elastic/beats/pull/32039
  - [x] `test_rotating_close_inactive_low_write_rate` https://github.com/elastic/beats/pull/32045
~~  - [ ] `test_shutdown_no_inputs`~~ not relevant to `filestream`
  - [x] `test_skip_symlinks`: `fswatch_test_non_windows.go:TestFileScannerSymlinks/skip_symlinks`

- [ ] **filebeat/tests/system/test_registrar.py**
  - [ ] `test_clean_inactive`
  - [ ] `test_clean_removed`
  - [ ] `test_clean_removed_with_clean_inactive`
  - [ ] `test_ignore_older_state`
  - [ ] `test_ignore_older_state_clean_inactive`

- [x] **filebeat/tests/system/test_json.py**
  ~~- [ ] `test_config_no_msg_key_filtering`~~ specific to `log` input
  ~~- [ ] `test_config_no_msg_key_multiline`~~ specific to `log` input
  - [x] `test_docker_logs` #24763
  - [x] `test_docker_logs_filtering` #24763
  - [x] `test_id_in_message`
  ~~- [ ] `test_integer_condition`~~ must be E2E test, it involves `drop_event` processor
 ~~- [ ] `test_json_add_tags`~~ must stay Python as tags is in pipeline
  ~~- [ ] `test_json_decoding_error_false`~~ must keep E2E, the test checks if there is no error logged in the log file of the Beat
  ~~- [ ] `test_json_decoding_error_true`~~ must keep E2E, the test checks if there is an error logged in the log file of the Beat
  - [x] `test_simple_json_overwrite` #24763
  - [x] `test_timestamp_in_message` #24763
  - [x] `test_type_in_message` https://github.com/elastic/beats/pull/32032

- [x] **filebeat/tests/system/test_multiline.py**
  - [x] `test_c_style_log` #24763
  - [x] `test_close_timeout_with_multiline` #24763
  - [x] `test_consecutive_newline` #24763
  - [x] `test_invalid_config` #24644
  - [x] `test_java_elasticsearch_log` #24763
  - [x] `test_max_bytes` #24763
  - [x] `test_max_lines` #24763
  - [x] `test_rabbitmq_multiline_log` #24763
  - [x] `test_timeout` #24763

**Comment by kvch** [comment]
The tests that are already running in Golang using the filestream input can be deleted from the Python test suite. We no longer support the log input, so there is no need to run duplicate tests for it.

**Comment by kvch** [comment]
Significant tests that are missing from `filestream`:
- [ ] test_rotating_close_inactive_larger_write_rate
- [ ] test_rotating_close_inactive_low_write_rate

The tests from `test_registry.py` should not be migrated because most of the are low-value and specific to the `log` input. Some of the tests like `test_clean_inactive` or `test_clean_removed` is tested from the package `input-logfile`. But as the registry behaves differently in `filestream`, it does not really make sense to compare the two tests.
