### ISSUE TITLE
Get redirects set up for the following topics: 

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#2426]
Details of the redirects are in the comments.

**Redirects to set up for 5.0 (now):**
- [x] Redirects for #2330: change "tls" to "ssl"
- [x] Redirects for #2505 (removal of dashboard content from Platform Ref)
- [x] Filebeat redirects resulting from edits and content restructuring.
- [x] Packetbeat redirects resulting from edits and content restructuring. 
- [x] Winlogbeat redirects resulting from edits and content restructuring. 
- [x] Metricbeat redirects resulting from edits and content restructuring. 
- [x] Redirects for changes to Developer Guide for creating new beats. 

**Redirects to set up at GA (when 5.0 is made “current”):**
- [x] Redirects for #2330: change "tls" to "ssl"
- [x] Redirects for removal of the shipper section
- [x] Redirects for #2505 (removal of dashboard content from Platform Ref)
- [x] Filebeat redirects resulting from edits and content restructuring. 
- [x] Packetbeat redirects resulting from edits and content restructuring. 
- [x] Winlogbeat redirects resulting from edits and content restructuring.

**Comment by dedemorton** [comment]
**5.0 Redirects for #2330** 
_OLD URLs:_

1. https://www.elastic.co/guide/en/beats/packetbeat/5.0/configuring-tls-logstash.html
2. https://www.elastic.co/guide/en/beats/packetbeat/5.0/configuration-output-tls.html
3. https://www.elastic.co/guide/en/beats/filebeat/5.0/configuring-tls-logstash.html
4. https://www.elastic.co/guide/en/beats/filebeat/5.0/configuration-output-tls.html
5. https://www.elastic.co/guide/en/beats/metricbeat/5.0/configuring-tls-logstash.html
6. https://www.elastic.co/guide/en/beats/metricbeat/5.0/configuration-output-tls.html
7. https://www.elastic.co/guide/en/beats/winlogbeat/5.0/configuring-tls-logstash.html
8. https://www.elastic.co/guide/en/beats/winlogbeat/5.0/configuration-output-tls.html

_NEW URLs:_

1. https://www.elastic.co/guide/en/beats/packetbeat/5.0/configuring-ssl-logstash.html
2. https://www.elastic.co/guide/en/beats/packetbeat/5.0/configuration-output-ssl.html
3. https://www.elastic.co/guide/en/beats/filebeat/5.0/configuring-ssl-logstash.html
4. https://www.elastic.co/guide/en/beats/filebeat/5.0/configuration-output-ssl.html
5. https://www.elastic.co/guide/en/beats/metricbeat/5.0/configuring-ssl-logstash.html
6. https://www.elastic.co/guide/en/beats/metricbeat/5.0/configuration-output-ssl.html
7. https://www.elastic.co/guide/en/beats/winlogbeat/5.0/configuring-ssl-logstash.html
8. https://www.elastic.co/guide/en/beats/winlogbeat/5.0/configuration-output-ssl.html

**Comment by dedemorton** [comment]
**Redirects for #2330 to set up for GA:**

_OLD URLs:_

1. https://www.elastic.co/guide/en/beats/packetbeat/current/configuring-tls-logstash.html
2. https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-output-tls.html
3. https://www.elastic.co/guide/en/beats/filebeat/current/configuring-tls-logstash.html
4. https://www.elastic.co/guide/en/beats/filebeat/current/configuration-output-tls.html
5. https://www.elastic.co/guide/en/beats/metricbeat/current/configuring-tls-logstash.html
6. https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-output-tls.html
7. https://www.elastic.co/guide/en/beats/winlogbeat/current/configuring-tls-logstash.html
8. https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-output-tls.html

_NEW URLs:_

1. https://www.elastic.co/guide/en/beats/packetbeat/current/configuring-ssl-logstash.html
2. https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-output-ssl.html
3. https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ssl-logstash.html
4. https://www.elastic.co/guide/en/beats/filebeat/current/configuration-output-ssl.html
5. https://www.elastic.co/guide/en/beats/metricbeat/current/configuring-ssl-logstash.html
6. https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-output-ssl.html
7. https://www.elastic.co/guide/en/beats/winlogbeat/current/configuring-ssl-logstash.html
8. https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-output-ssl.html

**Comment by dedemorton** [comment]
For the 5.0 GA, how do we want to handle the Topbeat URLs in current? Since Topbeat will no longer exist, any links to it in current will break at GA. Should we redirect to 1.3?

**Comment by dedemorton** [comment]
**Redirects for removal of the shipper section. Set up for GA.**

Changes "configuration-shipper.html" to "configuration-general.html"

_OLD URLs:_

https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-shipper.html
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-shipper.html
https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-shipper.html
https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-shipper.html

_NEW URLs:_

https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-general.html
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-general.html
https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-general.html
https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-general.html

**Comment by dedemorton** [comment]
Closing in favor of tracking this issue in https://github.com/elastic/beats/issues/2482

**Comment by dedemorton** [comment]
**Redirects for #2505 (removal of dashboard content from Platform Ref). Set up now.**

Can't really point users to the various Ref Guides, so I will set up the redirect to point to the topic in the Dev Guide about importing dashboards. Not ideal, but probably better than a dead link.

_OLD URLs_

https://www.elastic.co/guide/en/beats/libbeat/5.0/visualizing-data.html
https://www.elastic.co/guide/en/beats/libbeat/5.0/load-kibana-dashboards.html

_NEW URLs_
both links should redirect to: 
https://www.elastic.co/guide/en/beats/libbeat/5.0/import-dashboards.html

**Comment by dedemorton** [comment]
**Redirects for #2505 (removal of dashboard content from Platform Ref). Set up for GA.**

Can't really point users to the various Ref Guides, so I will set up the redirect to point to the topic in the Dev Guide about importing dashboards. Not ideal, but probably better than a dead link.

_OLD URLs_

https://www.elastic.co/guide/en/beats/libbeat/current/visualizing-data.html
https://www.elastic.co/guide/en/beats/libbeat/current/dashboard-load-options.html
https://www.elastic.co/guide/en/beats/libbeat/current/view-kibana-dashboards.html

_NEW URLs_
all three links should redirect to: 
https://www.elastic.co/guide/en/beats/libbeat/current/import-dashboards.html

**Comment by dedemorton** [comment]
**Filebeat redirects resulting from edits and content restructuring. To set up now.**

_OLD URLS_

1. https://www.elastic.co/guide/en/beats/filebeat/5.0/_how_filebeat_works.html
2. https://www.elastic.co/guide/en/beats/filebeat/5.0/_getting_help.html
3. https://www.elastic.co/guide/en/beats/filebeat/5.0/_reduce_open_file_handlers.html
4. https://www.elastic.co/guide/en/beats/filebeat/5.0/reduce-registry-size.html
5. https://www.elastic.co/guide/en/beats/filebeat/5.0/inode-reuse-issue.html
6. https://www.elastic.co/guide/en/beats/filebeat/5.0/windows-file-rotation.html
7. https://www.elastic.co/guide/en/beats/filebeat/5.0/_migrating_to_the_beats_input_plugin_for_logstash.html
8. https://www.elastic.co/guide/en/beats/filebeat/5.0/_updating_the_registry_file.html
9. https://www.elastic.co/guide/en/beats/filebeat/5.0/_migrating_your_configuration.html
10. https://www.elastic.co/guide/en/beats/filebeat/5.0/_changes_to_command_line_options.html
11. https://www.elastic.co/guide/en/beats/filebeat/5.0/_changes_to_the_output_fields.html
12. https://www.elastic.co/guide/en/beats/filebeat/5.0/_other_changes.html
13. https://www.elastic.co/guide/en/beats/filebeat/5.0/_step_5_starting_filebeat.html
14. https://www.elastic.co/guide/en/beats/filebeat/5.0/_step_6_loading_the_kibana_index_pattern.html 

_NEW URLS_

1. https://www.elastic.co/guide/en/beats/filebeat/5.0/how-filebeat-works.html
2. https://www.elastic.co/guide/en/beats/filebeat/5.0/getting-help.html
3. https://www.elastic.co/guide/en/beats/filebeat/5.0/faq.html
4. https://www.elastic.co/guide/en/beats/filebeat/5.0/faq.html
5. https://www.elastic.co/guide/en/beats/filebeat/5.0/faq.html
6. https://www.elastic.co/guide/en/beats/filebeat/5.0/faq.html
7. https://www.elastic.co/guide/en/beats/filebeat/5.0/migration-input-plugin.html
8. https://www.elastic.co/guide/en/beats/filebeat/5.0/migration-registry-file.html
9. https://www.elastic.co/guide/en/beats/filebeat/5.0/migration-configuration.html
10. https://www.elastic.co/guide/en/beats/filebeat/5.0/migration-changed-cli.html
11. https://www.elastic.co/guide/en/beats/filebeat/5.0/migration-changed-fields.html
12. https://www.elastic.co/guide/en/beats/filebeat/5.0/migration-other-changes.html
13. https://www.elastic.co/guide/en/beats/filebeat/5.0/filebeat-starting.html
14. https://www.elastic.co/guide/en/beats/filebeat/5.0/filebeat-index-pattern.html

**Comment by dedemorton** [comment]
**Filebeat redirects resulting from edits and content restructuring. To set up for GA.**

_OLD URLS_

1. https://www.elastic.co/guide/en/beats/filebeat/current/_how_filebeat_works.html
2. https://www.elastic.co/guide/en/beats/filebeat/current/_getting_help.html
3. https://www.elastic.co/guide/en/beats/filebeat/current/_migrating_to_the_beats_input_plugin_for_logstash.html
4. https://www.elastic.co/guide/en/beats/filebeat/current/_updating_the_registry_file.html
5. https://www.elastic.co/guide/en/beats/filebeat/current/_migrating_your_configuration.html
6. https://www.elastic.co/guide/en/beats/filebeat/current/_changes_to_command_line_options.html
7. https://www.elastic.co/guide/en/beats/filebeat/current/_changes_to_the_output_fields.html
8. https://www.elastic.co/guide/en/beats/filebeat/current/_other_changes.html
9. https://www.elastic.co/guide/en/beats/filebeat/current/_step_5_starting_filebeat.html
10. https://www.elastic.co/guide/en/beats/filebeat/current/_step_6_loading_the_kibana_index_pattern.html 

_NEW URLS_

1. https://www.elastic.co/guide/en/beats/filebeat/current/how-filebeat-works.html
2. https://www.elastic.co/guide/en/beats/filebeat/current/getting-help.html
3. https://www.elastic.co/guide/en/beats/filebeat/current/migration-input-plugin.html
4. https://www.elastic.co/guide/en/beats/filebeat/current/migration-registry-file.html
5. https://www.elastic.co/guide/en/beats/filebeat/current/migration-configuration.html
6. https://www.elastic.co/guide/en/beats/filebeat/current/migration-changed-cli.html
7. https://www.elastic.co/guide/en/beats/filebeat/current/migration-changed-fields.html
8. https://www.elastic.co/guide/en/beats/filebeat/current/migration-other-changes.html
9. https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-starting.html
10. https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-index-pattern.html

**Comment by dedemorton** [comment]
**Packet redirects resulting from edits and content restructuring. To set up now.**

_OLD URLS_

1. https://www.elastic.co/guide/en/beats/packetbeat/5.0/_step_4_starting_packetbeat.html 
2. https://www.elastic.co/guide/en/beats/packetbeat/5.0/_kibana_queries_and_filters.html
3. https://www.elastic.co/guide/en/beats/packetbeat/5.0/_getting_help.html
4. https://www.elastic.co/guide/en/beats/packetbeat/5.0/_recording_a_trace.html
5. https://www.elastic.co/guide/en/beats/packetbeat/5.0/_step_5_loading_sample_kibana_dashboards.html

NEW URLS

1. https://www.elastic.co/guide/en/beats/packetbeat/5.0/packetbeat-starting.html
2. https://www.elastic.co/guide/en/beats/packetbeat/5.0/kibana-queries-filters.html
3. https://www.elastic.co/guide/en/beats/packetbeat/5.0/getting-help.html
4. https://www.elastic.co/guide/en/beats/packetbeat/5.0/recording-trace.html
5. https://www.elastic.co/guide/en/beats/packetbeat/5.0/packetbeat-sample-dashboards.html

**Comment by dedemorton** [comment]
**Packet redirects resulting from edits and content restructuring. To set up for GA.**

_OLD URLS_

1. https://www.elastic.co/guide/en/beats/packetbeat/current/_step_4_starting_packetbeat.html
2. https://www.elastic.co/guide/en/beats/packetbeat/current/_kibana_queries_and_filters.html
3. https://www.elastic.co/guide/en/beats/packetbeat/current/_getting_help.html
4. https://www.elastic.co/guide/en/beats/packetbeat/current/_recording_a_trace.html
5. https://www.elastic.co/guide/en/beats/packetbeat/current/_step_5_loading_sample_kibana_dashboards.html

_NEW URLS_

1. https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-starting.html
2. https://www.elastic.co/guide/en/beats/packetbeat/current/kibana-queries-filters.html
3. https://www.elastic.co/guide/en/beats/packetbeat/current/getting-help.html
4. https://www.elastic.co/guide/en/beats/packetbeat/current/recording-trace.html
5. https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-sample-dashboards.html

**Comment by dedemorton** [comment]
**Winlogbeat redirects resulting from edits and content restructuring. To set up now.**

_OLD URLS_

1. https://www.elastic.co/guide/en/beats/winlogbeat/5.0/_step_5_starting_winlogbeat.html
2. https://www.elastic.co/guide/en/beats/winlogbeat/5.0/_step_6_loading_sample_kibana_dashboards.html
3. https://www.elastic.co/guide/en/beats/winlogbeat/5.0/_getting_help.html

_NEW URLS_

1. https://www.elastic.co/guide/en/beats/winlogbeat/5.0/winlogbeat-starting.html 
2. https://www.elastic.co/guide/en/beats/winlogbeat/5.0/winlogbeat-sample-dashboards.html
3. https://www.elastic.co/guide/en/beats/winlogbeat/5.0/getting-help.html

**Comment by dedemorton** [comment]
**Winlogbeat redirects resulting from edits and content restructuring. To set up for GA.**

_OLD URLS_

1. https://www.elastic.co/guide/en/beats/winlogbeat/current/_step_5_starting_winlogbeat.html
2. https://www.elastic.co/guide/en/beats/winlogbeat/current/_step_6_loading_sample_kibana_dashboards.html
3. https://www.elastic.co/guide/en/beats/winlogbeat/current/_getting_help.html

_NEW URLS_

1. https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-starting.html 
2. https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-sample-dashboards.html
3. https://www.elastic.co/guide/en/beats/winlogbeat/current/getting-help.html

**Comment by dedemorton** [comment]
Metricbeat redirects resulting from edits and content restructuring. The current and 5.0 redirects can be set up now because 5.0 is the first release of metricbeat.

_OLD URLS (in current)_

1. https://www.elastic.co/guide/en/beats/metricbeat/current/_overview.html
2. https://www.elastic.co/guide/en/beats/metricbeat/current/_step_4_starting_metricbeat.html
3. https://www.elastic.co/guide/en/beats/metricbeat/current/getting-support.html
4. https://www.elastic.co/guide/en/beats/metricbeat/current/_running_metricbeat_in_a_container.html
5. https://www.elastic.co/guide/en/beats/metricbeat/current/_monitoring_the_host_machine.html
6. https://www.elastic.co/guide/en/beats/metricbeat/current/_monitoring_a_service_in_another_container.html

_NEW URLS (in current)_

1. https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-dev-overview.html
2. https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-starting.html
3. https://www.elastic.co/guide/en/beats/metricbeat/current/getting-help.html
4 https://www.elastic.co/guide/en/beats/metricbeat/current/running-in-container.html 
5. https://www.elastic.co/guide/en/beats/metricbeat/current/running-in-container.html 
6. https://www.elastic.co/guide/en/beats/metricbeat/current/running-in-container.html 

_OLD URLS (in 5.0)_

1. https://www.elastic.co/guide/en/beats/metricbeat/5.0/_overview.html
2. https://www.elastic.co/guide/en/beats/metricbeat/5.0/_step_4_starting_metricbeat.html
3. https://www.elastic.co/guide/en/beats/metricbeat/5.0/getting-support.html
4. https://www.elastic.co/guide/en/beats/metricbeat/5.0/_running_metricbeat_in_a_container.html
5. https://www.elastic.co/guide/en/beats/metricbeat/5.0/_monitoring_the_host_machine.html
6. https://www.elastic.co/guide/en/beats/metricbeat/5.0/_monitoring_a_service_in_another_container.html

_NEW URLS (in 5.0)_

1. https://www.elastic.co/guide/en/beats/metricbeat/5.0/metricbeat-dev-overview.html
2. https://www.elastic.co/guide/en/beats/metricbeat/5.0/metricbeat-starting.html
3. https://www.elastic.co/guide/en/beats/metricbeat/5.0/getting-help.html
4. https://www.elastic.co/guide/en/beats/metricbeat/5.0/running-in-container.html 
5. https://www.elastic.co/guide/en/beats/metricbeat/5.0/running-in-container.html 
6. https://www.elastic.co/guide/en/beats/metricbeat/5.0/running-in-container.html

**Comment by dedemorton** [comment]
**Redirects for changes to Developer Guide for creating new beats. To set up now.**

Note that redirecting to the files in master is intentional.

_OLD URLS_

https://www.elastic.co/guide/en/beats/libbeat/current/_overview.html
https://www.elastic.co/guide/en/beats/libbeat/current/_sharing_your_beat_with_the_community.html


_NEW URLS_

https://www.elastic.co/guide/en/beats/libbeat/master/newbeat-overview.html
https://www.elastic.co/guide/en/beats/libbeat/master/newbeat-sharing.html

**Comment by dedemorton** [comment]
Created the following request with the web team to set up the redirects after 5.0 goes live:  https://github.com/elastic/website-www.elastic.co/issues/1284
