### ISSUE TITLE
Beats doc updates

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#2482]
This is a meta issue to track Beats documentation work for 5.0.0. This issue was created towards the end of the 5.0.0 release, so it doesn't include all the changes made to the doc during the alpha  releases.

If you have trouble clicking an item in the checklist to mark it as complete, open this comment in edit mode and change the source to `[x]`. Seems to be a bug in ticking the check boxes in this issue.

**5.0 GA:**
- [x] Resolve any [doc issues flagged for 5.0.0-GA](https://github.com/elastic/beats/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Av5.0.0-GA%20label%3Adocs). Some of the open doc issues are duplicated in this list. 
- [x] [DeDe] Document how to configure ingest node to have GeoIP info. See https://github.com/elastic/beats/issues/1671
- [x] Update Developer Guide. See https://github.com/elastic/beats/issues/1077 
- [x] Create migration guide for 2.x to 5.x. See https://github.com/elastic/beats/issues/1488 
- [x] [DeDe ] Document load-balancing modes in Filebeat. See https://github.com/elastic/beats/issues/1852
- [x] [DeDe] Submit request to get redirects set up. See https://github.com/elastic/beats/issues/2426
- [x] [DeDe] Add doc example that shows how to configure the Kafka output. See https://github.com/elastic/beats/issues/1339 
- [x] [DeDe] Update links to shield documentation for 5.0. See https://github.com/elastic/beats/issues/1308
- [x] Edit Breaking changes and Upgrading doc (see #2631)
- [x] [DeDe] Required cleanup:
  - [x] Remove any known issue notes that are specific to the alpha or beta releases. 
  - [x] Remove any coming, added, or deprecated tags that are relevant to alpha and beta only (keep deprecation tags that mark items deprecated between 2.4 and 5.0).
  - [x] Clean up config sections that were added to support changes between alpha4 and alpha5.
- [x] Make a doc page that explains all the Breaking Changes
- [x] Add label to indicate that doc about adding a new protocol is out-of date. Include a link to the protocol analyzer generator. 
- [x] [DeDe] Improve diagrams:
  - [x] Improve conceptual diagram of Filebeat (see https://github.com/elastic/beats/issues/713).
  - [x] Improve diagram in the overview to the Platform Reference (use new icons and logos).
  - [x] Add diagram to metricbeat docs under "How Metricbeat Works" to show a couple of modules and metricsets within those modules
- [x] Clarify docs about supported Filepath glob patterns. See https://github.com/elastic/beats/issues/2108

**5.0 Beta 1:**
- [x] Resolve any [doc issues flagged for 5.0.0-beta 1](https://github.com/elastic/beats/issues?q=is%3Aissue+label%3Av5.0.0-beta1+label%3Adocs+is%3Aopen). Some of the open doc issues are duplicated in this list. 
- [x] Lots of other work that DeDe completed before she created this meta issue. :-)
- [x] [Tudor] Document new repositories (add info about yum/apt repos). See https://github.com/elastic/beats/issues/2467 (fixed in https://github.com/elastic/beats/pull/2617)
- [x] [Tudor/DeDe] Document output supported versions. See https://github.com/elastic/beats/issues/1450
- [x] [Steffen] Update docs for index changes (add index pattern, rename index options). See https://github.com/elastic/beats/issues/2074
- [x] [DeDe] Update screen captures.
- [x] [DeDe] Misc content changes: 
  - [x] Remove restriction about intermediate CAs from the doc?
  - [x] Clarify description of paths option. See https://github.com/elastic/beats/issues/2193
  - [x] Document why field names under event_data might be unnamed. See https://github.com/elastic/beats/issues/2192
  - [x] Explain difference between short and long config files. See https://github.com/elastic/beats/issues/1844
  - [x] Clearly document for Kibana users that a fresh index is required after loading custom structured logs. 
  - [x] Document -E flag?
- [x] [DeDe] Misc editorial changes:
  - [x] Add content about loading each dashboard to the docs for each beat. See https://github.com/elastic/beats/issues/1943 
  - [x] Remove comments from example configs in ref guides See https://github.com/elastic/beats/issues/1795
  - [x] Make sure container topics contain sufficient content. See https://github.com/elastic/beats/issues/1793
  - [x] Use proper experimental flag here: https://www.elastic.co/guide/en/beats/filebeat/master/configuration-filebeat-options.html#_harvester_limit 
  - [x] Fix link text here to match heading: https://www.elastic.co/guide/en/beats/libbeat/master/event-conventions.html 
- [x] [DeDe] New or changed doc that requires an edit:
  - [x] How filebeat works content (includes some topics that got into the troubleshooting section)
  - [x] close_file options
  - [x] Importing dashboards
  - [x] Filebeat config options
  - [x] Parsing and normalizing fields
  - [x] Running Metricbeat in a container
- [x] [DeDe] Required cleanup:
  - [x] Remove alpha-specific notes about restrictions and changes.
  - [x] When ES branches to 5.0, need to change variable to point to the doc-branch rather than hard-coding it as master. Basically need to reverse this: https://github.com/elastic/beats/commit/a3560058ff62f72bece457fae15d5a09fbb3322d

**Comment by dedemorton** [comment]
Moved remaining issues and wish list to #3019 to track them for 5.1.0.
