### ISSUE TITLE
HAProxy Module improvements

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#2485]
- [x] Run `make collect` to make sure all files are up-to-date https://github.com/elastic/beats/pull/2486
- [x] Add tests to generate `data.json` files https://github.com/elastic/beats/pull/2720
- [x] Check that config files are according to standard (experimental disabled by default) https://github.com/elastic/beats/pull/2486
  - See also https://github.com/elastic/beats/pull/2384/files#r76591317
- [x] Review all haproxy fields for the naming convention
- [x] Add CHANGELOG update https://github.com/elastic/beats/pull/2486
- [x] Improve source in docs: https://github.com/elastic/beats/pull/2486/files#r77964060 https://github.com/elastic/beats/pull/2929
- [ ] (The addresses specified in the configuration should be validated when the MetricSet is constructed. This allows `-configtest` to catch invalid URLs.)
- [x] There are numerous errors being logged by the info MetricSet. Each individual value from the CSV is a string. Some of the strings are empty. When running the schema.Apply() an error happens because it's trying to convert an empty string to a int. If the `haproxy.Stat` fields were typed properly I think this would address the problem. #2485
- [x] Document the supported version. https://github.com/elastic/beats/pull/2929
- [ ] Add a sample dashboard.

**Comment by andrewkroh** [comment]
[ ] - The addresses specified in the configuration should be validated when the MetricSet is constructed. This allows `-configtest` to catch invalid URLs.

**Comment by ruflin** [comment]
@andrewkroh I took your TODO's and also put them on the top so we have all in one place.

**Comment by hartfordfive** [comment]
@andrewkroh Regarding most of the errors regarding the HAProxy fields, I believe it's because some of the fields aren't present in each `stat` entry.  How do you guys deal with fields that may not always have a value like in this case?  That way I can keep that in mind for the next time I create a module.

**Comment by ruflin** [comment]
@hartfordfive For the fields that are optional, you can use the `Optional` flag. See for example here in apache status metricset: https://github.com/elastic/beats/blob/master/metricbeat/module/apache/status/data.go#L23

**Comment by ruflin** [comment]
@hartfordfive I did a first step of the cleanup here including making some fields optional: https://github.com/elastic/beats/pull/2720

**Comment by andrewkroh** [comment]
The titles are duplicated:
![screen shot 2016-11-02 at 3 59 29 pm](https://cloud.githubusercontent.com/assets/4565752/19945188/64d12fce-a115-11e6-93ca-d86131f5e18a.png)

And the description for the stat metricset says: "This is the info metricset of the module haproxy."

**Comment by Chadwiki** [comment]
^ I noticed this on the bottom nav.

**Comment by ruflin** [comment]
@andrewkroh @Chadwiki I addressed this in https://github.com/elastic/beats/pull/2929

**Comment by hartfordfive** [comment]
@ruflin Thanks for making those changes.  I haven't had much time to work on the haproxy or php-fpm module since my last commit.  Hopefully I'll be able to continue working on the php-fpm module soon.

**Comment by ruflin** [comment]
@hartfordfive No worries. Looking forward to your future contributions.

**Comment by ruflin** [comment]
I think we are now mostly done with the cleanup. Only open point is creating dashboards and I kind of assuming during creating dashboards we will find some issues in the fields. @monicasarbu Interested to do the dashboards? ;-)

**Comment by ruflin** [comment]
Closing this even though we don't have the dashboards yet.
