### ISSUE TITLE
Add support for Elastic logging plugin on ARM

### ISSUE THREAD

**Issue by kvch** [elastic/beats#26108]
The goal of this issue is to track the progress of the Elastic logging plugin on ARM. It is a Docker plugin, not an image, thus, I separated it from the original issue: https://github.com/elastic/beats/issues/18334

### Tasks
- [x] packaging from the repository using `mage package`
- [ ] prepare the release manager and Docker registry for deploying ARM-based plugins
- [ ] integrate the artifact into the release process

### How to build the plugin for now?

If someone wants to build the artifact for themselves, they can do it by following these steps:

0. Make sure you are using an ARM-based host
1. Clone the beats repository
2. Run `TYPE=docker PLATFORMS=linux/arm64 mage package` under `x-pack/dockerlogbeat`

The new artifact will be found under `x-pack/dockerlogbeat/build/distributions`.
