### ISSUE TITLE
Adopt `parsers` in all Filebeat inputs

### ISSUE THREAD

**Issue by kvch** [elastic/beats#26130]
### Goal

[Parsers](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html#_parsers) are the successors of readers of the `log` input. They provide a more flexible message parsing. At the moment they are only available in the `filestream` input. But the functionality could be useful in other inputs.

We have to inspect all available inputs in Filebeat to see if it makes sense to add `parsers`. If the answer is yes, then the feature should be added.

#### Parsers
- [x] ndjson
- [x] multiline
- [x] container #26115
- [x] syslog #30541

#### 1. Add parsers code to the input

The `parser.Config` object has its own `Unpack` function, so it is enough for you to add it as an attribute to your configuration.

```golang
type myInputConfiguration struct {
   // other attributes
    parsers parser.Config `config:",inline"`
}
```

Then create the parser based on the configuration. The `Create` function expects a `reader.Reader` as a parameter it can read from.

```golang
var reader reader.Reader
p = inp.config.parsers.Create(reader)
```

Example configuration accepted by the code above

```yaml
parsers:
  - multiline:
      type: count
      lines_count: 3
```

#### 2. Add `parsers` to the reference configuration

Add the reference configuration to either
* `filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl`
* `x-pack/filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl`

#### 3. Add `parsers` to the documentation of the input

There is no common parsers section at the moment because it might not make sense to document all parsers for every input.

### Inputs
- [ ] AWS CloudWatch https://github.com/elastic/beats/issues/26429
- [x] AWS S3 https://github.com/elastic/beats/pull/25873
- [ ] Azure Event Hub
- [ ] Cloud Foundry
~~- [ ] Container~~ must use filestream input in the future
~~- [ ] Docker~~ must use filestream input in the future
- [x] filestream
- [ ] GCP Pub/Sub
- [ ] HTTP Endpoint
- [ ] HTTP JSON
- [x] journald
- [x] Kafka https://github.com/elastic/beats/pull/27335
~~- [ ] Log~~ must use filestream input in the future
- [ ] MQTT
- [ ] NetFlow
- [ ] Office 365 Management Activity API
- [ ] Redis
~~- [ ] Stdin~~ will be deprecated
~~- [ ] Syslog~~ syslog will be a parser
- [x] #31023
- [x] #31024
- [ ] Unix https://github.com/elastic/beats/pull/27858

**Comment by ascendant512** [comment]
May I vote for multiline in the unix input? It is the closest thing Filebeat has to a fifo.  Immensely useful for injecting arbitrary logs with netcat without messing with log directories or restarting Filebeat.

**Comment by jlind23** [comment]
@kvch @nimarezainia what are the missing ones on which we should work?
I'll plan them as soon as possible like in 8.2 to clean it up.

**Comment by kvch** [comment]
Ideally, all of them. But TCP, UDP, UNIX should be done by our team. For the other inputs, I have to track down others to see if it makes sense to add parsers, and bug them to add if necessary.

**Comment by jlind23** [comment]
@kvch @cmacknz will it be reworked with the input manager changes ongoing? If yes, I would rather postponing it for now. Thoughts?

**Comment by jlind23** [comment]
Those are the missing inputs where there is no parsers so far.
- [ ] AWS CloudWatch https://github.com/elastic/beats/issues/26429
- [ ] Azure Event Hub
- [ ] Cloud Foundry
- [ ] GCP Pub/Sub
@masci those ones seems to belong to the @elastic/obs-cloud-monitoring team. Could you please create the appropriate issues if it's relevant?

- [ ] HTTP Endpoint
- [ ] HTTP JSON
- [ ] Office 365 Management Activity API
@elastic/security-external-integrations those ones seems to belong to your area, could you please create the appropriate issues and check them if it is not needed.

- [ ] MQTT
- [ ] NetFlow
- [ ] Redis
@rameshelastic those ones belongs to the @elastic/obs-service-integrations team, could you take them on your behalf.

- [ ] TCP #31023 
- [ ] UDP #31024 
- [ ] Unix https://github.com/elastic/beats/pull/27858

**Comment by jlind23** [comment]
Those are the missing inputs where there is no parsers so far.

- [ ] AWS CloudWatch https://github.com/elastic/beats/issues/26429
- [ ] Azure Event Hub
- [ ] Cloud Foundry
- [ ] GCP Pub/Sub


@masci those ones seems to belong to the @elastic/obs-cloud-monitoring team. Could you please create the appropriate issues if it's relevant?

- [ ] HTTP Endpoint
- [ ] HTTP JSON
- [ ] Office 365 Management Activity API

@elastic/security-external-integrations those ones seems to belong to your area, could you please create the appropriate issues and check them if it is not needed.

- [ ] MQTT
- [ ] NetFlow
- [ ] Redis

@rameshelastic those ones belongs to the @elastic/obs-service-integrations team, could you take them on your behalf.

- [ ] TCP #31023 
- [ ] UDP #31024 
- [ ] Unix https://github.com/elastic/beats/pull/27858

**Comment by nimarezainia** [comment]
@kvch @jlind23 sorry catching this thread a bit late. Isn't filestream and enhancement and ultimately replacing log input? should we be making these changes if they are already available in filestream?
