### ISSUE TITLE
[Meta] [Fleet] [Agent] [Test]: Ephemeral Elastic Agents

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#26312]
Meta issue for the Concept of ephemeral Agents.

We have logged this ticket to keep all the changes related to ephemeral Agents on cloud centralized in a list.

**Comment by EricDavisX** [comment]
I sent an email to confirm, and hope to find that we have already covered this and the specs for it are quite simple - we can follow up in another day or so with more info async

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have gone through the shared email threads and posted related queries on ticket https://github.com/elastic/elasticsearch/pull/74180. 

Please let us know if we are missed anything.

**Comment by EricDavisX** [comment]
The design doc for this was pointed to as the source for info, so I am copying out the scenarios we want to support here:

There may be more elsewhere, but confirmed in scope for 7.14 are:
- [ ] 1 An Elastic Cloud operator configures and runs hosted Elastic Agents inside containers.
- [ ] 2 An integrations user configures and runs Elastic Agents in Docker containers without persistent volumes.
- [ ] 3 An integrations user configures and runs Elastic Agents in Kubernetes pods without persistent volumes.
- [ ] 4 A platform operator configures and runs Elastic Agents inside non-persistent virtual desktop images.
- [ ] 5 A Fleet user troubleshoots a problem by analyzing the logs and metrics of active and inactive agents.
- [ ] 6 A Fleet user sees that all the offline 7.13 Elastic Cloud agents are unenrolled after upgrading to 7.14.
- [ ] 7 An integrations user wants to resume sending data after a temporary network disruption or container stop, even after the TTL, as long as the data is still available on the host to minimize data loss and duplication.
- [ ] 8 A managed service provider offers logging as a service to its clients, who configure and run Elastic Agents.

We can check mark them off when they are manually tested, or confirmed as being covered in automation or other routine test environment usage (like elastic-package or Observability test clusters).  If they are NOT manually tested, please make a note as to which automation ci or test system covers it!  

Separately here are the 3 noted 'user journeys' with some details that we can confirm, please check them off also after manual testing or after / when we have confirmation that they are covered under automation or routine test environment usage.

User Journeys
- [ ] **Scenario (1) End user laptop goes offline**
 - The end user’s laptop has the agent installed with logs being sent to ES
 - This user goes on an extended leave, laptop is turned off and their agent is no longer Checking-in 
 - The Fleet Administrator, who set the policy never changed the “Unenroll Timeout” field - set to the default value of ZERO (i.e. never)
 - This agent will eventually go offline (refer to state diagram)
 - The agent stays in this state until a checkin arrives for that same agent-id
 - Sometime later when the laptop is active again, it sends a checkin (not a new enrollment)
 - The agent is then moved from “Offline” to “Healthy” and receives updates if needed.
 - The agent-id and logs are preserved 

- [ ] **Scenario (2) Container with Elastic-Agent is deleted**
 - For set of endpoints that are ephemeral in nature the “Unenroll Timeout” can be set by the Fleet Administrator, and as a policy applied to all the agents with that policy
 - - A separate policy may be created to group these types of agents together and keep them separate from laptops, baremetal, VMs etc
 - The user kills the container with their application within, therefore deleting the agent.
 - The agent will go into an “Offline” mode
 - Unenroll Timeout expires for this agent (no checkins received for the timeout period)
 - This will prompt a force unenroll, remove the API keys and move the agent to an “Inactive” state.
 - Logs stored in Elasticsearch are preserved for that agent-id, but logs stored on the container are lost

- [ ] **Scenario (3) Elastic-Agent in Cloud resized/moved/deleted**
 - Post 7.13 fleet-server (and APM-server) are hosted in Elastic Cloud this is done with an Elastic-Agent running in a container
 - Life-cycle management of the cloud would mean that this particular container may be stopped, started, moved or resized - some of which may be disruptive.
 - Elastic Cloud Agent Policy is the policy applied to this special agent and has a nominal “Unenroll Timeout” configured (the policy is not configurable by the end user/customer)
 - This special container may be destroyed from time to time during the course of its life by Elastic SRE/Cloud operations
 - - Similar to Scenario (2) above the Unenroll Timeout will expire and force the agent to transition to the “Inactive” state 
 - - Logs stored in Elasticsearch are preserved for that agent-id, but logs stored in the container are lost.
 - This special container may be stopped and restarted during the course of its life by Elastic SRE/Cloud operations
 - - In this scenario the filesystem contents are preserved. The agent gets a new agent ID when it reenrolls. Both the logs in Elasticsearch and the logs stored in the container are preserved.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have checked out 02 scenarios as per covered under testing at our end. 

Just for update: Further, we can try for one -two scenarios more and will update checkboxes accordingly after validating them.

Thanks
QAS

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have tested scenarios mentioned at point 6 and 7 and below are our observations:

- Point 6
> A Fleet user sees that all the offline 7.13 Elastic Cloud agents are unenrolled after upgrading to 7.14.

**_Steps followed:_**

1. Deploy kibana production 7.13.4 .
2. Install Agent version 7.13.4.
3. Upgrade the Kibana to 7.14.0 version.
4. Provide the Unenrollment timeout to 240 under policy setting and save it.
5. stop the service of agent and agent goes to offline state.
6. Wait for 4 minutes and observed that Agent goes to Inactive state.
Observations:
It is working fine, 7.13 agent gets auto-unenrolled on upgraded 7.14 kibana when endpoint gets offline and TTL is set.

- Point 7
> An integrations user wants to resume sending data after a temporary network disruption or container stop, even after the TTL, as long as the data is still available on the host to minimize data loss and duplication.

**_Steps followed:_**

1. Installed agent with Default Policy having Unenrollment timeout: 180 seconds.
2. Turned agent offline and wait for it to show offline on Kibana UI
3. Disconnected system from internet. After 180 seconds restarted internet.

Observations:

- Agent is unenrolled from kibana UI and is in inactive state.

Build details:
BUILD 42747
COMMIT f032cf9bdbf6f74b70db5e43b7b1d30f5de22d3e
artifact used: https://staging.elastic.co/7.14.0-8b7f437c/downloads/beats/elastic-agent/elastic-agent-7.14.0-windows-x86_64.zip


Thanks
QAS

**Comment by pc-mrousseau** [comment]
As a quick FYI - the 'timeout' approach has some drawbacks as well. If the timeout is too short, it might result in false positives due to network weather. If the timeout is too long, depending on the change velocity of the environment we can have a higher % of lingering "zombies". 

In many other similar platforms there are available APIs to pro-actively unenroll endpoints at the orchestration level. Given how rich the Elastic platform is overall for APIs, it's somewhat surprising and disappointing that there are almost no Fleet APIs. Having `/fleet/agent/unenroll?id=abcd` would be really neat.

**Comment by ruflin** [comment]
Commenting on the API part: There is a full Fleet API and everything you can do in the UI can be done view API. What we need to work on are the docs: https://www.elastic.co/guide/en/elasticsearch/reference/7.x//fleet-apis.html Here you can find the openapi definition for it: https://raw.githubusercontent.com/elastic/kibana/7.x/x-pack/plugins/fleet/common/openapi/bundled.yaml And the unenroll API you are looking for is also in there.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
>4 A platform operator configures and runs Elastic Agents inside non-persistent virtual desktop images.

We have attempted to test this on 7.14.1 released build using Linux ARM64 docker image.
We have set unenrollment timeout: 60 seconds. After 60 seconds of disconnecting agent  it moved to inactive state.

Please let us know if anything else is required.
Thanks

**Comment by EricDavisX** [comment]
Thanks Amol, that's great news.  The Endpoint team is finishing up some testing and we'll look to close this out.

**Comment by EricDavisX** [comment]
we can close this out now, testing is done on all teams as I know it.
