### ISSUE TITLE
[Elastic Agent] Improve Elastic Agent debuggability

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#26930]
The Elastic Agent is a supervisor which runs sub processes. This combination of multiple process and dependency on Fleet makes debugging the Elastic Agent sometimes tricky. One part is for users to provide the necessary and the other is for engineers to reproduce and understand the issue. Just on example can be found here: https://github.com/elastic/beats/issues/26213

Improving this consists of many different parts. This issue is to link together this overall effort.

Related issues (incomplete list):

### High Prio

- [x] elastic/elastic-agent#154
- [x] https://github.com/elastic/beats/issues/21413
- [x] elastic/elastic-agent#101
- [x] elastic/elastic-agent#100
- [x] https://github.com/elastic/fleet-server/issues/1128
- [ ] https://github.com/elastic/enhancements/issues/14587
- [x] elastic/elastic-agent#105
- [x] https://github.com/elastic/fleet-server/pull/992
- [ ] 
- [x] https://github.com/elastic/sdh-beats/issues/1569  (modifications to the download timeout and extra logging for progression of download)
- [x] https://github.com/elastic/beats/issues/29898
- [x] elastic/elastic-agent#104
- [x] elastic/elastic-agent#88
- [x] Correctly aggregates the health status of the running process, a problem with a sub process should impact the agent status. https://github.com/elastic/kibana/issues/78188 
elastic/elastic-agent#79

### Medium Prio

- [ ] elastic/elastic-agent#115
- [ ] Display the amount of memory/cpu in use by the agent, including cgroup metrics(a snapshot. are there other useful metrics?)
- [x] https://github.com/elastic/beats/issues/27764
- [x] https://github.com/elastic/beats/issues/28334
- [ ] elastic/elastic-agent#117
- [x] elastic/elastic-agent#99
- [x] elastic/elastic-agent#114
- [x] elastic/elastic-agent#92

### Low Prio

- [ ] Display how much data is pooled to disk
- [x] elastic/elastic-agent#154
- [x] https://github.com/elastic/enhancements/issues/13780
- [x] elastic/elastic-agent#103

-----------------------------------------------------
- [x]  https://github.com/elastic/beats/issues/25449
- [x] * https://github.com/elastic/beats/issues/25230
- [x] * https://github.com/elastic/beats/issues/27059
- [x] * https://github.com/elastic/beats/issues/27138
- [x] https://github.com/elastic/beats/pull/28798
https://github.com/elastic/kibana/issues/78188√https://github.com/elastic/kibana/issues/78188

**Comment by jlind23** [comment]
@nimarezainia this issue: https://github.com/elastic/beats/issues/29407
Is becoming pretty urgent as a lot of users were experiencing issue while downloading our binary. I would be happy to treat it as an high priority.

**Comment by jlind23** [comment]
Transferring here Marcin comment from another issue related to this one  - https://github.com/elastic/kibana/issues/78188

> We had an offline conversation with @dover around improvements.
> 
> There is a noticeable amount of SDH issues coming, which end up with a root cause, or one of the possible causes, like proxy connectivity issues. The customer has to dive into logs to figure out if the used proxy operates properly (whether connections are established, no 503s, etc.).
> 
> I believe we could more proactive and verify the connectivity between Agent and Elasticsearch, Agent and Fleet Server. I was thinking about a special technical policy first to verify all connections and settings, but maybe we can start with picking up the `elastic-agent install` feedback.
> 
> It would definitely help with researching customer problems ("Has your proxy ever worked?" vs "Is there an proxy outage now?").

**Comment by mtojek** [comment]
Another lost customer: https://discuss.elastic.co/t/cant-enroll-an-agent-to-create-fleet-server-no-error-shown-in-log/295375
