### ISSUE TITLE
Heartbeat Improvements

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#2749]
The following list contains the major tasks which have to be done to get Heartbeat ready:
- [ ] Docs
  - [ ] Move Docs and default settings to `<module>/_meta`
  - [ ] Add documentation in `docs` directory for docs build
  - [ ] Add documentation for methods in code
  - [x] Update global README.md and it heartbeat to the list. See https://github.com/elastic/beats/issues/2748
  - [ ] Add to docs build
- [ ] CI
  - [ ] Add to Travis builds
  - [ ] Add to Jenkins builds
  - [ ] Add to Appveyor builds
  - [ ] Add to snapshot builds
- [ ] Testing
  - [ ] Add system tests / integration tests
  - [ ] Add to beats-tester
- [ ] Review
  - [ ] Review config option on naming
  - [ ] Review fields if naming standard is followed
  - [ ] Code / Project review by other team member
