### ISSUE TITLE
[Meta][Heartbeat] All errors should produce ES output when possible

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#29692]
Historically when heartbeat encountered an error it would fail fast and log an error, in some cases even exit completely. As we evolve our GUI-centricity and work toward a service this mode of operation becomes less desirable. All errors should be obvious in the Uptime UI unless there is no way to communicate back to ES. This means indexing a document whenever an error happens.

This meta issue serves to track work / issues toward this goal. 

- [x] https://github.com/elastic/beats/issues/28770
- [x] https://github.com/elastic/beats/issues/29346
- [x] https://github.com/elastic/beats/pull/29413
  - [ ] Validate that running on prem with `ELASTIC_SYNTHETICS_CAPABLE=FALSE` produces an error in the Kibana UI
  - [ ] Verify that if script params are invalid, this should not be savable
- [x] #29897
  - [x] If an invalid param is set on Synthetics Agrs this should produce an error in the Kibana UI
- [ ] ~~https://github.com/elastic/uptime/issues/432~~
- [x] When `journey/end` is not reported - https://github.com/elastic/beats/issues/30729
