### ISSUE TITLE
Metricbeat Kafka Module Enhancements

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3005]
* [x] Add dashboards https://github.com/elastic/beats/issues/4665 elastic/beats#8457
* [ ] Add support for replica offsets in partition metricset 
* [x] Add metricset for broker stats
* [ ] Add metricset for consumer stats 
* [x] Consumer lag stats per partition https://github.com/elastic/beats/issues/3608

Community contributions:

* https://github.com/elastic/beats/pull/5918

**Comment by rpn0709** [comment]
One of the most important metrics to monitor in kafka is lag. This looks like it could be calculated with the following "kafka.partition.offset.newest - kafka.consumergroup.offset" but those value are in two different metricsets with no identical fields to search by. If we can get these two values in one metricset or rename the topic field to the same thing in both documents that may work.

**Comment by urso** [comment]
About lag: consumer groups are potentially handled by different brokers. The metricbeat might need to connect to remote kafka node in order to collect and correlate additional information

**Comment by urso** [comment]
As of now, metricbeat is required to be installed on every kafka node and should collect stats from local node only. => Add 'cluster' mode to kafka module. One configures a few hosts for bootstrapping only, but then the module should collect cluster wide stats. This will allow metricbeat to collect stats from remote cluster, without having to list every single node in a cluster.

**Comment by TimWardOrigami** [comment]
Agree that the main motivation for monitoring Kafka is to track consumer group lag. Ideally the lag should be a field in an event, or we should be able to calculate it by subtracting two fields in the same event.

The information is actually present and correct, but as it's in two different events I think there's no way to draw graphs of it in Kibana? - and none of my threshold detection and alerting code has any concept of doing a subtraction across two different events.

(My particular problem is that someone can send a storm of spam into Kafka, and I'd rather like to spot that a consumer group has got a couple of days behind so that I can do something about it.)

**Comment by jsoriano** [comment]
Closing, there are already metrics for partition offsets and consumer lag. There are other issues open about improving support for consumers as #22859 and #23077.
