### ISSUE TITLE
Beats Doc Updates for 5.1

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#3019]
This is a meta issue to track Beats documentation work for 5.1. 

If you have trouble clicking an item in the checklist to mark it as complete, open this comment in edit mode and change the source to `[x]`. Seems to be a bug in ticking the check boxes in this issue.

**5.1:**
- [x] Document new processors:
  - [x] add_cloud_metadata processor (see https://github.com/elastic/beats/issues/2791)
  - [x] [DeDe]json_decode_files processor (see https://github.com/elastic/beats/issues/2923 and https://github.com/elastic/beats/pull/2605)
- [x] Document Metricbeat docker module
- [x] Resolve any [doc issues flagged for 5.1](https://github.com/elastic/beats/issues?q=is%3Aissue+label%3Av5.1.0+label%3Adocs+is%3Aopen). 
- [x] [DeDe] Doc edits left over from 5.0:
  - [x] Conditionals
  - [x] HAProxy
  - [x] New config options (shutdown_timeout, etc)

NOTE: Moved "future" list to the meta issue for 5.2.
