### ISSUE TITLE
[Meta] Oracle Module Enhancements

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/beats#30810]
We've several long-awaited enhancement asks from the customers regarding the Oracle module. Let's update and release an improved version of this module that addresses the following problem scenarios and user stories.

- [x] https://github.com/elastic/beats/issues/30946
- [x] https://github.com/elastic/beats/issues/24609 (maybe a particular case of #30947)
- [x] https://github.com/elastic/beats/issues/30948
- [x] https://github.com/elastic/beats/issues/30949
- [x] https://github.com/elastic/beats/issues/31611

**Comment by yug-elastic** [comment]
Closing this issue as all the PRs for the sub-issues are merged and they are closed.
CC: @akshay-saraswat @agithomas @sunny-elastic
