### ISSUE TITLE
[Meta] Filestream Go integration tests are flaky

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#31517]
This is a top level tracking issue for build failures caused by flakiness in the filestream go integration tests. Several tests are flaky and fail regularly. Known flaky test issues from [this search](https://github.com/elastic/beats/issues?q=is%3Aissue+is%3Aopen+label%3Aflaky-test+filestream):

- [ ] https://github.com/elastic/beats/issues/31445
- [ ] https://github.com/elastic/beats/issues/31166
- [ ] https://github.com/elastic/beats/issues/31125
- [ ] https://github.com/elastic/beats/issues/26608
- [x] https://github.com/elastic/beats/issues/26353
- [ ] https://github.com/elastic/beats/issues/26727
- [ ] https://github.com/elastic/beats/issues/31662
- [ ] https://github.com/elastic/beats/issues/31700

**Comment by cmacknz** [comment]
Previous test failures that did not create an ticket automatically as examples:

    * https://beats-ci.elastic.co/job/Beats/job/beats/job/main/148/
        * filebeat-goIntegTest / github.com/elastic/beats/v7/filebeat/input/filestream.TestParsersCStyleLog
        === RUN   TestParsersCStyleLog
            environment_test.go:196: 
                    Error Trace:	environment_test.go:196
                                    parsers_integration_test.go:243
                    Error:      	Not equal: 
                                    expected: 157
                                    actual  : 121
                    Test:       	TestParsersCStyleLog
        --- FAIL: TestParsersCStyleLog (0.11s)
    * https://beats-ci.elastic.co/job/Beats/job/beats/job/8.0/386/
        *  filebeat-goIntegTest / github.com/elastic/beats/v7/filebeat/input/filestream.TestParsersJavaElasticsearchLogs
        === RUN   TestParsersJavaElasticsearchLogs
        environment_test.go:193: 
        Error Trace:	environment_test.go:193
                        parsers_integration_test.go:203
        Error:      	Not equal: 
                        expected: 7049
                        actual  : 6932
        Test:       	TestParsersJavaElasticsearchLogs
        --- FAIL: TestParsersJavaElasticsearchLogs (0.10s)
    * https://beats-ci.elastic.co/job/Beats/job/beats/job/8.0/381/
        * filebeat-goIntegTest / github.com/elastic/beats/v7/filebeat/input/filestream.TestFilestreamTruncateWithSymlink
        === RUN   TestFilestreamTruncateWithSymlink
        environment_test.go:193: 
                Error Trace:	environment_test.go:193
                                input_integration_test.go:631
                Error:      	Not equal: 
                                expected: 22
                                actual  : 0
                Test:       	TestFilestreamTruncateWithSymlink
        --- FAIL: TestFilestreamTruncateWithSymlink (0.01s)
    * https://beats-ci.elastic.co/job/Beats/job/beats/job/main/116/
        * filebeat-goIntegTest / github.com/elastic/beats/v7/filebeat/input/filestream.TestParsersRabbitMQMultilineLog
        === RUN   TestParsersRabbitMQMultilineLog
            environment_test.go:193: 
                    Error Trace:	environment_test.go:193
                                    parsers_integration_test.go:287
                    Error:      	Not equal: 
                                    expected: 386
                                    actual  : 193
                    Test:       	TestParsersRabbitMQMultilineLog
        --- FAIL: TestParsersRabbitMQMultilineLog (3.01s)
