### ISSUE TITLE
[Meta][Heartbeat] HB support for elastic-agent V2

### ISSUE THREAD

**Issue by emilioalvap** [elastic/beats#33314]
### Summary

With the introduction of elastic-agent spec V2 and at the same time the spec is implemented, Heartbeat will need to make changes required to support monitor states and an exponential backoff. This issue is to track the effort on Synthetics side.

#### V2 spec

With the new spec, the plan os to remove output section from individual beats configs. As a special case, elastic-agent will provide this config to HB, mapped to a private config so that it doesn't interfere with `libbeat` and the shipper, eg: `heartbeat.elasticsearch.output`:

- https://github.com/elastic/elastic-agent/issues/1476#issuecomment-1275123823

#### Actions on HB side

- [x] https://github.com/elastic/beats/issues/33244.
- [x] Register private `heartbeat.elasticsearch.output` config section and make it reloadable. https://github.com/elastic/beats/pull/33405
- ~~[ ] Prevent HB from propagating multiple output configs to `libbeat`.~~
- ~~[ ] Investigate how max-retry output from the shipper can be leveraged by run-once mode.~~ Found alternative solution with `libbeat test output`.
- [x] https://github.com/elastic/elastic-agent/issues/1807
- [x] https://github.com/elastic/elastic-agent/pull/1812
- [x] https://github.com/elastic/elastic-agent/issues/1931
- [x] https://github.com/elastic/beats/pull/34061

**Comment by emilioalvap** [comment]
Closing as completed, last changes have been tested during `8.7`.

https://github.com/elastic/elastic-agent/issues/1476#issuecomment-1275123823 can be tracked independently.
