### ISSUE TITLE
[auditbeat] RHEL9 support

### ISSUE THREAD

**Issue by epixa** [elastic/beats#34577]
### Overview

RHEL9 was released last May. We need to add support to our CI test matrix for Auditbeat for the latest RHEL release to ensure we're testing this on a regular basis, and then we can add it to our support matrix.

### Tasks

- [x] Perform sanity tests on RHEL9
- [x] Configure `auditbeat` [unit testing](https://github.com/elastic/beats/blob/main/auditbeat/Jenkinsfile.yml#L14) on RHEL9

### The RPM's legacy SysV-style init script

The legacy `service` command still exists in RHEL9, and will attempt to use the SysV-style init script packaged in our RPM as `/etc/init.d/auditbeat`, but it will fail because that script depends on [`/etc/rc.d/init.d/functions`](https://github.com/fedora-sysv/initscripts/blob/main/etc/rc.d/init.d/functions), which is absent on recent versions of RHEL. During manual testing I used systemd's `systemctl` command to manage the service. We should consider removing the SysV-style init script (if not required by other supported RPM-based distros), or modify it to provide graceful output rather than this error:
```
$ service auditbeat status
/etc/init.d/auditbeat: line 40: /etc/rc.d/init.d/functions: No such file or directory
/etc/init.d/auditbeat: line 44: status: command not found
/etc/init.d/auditbeat: line 90: status: command not found
```

<details>
<summary><h3>Task details - Sanity test plan</h3></summary>

#### Overview

Verify the functionality of Auditbeat on RHEL9, for both the RPM package and the tarball artifact.

#### Versions

- Red Hat Enterprise Linux release 9.1 (Plow) as Vagrant box [generic/rhel9 (virtualbox, 4.2.16)](https://app.vagrantup.com/generic/boxes/rhel9/versions/4.2.16)
- Auditbeat 8.7.0 (in the Vagrant VM)
- Elastic Stack 8.7.0 (on the host)

#### Install

RPM:
```bash
curl -L -O https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.7.0-x86_64.rpm
sudo rpm -vi auditbeat-8.7.0-x86_64.rpm
cd /etc/auditbeat/
```

Tarball:
```bash
curl -L -O https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.7.0-linux-x86_64.tar.gz
tar xzvf auditbeat-8.7.0-linux-x86_64.tar.gz
cd auditbeat-8.7.0-linux-x86_64
sudo chown root auditbeat.yml
```

#### Configure

Edit `auditbeat.yml` as follows:

- Leave the default configuration of the `file_integrity` and `system` modules.
- Uncomment the audit rules for the `auditd` module.
- Set the following connection details:
  ```yaml
  setup.kibana.host: "https://10.0.2.2:5601"
  setup.kibana.ssl.verification_mode: "none"
  output.elasticsearch.hosts: ["10.0.2.2:9200"]
  output.elasticsearch.protocol: "https"
  output.elasticsearch.ssl.verification_mode: "none"
  output.elasticsearch.username: "elastic"
  output.elasticsearch.password: "changeme"
  ```

#### Stop `auditd` so Auditbeat can get the audit data

```bash
sudo systemctl status auditd
sudo service auditd stop # use 'service' as a workaround for 'auditd.service' being configured to refuse manual stop
sudo systemctl disable auditd
```

#### Set up the assets

```
auditbeat setup -e
```

#### Start Auditbeat

RPM:
```bash
sudo systemctl start auditbeat
sudo systemctl enable auditbeat
```

Tarball:
```bash
sudo ./auditbeat --path.logs /var/log/auditbeat
```

#### Verification

- [x] RPM: System logs show Auditbeat output and no obvious errors
- [x] RPM: Elastic Stack receives `auditbeat-*` data
- [x] RPM: All Auditbeat dashboards are populated
- [x] RPM: The service survives reboot
- [x] Tarball: logs show Auditbeat output and no obvious errors
- [x] Tarball: Elastic Stack receives `auditbeat-*` data
- [x] Tarball: All Auditbeat dashboards are populated
- [x] ~~Tarball: The service survives reboot~~ &rarr; n/a

</details>

**Comment by Oddly** [comment]
Is there an update for this feature?

**Comment by jlind23** [comment]
@Oddly If we look at our currently supported operating system you should find RHEL9 : https://www.elastic.co/support/matrix

**Comment by ebeahan** [comment]
When testing, likely will encounter this known issue: https://github.com/elastic/elasticsearch/issues/85876

**Comment by ebeahan** [comment]
> The legacy service command still exists in RHEL9, and will attempt to use the SysV-style init script packaged in our RPM as /etc/init.d/auditbeat, but it will fail because that script depends on [/etc/rc.d/init.d/functions](https://github.com/fedora-sysv/initscripts/blob/main/etc/rc.d/init.d/functions), which is absent on recent versions of RHEL.

@chrisberkhout can you open a separate issue capturing these observations? We'll log in an issue for future work and also provide some context if anyone experiences and searches for the same error.
