### ISSUE TITLE
Beats Doc Updates for 5.3

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#3539]
**5.3:**

- [x] Make sure these sections get edited:
  - [x] Config reload (backlog. See #3281)
  - [x] Docs about -setup for loading dashboards (see https://github.com/elastic/beats/pull/3506).
- [x] Heartbeat docs: Add content about loading sample dashboards when the dashboards are available. 
- [x] Check cURL statements used in docs to make sure they include content-type when passing a body.
- [x] Make these minor fixes to the getting started guides:
  - [x] Mention that command line options aren’t available when using init.d script. See https://github.com/elastic/beats/issues/812 (also contains some info relevant to issue #1047)
  - [x] Filebeat GS:  move step about importing the index pattern in Filebeat into the doc for Filebeat rather than making users jump to the platform ref for a simple command.
- [x] Fix bugs flagged for 5.3 plus: 
  - [x] Clarify Filebeat docs wrt the index setting (see https://github.com/elastic/beats/issues/3558).
- [x] Make sure our Beats developer guide is up-to-date and that the Metricbeat docs point to the docs about the single generator (we now have a single generator for generating either a Beat or a Beat based on Metricbeat--see https://github.com/elastic/beats/pull/3491). Make sure the blog post mentioned in the PR has been updated.

**Follow up:**
- [x] See if we can remove close this issue: https://github.com/elastic/beats/issues/652

**Comment by dedemorton** [comment]
Closing this and moving the backlog https://github.com/elastic/beats/issues/4021
