### ISSUE TITLE
Add FAQ topics to the Beats doc

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#3599]
This issue is for discussing topics that we might want to add to the Beats FAQs. Candidates for this list include questions that come up frequently in the discussion forums.

- [ ] How to get Filebeat to re-process log files.
- [ ] Why does Filebeat sometimes produce duplicates? 
- [ ] How do I tell filebeat not to process older log files?

**Comment by dedemorton** [comment]
Closing because  I think it’s better to focus on the core docs rather than making the FAQ longer (a short faq is better imo)
