### ISSUE TITLE
Dynamically generate and load index templates

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3654]
Currently index templates are generated with python and then packaged with each beat. This has the disadvantage that with more ES versions more files have to be generated and packaged. In addition it does not allow to only provide a template for one metricbeat module for example. Generating the templates as part of the beat will allow to generate the needed templates on request and does not required anymore prepackage templates.

Implementation steps:

* [x] Implement generation in Golang https://github.com/elastic/beats/pull/3603
  * [x] Remove defaults from fields.common.yml for more flexibility https://github.com/elastic/beats/pull/3602
  * [x] Unify naming of fields.yml entries https://github.com/elastic/beats/pull/3655
* [x] Unify fields generated file across all beats #3677 https://github.com/elastic/beats/pull/3683
* [x] Set template order for seamless migrations: https://github.com/elastic/beats/issues/3657
* [x] Implement dynamic generation of template when starting the beat https://github.com/elastic/beats/pull/3681
* [x] Remove generated templates
* [ ] Reorganise template config options https://github.com/elastic/beats/issues/3921
* [ ] Add config option to generate json on disk #4323
* [x] Add support to check elasticsearch version and generate templates accordingly
* [x] ~~Allow template generation per Metricbeat module~~ (multiple template not supported by ES 6)
* [ ] Move manual template generation to `beats-tools` or something similar
* [x] Identify how variables like `number_of_shards` could be easily set https://github.com/elastic/beats/pull/4284
* [ ] Review the guides in the docs around template and dashboard loading.

**Comment by ruflin** [comment]
Elasticsearch will potentially remove the support for template inheritance in 6.0 and will always pick the one if the highest order. This will impact the last point "template generation per module".

**Comment by tsg** [comment]
@dedemorton Pinging you here for awareness, for 6.0 we'll be significantly changing the way templates and dashboards are loaded. This will likely require some updates in the existing guides, but lets wait for things to stabilize a bit before updating them.

**Comment by tsg** [comment]
Closing, looks mostly done.
