### ISSUE TITLE
Check Pod Autodiscover conditions for node/namespace updates

### ISSUE THREAD

**Issue by gizas** [elastic/beats#37338]
## Context

This issue tries to resolve the https://github.com/elastic/beats/issues/34717 
For more details, upon of [Node](https://github.com/elastic/elastic-agent-autodiscover/blob/main/kubernetes/eventhandler.go#L193) or [Namespace](https://github.com/elastic/elastic-agent-autodiscover/blob/main/kubernetes/eventhandler.go#L154) event updates, we trigger updates for all pods that are related to the specific resources. 

The issue is that many of those updates are not related with the actual metadata information that the watchers are made for. So we need to check which of those updates are the ones that should trigger pod watcher restarts

## Solution
We enhance the nodePodupdater function and we also pass the nodeWatcher as a parameter https://github.com/elastic/beats/blob/conditionsonPodupdater/libbeat/autodiscover/providers/kubernetes/pod.go#L156

Then we are able to check whether those updates are releavnt or not in order to trigger a pod update in https://github.com/elastic/elastic-agent-autodiscover/blob/conditionsonPodupdater/kubernetes/eventhandler.go#L236-L245

## How to Test

- Create a kind cluster `kind create cluster`
- Create a local stack with `elastic-package stack up -d -vvv --version=8.12.0-SNAPSHOT`
- Follow [Process](https://github.com/elastic/beats/blob/main/metricbeat/module/kubernetes/_meta/test/docs/README.md#build-and-launch-metricbeat-process) (just replace metricbeat with filebeat)
- Install https://github.com/elastic/beats/blob/main/filebeat/_meta/test/docs/01_playground/filebeat.yaml
- Download the elastic-agent-autodiscover repo linked in this story with relevant updates. In order to make filebeat to use the local copy of your elastic-agent-autodiscover library, update the **/beats/go.mod** file:
```yaml
replace github.com/elastic/elastic-agent-autodiscover => /Users/andreasgkizas/elastic/elastic-agent-autodiscover
```
- Build filebeat `GOOS=linux GOARCH=arm64 go build`
- You can monitor node updates on the background 
```bash
kubectl proxy &
stdbuf -oL curl -s '127.0.0.1:8001/api/v1/nodes?allowWatchBookmarks=true&watch=true&pretty=false' > nodes.log &
```
 - Trigger a node with eg.`kubectl label nodes kind-control-plane katsoulis=pasole`

## Definition of Done

- [x] Test for a longer period of time for node updates
- [x] Repeat same procedure on namespacePodUpdater
- [ ] Test and verify that metricbeat is not affected. (Reason is to see how autodiscover affects metricbeat) 
- [ ] Test with a full Elastic Agent build to see if something is not broken

## Testing

1. Updating label of namespace
```bash
kubectl label namespaces default katsoulis3=pasole
```

![Screenshot 2023-12-12 at 4 53 17 PM](https://github.com/elastic/beats/assets/1685415/b9282620-bfa7-4c8f-8f95-cd8b1780cc66)

2. Updating label of node
```bash
kubectl label node kind-control-plane pas1=pas1
```
![Screenshot 2023-12-13 at 11 46 56 AM](https://github.com/elastic/beats/assets/1685415/0370c34e-f37f-4a7c-a215-5ff8640df3f8)

3. Checking the events of nodes

Metadata Event update in node triggers pod update

<img width="1706" alt="Screenshot 2023-12-11 at 2 02 34 PM" src="https://github.com/elastic/beats/assets/1685415/b7d9a937-a94e-4619-8298-46f59d95230f">

Healthcheck Event update in node **does not** trigger pod update

![Screenshot 2023-12-13 at 11 56 28 AM](https://github.com/elastic/beats/assets/1685415/7dfe0e1d-bf10-4e04-ad4f-12f7dbf84885)

## Relevant link:
- [Repo in elastic-agent-autodiscover](https://github.com/elastic/elastic-agent-autodiscover/blob/conditionsonPodupdater/kubernetes/)
- [Beats Repo](https://github.com/elastic/beats/blob/conditionsonPodupdater/libbeat/autodiscover/providers/kubernetes/)

```[tasklist]
### Tasks
- [ ] [PR in elastic-agent-autodiscover/](https://github.com/elastic/elastic-agent-autodiscover/pull/71)
- [ ] [PR in beats](https://github.com/elastic/beats/pull/37431)

```

**Comment by constanca-m** [comment]
I ran an environment with these changes.

When I did: 

```
kubectl label node kind-control-plane teste2=teste1
```

I could see the output:

![image](https://github.com/elastic/beats/assets/113898685/e0eab5ea-96f3-4707-a93c-99cc1503763e)

I left filebeat running for longer, and I could not see more updates on pods from the node healthcheck. But if I trigger it again by updating the labels of the node, I can see it the message again for pod update.

It seems to work fine!
