### ISSUE TITLE
Restructure Beats documentation

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#3737]
Restructure the Beats documentation into three separate books:

- [ ]  Beats User Guide - Beats overview info plus the docs for all Beats in a single book - The One Beats Guide to Rule Them All
- [x] Beats Developer Guide - (https://github.com/elastic/beats/issues/3738) All content for developers, including architecture overview
- [ ] Beats Release Notes

Rough outline (in progress and definitely not complete).

`````
Beats User Guide 
=============

Overview
	Log Monitoring with Filebeat
	Uptime Monitoring with Heartbeat
	Metrics Monitoring with Metricbeat
	Windows Event Monitoring with Winlogbeat	
Community Beats
Getting Started...
 	with Elastic Stack*
	with Filbeat
	with Heartbeat
	with Metricbeat
	with Packetbeat
	with Winlogbeat
Configuring Beats
	Configuration Options (Reference)
		Filbeat
		Heartbeat
		Metricbeat
		Packetbeat
		Winlogbeat
		Outputs
	Processors
	Filtering and enhancing the exported data
	Configuring Beats to Use Ingest Node
	Using Environment Variables
	YAML Tips and Gotchas
	Config File Format
Exported Fields
	Filbeat
	Heartbeat
	Metricbeat
	Packetbeat
	Winlogbeat
Securing Beats
Troubleshooting
	Getting Help
	Debugging
	Frequently Asked Questions		
Release Notes

* We won't need this if we have a getting started guide in the stack docs.

Beats Developer Guide
================

Beats Architecture
Contributing to Beats
Beats Extension Points
Creating a New Beat
Creating New Kibana Dashboards for a Beat
Extending Packetbet
	Protocol Analyzer
Extending Metricbeat
	Adding New Modules
	Adding New Metricsets
`````

**Comment by dedemorton** [comment]
Eureka! I think I've figured out how to work around the problem with duplicate section IDs. We can use variables to ensure unique IDs. The usual syntax that we use for IDs doesn't accept variables. So this DOES NOT work: `[[{beatname_lc}-myid]]`

But this seems to work:  `[id="{beatname_lc}-myid"]`

Adding this comment now because I'm likely to forget my aha moment when I'm ready to restructure the Beats content. :-)

**Comment by dedemorton** [comment]
The section about Configuring beats needs to be fleshed out and changes like the ones described here need to be added: https://github.com/elastic/beats/issues/4422

**Comment by dedemorton** [comment]
This work is no longer targeted for 6.0 because each Beat will continue to be a separate install. Deferring to a future release.

**Comment by dedemorton** [comment]
Closing because the hierarchy described here no longer makes sense now that we are aligning the docs with solutions.
