### ISSUE TITLE
Remove deprecated features in master branch

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3782]
The next release of the master branch will be the 6.0 release. Features which were deprecated for 5.0 should be removed in the master branch to clean it up. This issue is intended to track the removal of these items.

* [x] Remove old filebeat configuration options https://github.com/elastic/beats/pull/3768
* [x] Remove filebeat state conversion script for migration from 1.x to 5.x https://github.com/elastic/beats/pull/3767
* [x] Remove geoip feature https://github.com/elastic/beats/pull/3766
* [x] Remove topology map feature  https://github.com/elastic/beats/pull/3769
* [x] Remove http endpoing in Winlogbeat https://github.com/elastic/beats/pull/3901

**Comment by ruflin** [comment]
Closing as all PR's were merged.
