### ISSUE TITLE
Improve error handling in schema / metricsets

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3807]
The current error handling in schema and metricsets is not optimal. The following should be done to improve it / clean it up:

* [ ] `schema.Apply` should return and error list and not only log errors. This improves unit testing. https://github.com/elastic/beats/pull/3790
* [ ] Remove temoprary `ApplyNoError` and modify processors accordingly
* [ ] New `schema.Apply` also stores Optional fields errors. Identify if this could be a performance issue in production
* [ ] Improve logging of errors by logging a missing field only once and potentially all in one line
* [ ] Check currently ignored errors in each metricset and handle errors

**Comment by tsg** [comment]
Closing as old.
