### ISSUE TITLE
[Logstash] Missing `logstash.node.stats.pipelines.queue.capacity` mapping

### ISSUE THREAD

**Issue by crespocarlos** [elastic/beats#38164]
## Summary 

Logstash mapping is missing `logstash.node.stats.pipelines.queue.capacity.*` fields, causing the error below

```
"mapper [logstash.node.stats.pipelines.queue.capacity.queue_size_in_bytes] cannot be changed from type [float] to [long]
```

AC

`logstash.node.stats.pipelines.queue.capacity` is mapped as following

```json
{
  "capacity": {
    "properties": {
      "max_queue_size_in_bytes": {
        "type": "long"
      },
      "max_unread_events": {
        "type": "long"
      },
      "page_capacity_in_bytes": {
        "type": "long"
      },
      "queue_size_in_bytes": {
        "type": "long"
      }
    }
  }
}
```

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/beats/pull/38262
- [ ] https://github.com/elastic/elasticsearch/pull/106218
- [ ] https://github.com/elastic/integrations/pull/9339
```

**Comment by sheelchand** [comment]
I see the same issue in elasticsearch logs `"stacktrace": ["java.lang.IllegalArgumentException: mapper [logstash.node.stats.pipelines.queue.capacity.queue_size_in_bytes] cannot be changed from type [float] to [long]",` 

Does anybody know the work around like a way to change the mapping to float?

**Comment by klacabane** [comment]
Hi @sheelchand, workarounds differ depending on the metrics collection mode. Are you using elastic-agent or metricbeat to collect the data ?

**Comment by sheelchand** [comment]
@klacabane We use metrcibeat for logstash monitoring. Please let us know the workaround. Thanks!
