### ISSUE TITLE
[logstash] add missing `logstash.node.stats.pipelines.queue.capacity` mapping

### ISSUE THREAD

**Issue by klacabane** [elastic/beats#38250]
### Summary
Add missing `logstash.node.stats.pipelines.queue.capacity` ([sample event](https://github.com/elastic/integrations/blob/main/packages/logstash/data_stream/node_stats/sample_event.json#L141-L146)) mapping

```
  "queue": {
      "capacity": {
          "max_queue_size_in_bytes": 1073741824,
          "max_unread_events": 0,
          "page_capacity_in_bytes": 67108864,
          "queue_size_in_bytes": 132880
    }
  }
```

```[tasklist]
### Tasks
- [ ] update [metricbeat-*](https://github.com/elastic/beats/tree/main/metricbeat/module/logstash) mappings
- [ ] update [.monitoring-logstash-*](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/template-resources/src/main/resources/monitoring-logstash-mb.json) mappings
- [ ] update [logstash package](https://github.com/elastic/integrations/tree/main/packages/logstash) mappings
```

**Comment by miltonhultgren** [comment]
Duplicate of https://github.com/elastic/beats/issues/38164?

**Comment by klacabane** [comment]
dup
