### ISSUE TITLE
The integration test framework should test the DEB and RPM installations of Beats

### ISSUE THREAD

**Issue by jlind23** [elastic/beats#38334]
Relates https://github.com/elastic/elastic-agent/issues/4086

In order to properly replace Beats-tester we need to rely on the Elastic Agent testing framework to install standalone Beats using DEB and RPM. Similar to https://github.com/elastic/elastic-agent/pull/4301

```[tasklist]
### Tasks
- [ ] RPM for metricbeat
- [ ] DEB for metricbeat
- [ ] RPM for filebeat
- [ ] DEB for filebeat
```
