### ISSUE TITLE
Heartbeat GA

### ISSUE THREAD

**Issue by urso** [elastic/beats#3952]
**EDIT**

The only required things for GA are now considered to be:

- [x] Automatic Reload #8023  (6.x via #8315)
- [ ] Automatic Reload Docs #8227  
- [ ] Mark heartbeat 6.5 as GA #8331

-------

Original (archived)

Required:
- [x] event structure: #3406, #3838

- [x] http rtt measures: #3530

- [x] add `fields`, `tags` settings to monitors: #3623

- [ ] add 'generic' kibana dashboard
- [x] HTTP default port: #3915

- [x] Use IP type for `ip` field #3926

- [ ] Make the http url field a proper URL formatted field in Kibana index pattern
- [ ] Check documentation if GA ready
- [ ] telemetry

discussion:
- scheduler configuration and implementation:
  - replace Tasks with goroutines + I/O lib blocking, rate-limiting actual IO operations (inactive tasks need no stack and such -> less resource usage)
  - keep cron-like configuration or have only configurable period based on beats-start.

**Comment by tsg** [comment]
Linking also this one, for visibility:
* [] https://github.com/elastic/beats/issues/5234 Allow parsing the response body

**Comment by urso** [comment]
http body check: #5981

**Comment by ruflin** [comment]
I reorganised the GA checklist to get this quicker to GA. We now only have a few items left for GA. Some of the optional changes could be breaking but we can tackle these for 7.0

**Comment by andrewvc** [comment]
Removed the optional checkboxes, archiving here:


Optional:
- [ ] HTTP NTMLSSP support (add support for IIS).
- [ ] HTTP redirect handling
  - [ ] validate redirect occured (setting to follow redirect)
  - [ ] validate no redirect response
- [ ] Sample reindex API configuration to convert old heartbeat events into new event format
- [ ] rate limiting active Task (IO operations) in scheduler #4664
- [ ] ICMP Echo on Windows
- [ ] UDP based ping (e.g. ping not using root uses UDP)
- [ ] Fix crash error: https://github.com/elastic/beats/issues/6616
- [ ] dynamic reloading based on conf.d. Note: current reloading merges settings, so users can define defaults (this functionality get's lost)
- [ ] enhance validators using conditionals support from libbeat:
  - [ ] more enhanced support to build requests. #3970
  - [ ] make conditionals 'locally' extensible via `ConditionBuilder` with custom registry of validators
- [ ] report TLS details: #3741
- [ ] Allow parsing the response body https://github.com/elastic/beats/issues/5234

**Comment by andrewvc** [comment]
Updated to only have auto reload as required for GA
