### ISSUE TITLE
Publisher / Output Refactoring

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3955]
* [x] Unify publisher handling across all beats
* [x] Only allow one output to be active at the same time (applies to LS, ES, Kafka, Redis)
* [ ] Make output reloadable

**Comment by ruflin** [comment]
Closing this as @urso handled the first 2 items. Reloading is not possible yet but we have soon the foundation for it to make it possible.
