### ISSUE TITLE
[meta][winlogbeat] GA the experimental API

### ISSUE THREAD

**Issue by marc-gr** [elastic/beats#39580]
Meta issue to track necessary work to make the experimental API GA (this issue is still a wip and list is not exhaustive) :

- [x] https://github.com/elastic/beats/issues/19337
- [x] https://github.com/elastic/beats/issues/19338
- [x] Fix documentation https://github.com/elastic/beats/pull/41770
- [x] Ensure ForwardedEvents are handled optimally by avoid rendering them and using RenderedMessage https://github.com/elastic/beats/pull/41525
- [x] Improve testing and benchmarking of both APIs
- [x] See if both APIs can comply to the same format (see https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-winlogbeat-options.html#_event_logs_api) https://github.com/elastic/beats/pull/41525
- [x] https://github.com/elastic/beats/issues/40386
