### ISSUE TITLE
Follow up kubelet module

### ISSUE THREAD

**Issue by exekias** [elastic/beats#3965]
Finish all the rough edges after initial merge: https://github.com/elastic/beats/pull/3916

- [x] Complete fields.yml files with all fields
- [x] Check fields again if they follow the conventions
- [x] Add system tests to check if all fields are documented
- [x] Add tests
- [x] Add more documentation on how to use it etc.
  - [x] Add documentation on how metricbeat should be deployed inside kubernetes
- [x] Check that all beta flags exist and work.
- [x] Add dashboard/(s)

**Comment by exekias** [comment]
Documentation to deploy kubernetes was added, I think we can close this
