### ISSUE TITLE
[Meta] Supporting Kerberos in Elastic Agent Kafka  Output 

### ISSUE THREAD

**Issue by nimarezainia** [elastic/beats#39761]
Currently there are gaps in agent/beats support for kerberos in various kafka implementations. This meta issue is to gather all the specific development efforts that need to be implemented in order to provide a cohesive offering

```[tasklist]
### Tasks
- [ ] Update the Kafka client currently in use by beats/agent so that we have access to the latest
- [ ] Ensure filebeat Kafka input correctly authenticates against Active Directory using Kerberos config
- [ ] Ensure *beats output to Kafka authenticates against Active Directory using Kerberos config, and make this feature GA
- [ ] Modify the Fleet UI for Kafka output to include a Kerberos configuration
- [ ] (optional) Support kerberos authentication on the Metricbeat kafka module```
```

Related issus:

- [x] https://github.com/elastic/beats/issues/33334
- [ ] https://github.com/elastic/elastic-agent-shipper/issues/168

cc: @cmacknz

**Comment by nimarezainia** [comment]
> The first step here will be getting a test environment with both Kafka and Kerberos using Active Directory.
> 
> We can then test if we can fix this by upgrading our fork of https://github.com/elastic/sarama which implements our Kafka client. This is quite far (~700 commits) behind upstream now. There is an upstream Kerberos test we could use as a starting point https://github.com/IBM/sarama/blob/main/kerberos_client_test.go. This appears to have been added in [IBM/sarama#2457](https://github.com/IBM/sarama/pull/2457).
> 
> We can simulataneously evaluate if it is worth continuing to maintain our own fork of Sarama, or even evaluate alternative client packages, although that will present challenges with configuration backwards compatibility. https://github.com/twmb/franz-go is one alternative that claims Kerberos support.

kafka exporter in otel seems to have [support](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/kafkaexporter/README.md) for kerberos although there's no way of telling whether it works with AD. How would one tell which implementation of the kafka client is being used there?

Thinking ahead, if we were to utilise otel for this feature I see the following priorities:

1.  Ensure kafka exporter has all the features we need for the support provided today (whether upstreamed or in our dist)
2. Change our Fleet UI (beats based) kafka implementation to interface with the otel shipper instead
3. Modify the standalone config to be otel based (which would be a breaking change unless we do some translation between beats to otel config)

Which ever way we choose to go, building a testing environment for this first is a must.

**Comment by cmacknz** [comment]
It is the same as ours, `github.com/IBM/sarama` https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5427c934ebcad5dfb77bca48e44b063349b6e4f4/internal/kafka/authentication.go#L12

**Comment by nimarezainia** [comment]
> It is the same as ours, `github.com/IBM/sarama` https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5427c934ebcad5dfb77bca48e44b063349b6e4f4/internal/kafka/authentication.go#L12

trying to make a decision on whether this can wait until otel shipper is available and we switch over. Even if we assume that the otel kafka exporter has an updated fork of the client and that there are no issues with it working with AD, we won't be able to use this for the filebeat Kafka input. Perhaps that will be the caveat we live with.

**Comment by ldecrescenzo** [comment]
Hi @nimarezainia/ @cmacknz! I would like to know if we have any updates about this topic.

I had the same issue with two customers asking about this Kerberos/Kafka authentication.

Thanks in advance!

**Comment by cmacknz** [comment]
Something that came out of the FIPS work is noticing that some of the packages used to implement Kerberos today use custom cryptography of questionable origin. We should try to find alternatives. The FIPS builds are disabling Kerberos for this reason.

https://github.com/elastic/ingest-dev/issues/4533#issuecomment-2635526751

**Comment by cmacknz** [comment]
The active directory work will be blocked on having a VM that supports active directory, captured in:

- https://github.com/elastic/ingest-dev/issues/4700

This will additionally unblock supporting active directory for the user that runs the Elastic Agent service.

**Comment by cmacknz** [comment]
I would like to see us evaluate if there is a better way to implement Kerberos, find out how to evaluate Active Directory, and how to test it properly before starting work here.

**Comment by nimarezainia** [comment]
Blocked because of https://github.com/elastic/ingest-dev/issues/4700

**Comment by nimarezainia** [comment]
@ebeahan and @cmacknz we currently have an escalation on this topic. I know we are waiting for the VM with AD to be available from the robots team. Any chance this work can start before the VM is available?  obviously the ultimate goal is to have that VM readily available for future testing etc however I would have thought that this could be set up on an individual engineer's setup for work to continue.

cc: @jlind23

**Comment by jlind23** [comment]
@elastic/observablt-robots do you have this on your radar? if yes, any way we can get this prioritized when you have some bandwidth?

**Comment by v1v** [comment]
@jlind23, yes, it's on our radar. Unfortunately, we are working on some top-priority tasks related to serverless, and not all of us can have access to the Buildkite ecosystem.

The current status is:

>The problem is related to our internal buildkite infrastructure, gobld and a private GCP QA account. Windows VMs with the AD can't start and the startup logs are not accessible

Maybe the Plaftorm Eng Productivity team could help here, as they are the ones providing the BK infrastructure. 

Another approach I can think of, if possible, we could pair with someone from the Beats team, hand over what we have done so they can move things forward while we work in other top-priorities tasks. 

What do you think?

**Comment by cmacknz** [comment]
We should also check to see if security has a solution to this already.

@MindyRS does your team have any test setups for Windows with ActiveDirectory enabled we could reuse or build on?

**Comment by nimarezainia** [comment]
@v1v I wanted to followup on this issue. Could https://github.com/elastic/ingest-dev/issues/4700 be prioritized please?

**Comment by v1v** [comment]
> @v1v I wanted to followup on this issue. Could https://github.com/elastic/ingest-dev/issues/4700 be prioritized please?

Sure thing, @pazone is leading the effort, so he can provide details on when he can start working on it.

**Comment by pazone** [comment]
@nimarezainia The [AD support](https://github.com/elastic/ingest-dev/issues/4700) implementation will be started tomorrow.

**Comment by nimarezainia** [comment]
I believe we are now unblocked on the AD support.

**Comment by pazone** [comment]
FYI: [The image and the Windows machine are ready](https://github.com/elastic/ingest-dev/issues/4700#issuecomment-2830509367). As far as I understand we need a setup of 3 VMs: 

- Kafka/Kerberos 
- Windows AD VM 
- a VM with enrolled elastic-agent managed by buildkite

Should we discuss it and create a follow up issue for this (if it doesn't exist)?

**Comment by ebeahan** [comment]
Revisiting this issue with the help of Claude's analysis (rephrased into my words). 

* https://github.com/elastic/beats/issues/33334 and the [beta warning](https://www.elastic.co/docs/reference/beats/filebeat/kafka-output#kerberos-option-kafka) are still in place.
  * The Sarama update to v1.46.3 was done as part of https://github.com/elastic/beats/issues/49210
  * Whether the update addressed the Active Directory bug is unverified as fixed. 

* The upstream `kafkaexporter` switched from `sarama` to `franz-go`: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/44565. 
  * The `kafkaexporter` distribution already has a Kerberos config struct backed by franz-go.
  * Need to verify if the OTel `kafkaexporter` Kerberos config works correctly against Active Directory, and if it does, document this as the recommended path.

* Kerberos config keys differ between the two `elastic/sarama` and `franz-go`/`kafkaexporter`. We need to understand the impact to configuring in the Fleet UI.

* Metricbeat Kafka module - should this be handle by Signals, if still a need?

**Comment by khushijain21** [comment]
So, I tested kafka output (on main) with active directory using following steps and the test was successful. Note, this was manual step and we can work towards automating this in CI

1. Creating a VM with AD installed
	1. Spin up VM with AD installed (image created by Pavel [here](https://github.com/elastic/ingest-dev/issues/4700#issuecomment-2830509367) ). Create a network tag like `ad-kerberos`
	2. Create a firewall rule with the tag `ad-kerberos` [here](https://console.cloud.google.com/net-security/firewall-manager/firewall-policies/list?project=elastic-platform-ingest) )to expose tcp/udp on port 88.
2. Creating prinicpal for kafka service. 
	1. Install the RDP. Exec into the VM using Windows Desktop app. (Available in appstore in macos)

     <ol type="i" start="2">

      <li>Open powershell as administrator and run below command. Note the realm name here is `ingest.example.com` because this is the domain name used when creating the VM

```
Import-Module ActiveDirectory

New-ADUser -Name "beats" -SamAccountName "beats" `
  -UserPrincipalName "beats@ingest.example.com" `
  -AccountPassword (ConvertTo-SecureString "Testing1!" -AsPlainText -Force) `
  -Enabled $true -PasswordNeverExpires $true
Set-ADUser beats -KerberosEncryptionType AES128,AES256 -ChangePasswordAtLogon $false

New-ADUser -Name "kafka_localhost" -SamAccountName "kafka_localhost" `
  -UserPrincipalName "kafka_localhost@ingest.example.com" `
  -AccountPassword (ConvertTo-SecureString "KafkaBroker1!" -AsPlainText -Force) `
  -Enabled $true -PasswordNeverExpires $true
Set-ADUser kafka_localhost -KerberosEncryptionType AES128,AES256 -ChangePasswordAtLogon $false

setspn -A kafka/localhost kafka_localhost

ktpass /princ kafka/[localhost@INGEST.EXAMPLE.COM](mailto:localhost@INGEST.EXAMPLE.COM) `
  /mapuser kafka_localhost@INGEST.EXAMPLE.COM `
  /pass KafkaBroker1! `
  /out C:\kafka_localhost.keytab `
  /crypto AES256-SHA1 `
  /ptype KRB5_NT_PRINCIPAL
```
</li>
</ol>

   <ol type="i" start="3">
   <li>Copy the keytab created for the kafka service using following command

```
[Convert]::ToBase64String([IO.File]::ReadAllBytes("C:\kafka_localhost.keytab"))
```

  </li>
  </ol>

3. Test end-to-end
    1. Checkout this branch. https://github.com/khushijain21/beats/tree/kafka-kerberos
    This branch sets up kafka service with kerberos enabled. Ensure that the copied keytab is stored under `beats/testing/environments/docker/kafka_kerberos/secrets` and also ensure that the test is pointing to the correct public IP of your VM
   2. Run `mage docker:composeUp` from libbeat.
   3. Run `go test -run TestKafkaPublishKerberosAware -tags integration ./libbeat/outputs/kafka`
   4. The test passed.

Troubleshooting TIp:
- My test failed the first time because of encryption mismatch between AD and kafka service. 
- AD issued a RC4 (`arcfour-hmac`) service ticket for `kafka/localhost`, while the broker keytab only had AES256. The broker couldn’t decrypt the ticket and auth failed
- Ensure that AD account + keytab use the same etypes — typically set `KerberosEncryptionType` to AES128/AES256 on the AD user and export the keytab with AES (`/crypto AES256-SHA1`), so AD issues AES service tickets that match the keytab.
