### ISSUE TITLE
Improve importability of Beats in other code bases

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#40110]
Beats code base currently has a number of assumptions that make it very difficult to import beats into another code base and makes it very difficult to run multiple instances of beats within the same process.

- [x] [libbeat/common/reload](https://github.com/elastic/beats/blob/c111789e3c611a075fa2e02a65b5b8f9a6b4657f/libbeat/common/reload/reload.go#L30) uses a package global variable for the Registry.  This means you can't have 2 different beats with 2 different registries in the same process, this needs to be fixed.  #40622
- [x] [filebeat modules](https://github.com/elastic/beats/blob/c111789e3c611a075fa2e02a65b5b8f9a6b4657f/filebeat/fileset/factory.go#L42) and [metricbeat modules](https://github.com/elastic/beats/blob/c111789e3c611a075fa2e02a65b5b8f9a6b4657f/metricbeat/mb/module/runner.go#L37) register metrics in the same namespace.  Each beat needs it's own namespace to prevent collisions.  #40660
- [x] libbeat sets command line flags [here](https://github.com/elastic/beats/blob/c111789e3c611a075fa2e02a65b5b8f9a6b4657f/libbeat/cfgfile/cfgfile.go#L32-L64) and [here](https://github.com/elastic/beats/blob/c111789e3c611a075fa2e02a65b5b8f9a6b4657f/libbeat/cmd/root.go#L98-L108), if libbeat is imported in another code base you can have conflicts with flags.  This needs to be changes so libbeat can be imported without setting any flags.
- [x] elastic/beats#40659
- [x] libbeat sets [fleetmode](https://github.com/elastic/beats/blob/c111789e3c611a075fa2e02a65b5b8f9a6b4657f/libbeat/common/fleetmode/fleet_mode.go#L35) by looking at CLI flags, this needs to be fixed.  #40667

**Comment by blakerouse** [comment]
Final importability issue that was linked to this issue was fixed here - https://github.com/elastic/beats/pull/40993
