### ISSUE TITLE
Beats Doc Updates for 5.4

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#4021]
**5.4** 

This list is a work-in-progress and doesn't accurately represent doc goals for 5.4 (yet)

- [x] Resolve doc bugs and issues flagged for 5.4.0:
  - [x] Move content about processors. See https://github.com/elastic/beats/issues/4058 (in progress, but not currently flagged for 5.4)
  - [x] Fix the structure of the modules documentation. See https://github.com/elastic/beats/issues/4029
  - [x] Clarify docs for Windows commands to indicate the Powershell is required. See #3993 
  - [x] Document complex objects support in env/cli vars #3686 
   - [x] Document limitation of multiple host output interaction with LS when multiline is configured on the LS side #4008 
- [x] Add more content about flows to the Packetbeat docs. Right now we only have config info [here](https://www.elastic.co/guide/en/beats/packetbeat/5.2/configuration-flows.html). What are flows? What kind of info can you get? When are they needed?
- [x] Pull dev guide content into a single Beats Developer Guide #3738
- [x] Update docs with info about official docker images.

Notes:
- Moved backlog to https://github.com/elastic/beats/issues/4193.
- Removed "Heartbeat rtt.us field is not documented" from this list because urso has an issue open for heartbeat ga to add more rtt measures.

**Comment by dedemorton** [comment]
Added https://github.com/elastic/beats/pull/4197 to cover flows.
