### ISSUE TITLE
[META][Kubernetes provider/Kubernetes module] Set watcher options node based on configuration

### ISSUE THREAD

**Issue by constanca-m** [elastic/beats#40246]
We need to do similar work for `node` as we did for `namespace` [in this issue](https://github.com/elastic/beats/issues/38978).

- [ ] [Beats] In beats, check node option is being taken into consideration. For example, the watcher is not using the `node` option for deployment:
https://github.com/elastic/beats/blob/269d31935ea6a107cfdc8d9317aff78cb5d7263f/libbeat/autodiscover/providers/kubernetes/pod.go#L128-L133
- [ ] [Beats] Check `add_kubernetes_metadata` node option as well
- [ ] [Beats] Update documentation
- [ ] [Elastic Agent] Check the Kubernetes provider uses the node option
- [ ] [Integrations] Put the node option at group level, similar as we did for namespace [here](https://github.com/elastic/integrations/pull/10213).
