### ISSUE TITLE
[META Issue]Enhancement for being able to toggle the kubeadm-config api calls 

### ISSUE THREAD

**Issue by gizas** [elastic/beats#40276]
This is the META issue that will summarise all the needed sub issues that are needed in order to be able to disable the /api/v1/namespaces/kube-system/configmaps/kubeadm-config API calls through configuration. 

The relevant enhancement was raised here: https://github.com/elastic/enhancements/issues/21172 
See this issue for more details

The enhancement finally needs to be available in the elastic agent when users install the Kubernetes Integration. Additional we note that the kubeadm config calls are being made both  as part of log collection process start and as metrics collection starts.

So in more details the task list is:

### Tasks
- [ ] [Metricbeat Enhancememt]: Issue to disable the kube-adm calls in metricbeat. https://github.com/elastic/beats/pull/40086 
- [ ] [Filebeat autodiscover Enhancememt]: Issue to disable the kube-adm calls when [autodiscover](https://github.com/elastic/beats/blob/main/deploy/kubernetes/filebeat-kubernetes.yaml#L133) is configured in **filebeat**. This specific issue needs to be implemented on kubernetes provider. Respectively the pod, node and service have eg [PodMetadataGenerator](https://github.com/elastic/beats/blob/main/libbeat/autodiscover/providers/kubernetes/pod.go#L149) that finally calls the [getClusterInfoFromKubeadmConfigMap](https://github.com/elastic/elastic-agent-autodiscover/blob/main/kubernetes/metadata/metadata.go#L145) that is responsible to make those calls 
- [ ] [Filebeat Input Enhancememt]: Issue to disable the kube-adm calls when [filestream input](- [ ] [Filebeat autodiscover Enhancememt]: Issue to disable the kube-adm calls when [autodiscover]) is configured. In this case check if relevant api calls are made
- [ ] [Elastic Agent Fix]: Issue that is needed to make available in the Elastic Agent policy of kubernetes integration all the config options introduced from previous issues from filebeat and metricbeat. We will need to make checks with metrics and logs ingestion enabled to check whether the API calls are minimised

NOTES: 
- In elastic agent the add_kubernetes_metadata processor starts by default and is not configurable
- In case Fleet Elastic Agent needs to configure the kubernetes provider, we will use the following installation method: https://www.elastic.co/guide/en/fleet/current/advanced-kubernetes-managed-by-fleet.html#_step_2_create_a_new_configmap

**Comment by gizas** [comment]
@cmacknz I was testing the above [enhancement](https://github.com/elastic/integrations/pull/11187) through the integration, but I could not observe any improvements in case of applying the use_kubeadm variable through the integration.

 ![Image](https://github.com/user-attachments/assets/ea8b70f3-e822-4c7d-b442-ca58782f44b3)


I think the reason is that the kubernetes provider is already started and we call the [GetPodMetadataGen](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/composable/providers/kubernetes/pod.go#L131) here

So to my questions:

- ```bash
DEV=true EXTERNAL=true SNAPSHOT=true PLATFORMS=linux/amd64 PACKAGES=tar.gz mage -v package
failed to run compiled magefile: signal: killed
```
I have at least 7GB of memory, any ideas how else I can unblock myself here?

- Do we have an API for the elastic-agent to configure the add_kubernetes_metadata processors in advance?
- I guess the work of https://github.com/elastic/elastic-agent/issues/4670 is still in progress? I can not use it now somehow?

**Comment by cmacknz** [comment]
> Do we have an API for the elastic-agent to configure the add_kubernetes_metadata processors in advance?

Not yet.

> I guess the work of https://github.com/elastic/elastic-agent/issues/4670 is still in progress? I can not use it now somehow?

It was paused because we are working on getting rid of the beats sub-processes which would eliminate this problem.

I would suggest if you need control over this for k8s to expose it as a env var as was done for add_cloud_metadata. There is unfortunately no other easy change to make here, the global processor configuration is unnecessarily hard to do in the current agent architecture.

**Comment by henrikno** [comment]
@gizas Could we add a way to toggle this via an ENV var?

Btw. `failed to run compiled magefile: signal: killed` went away from me when I upgraded go 1.22 to go 1.23.

**Comment by swiatekm** [comment]
It took me a bit of time to figure out where the kubeadm behaviour is configured in elastic-agent, so I'm going to leave the results here for posterity. To start with, this is the default of our internal autodiscovery library, defined [here](https://github.com/elastic/elastic-agent-autodiscover/blob/c0ab8b63bf5ac1e926b9a997bfa4ca272a3b4af3/kubernetes/metadata/config.go#L48). Elastic-agent implements this default [here](https://github.com/elastic/elastic-agent/blob/472cb1bf4758566b20adfeae6c766b97e3c1692f/internal/pkg/composable/providers/kubernetes/config.go#L67).

If we wanted to disable this behaviour in agent, the config fragment would look like the following:

```yaml
providers:
  kubernetes:
    add_resource_metadata:
      namespace:
        use_kubeadm: false
      node:
        use_kubeadm: false
```

**Comment by gizas** [comment]
Oh I see that we refer https://github.com/elastic/elastic-agent-autodiscover/blob/main/kubernetes/metadata/config.go#L63-L64 and this uses use_kubeadm: true!!!!

So question would be how to initialise the kubeadm: I see only this option  https://www.elastic.co/guide/en/fleet/current/advanced-kubernetes-managed-by-fleet.html#_step_2_create_a_new_configmap correct? 
And also the users would need to configure the use_kubeadm in policy of https://github.com/elastic/integrations/pull/11187

**Comment by swiatekm** [comment]
> Oh I see that we refer https://github.com/elastic/elastic-agent-autodiscover/blob/main/kubernetes/metadata/config.go#L63-L64 and this uses use_kubeadm: true!!!!
> 
> So question would be how to initialise the kubeadm in agent provider: I see only this option https://www.elastic.co/guide/en/fleet/current/advanced-kubernetes-managed-by-fleet.html#_step_2_create_a_new_configmap correct? And also the users would need to configure the use_kubeadm in policy of [elastic/integrations#11187](https://github.com/elastic/integrations/pull/11187)

I *think* you can also set this via overrides in the fleet policy after https://github.com/elastic/elastic-agent/pull/6169. @blakerouse please let me know if I'm off the mark here.

**Comment by gizas** [comment]
@swiatekm any progress on this? Do you want to document the steps in case of EA? 
Even in case of overrides is it not clear to me where how I apply them
