### ISSUE TITLE
Complete the Beats Developer Guide

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#4059]
Remaining work for Beats Dev Guide:

- [x] Decide how far to backport this change. Decision: Don't backport. This is for 6.0.0+.
- [x] Set up redirects for moved content
- [x] Replace CONTRIBUTING.md content with a link to the section in the dev guide
- [x] Update any links that point to CONTRIBUTING.md to point to the docs instead (for example https://github.com/elastic/beats/README.md should point to the published docs).
- [ ] Update section about adding packetbeat protocols so that it has actual content
- [ ] ~Add conceptual info that covers various extension points for beats (work in content from the Elastic{ON} presentation (see #3737 for an idea of the propsed TOC)~
- [x] Consider whether we should take the content from this blog and add it to the devguide: https://www.elastic.co/blog/build-your-own-beat

**Comment by jsoriano** [comment]
@dedemorton I was talking with @fearful-symmetry about updating some things in the devguide and I found this issue. Can it be closed? I see that other related issues and PRs are already closed.

**Comment by dedemorton** [comment]
Closing because most of this work has been done. There is a separate issue open to track updating the protocol docs: https://github.com/elastic/beats/issues/1111

@jsoriano It's awesome that you are planning to update the much-neglected dev guide. There are a bunch of other PRs related to updating the dev guide. Should I assign them to you?

**Comment by jsoriano** [comment]
Well, @fearful-symmetry was thinking about updating the devguide :innocent:
