### ISSUE TITLE
Metricbeat: reduce disk usage in default configuration

### ISSUE THREAD

**Issue by tsg** [elastic/beats#4112]
Meta ticket for several improvements we plan for Metricbeat in order to reduce the storage space requirements in its default configuration.

* [x] #4127 Add a feature to allow collecting only the first top N processes by CPU and/or memory, instead of all of them.
* [x] #4231 Add new metrics for the total process counts and use those in dashboards
* [x] #4284 Make it possible to set "shards" and "replicas" from the metricbeat YAML file.
* [x] #4329 Set the default number of shards to 1.
* [x] #4317 Make it easily possible to disable `_source`, but leave it on by default.
* [x] #4329 Enable best compression by default.
* [x] #4329 Reduce the collection interval for filesystem statistics and disable `fsstat` by default. Set it to 1m.
* [x] #4329 Filter out several filesystem types by mount point (e.g. proc, tmpfs, dev)
* [ ] Filter out logical devices from the `diskio` stats

We target these changes for the 6.0 release.

**Comment by tsg** [comment]
This can be considered closed.
