### ISSUE TITLE
Beats doc updates for 5.6

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#4193]
**5.6**

- [x] Document how to run Beats in a container (https://github.com/elastic/beats/issues/4192)
- [x] Document file permissions for config reloading (https://github.com/elastic/beats/issues/4189)
- [x] Update screen captures of dashboards. 
- [x] [Monica] Add section to upgrading topic about upgrading dashboards to use Kibana API. 
- [x] [Tudor] Import machine learning jobs.

NOTE: Moved backlog to https://github.com/elastic/beats/issues/4540

**Comment by dedemorton** [comment]
Changing this to 5.6 since 5.5 is already out (had to defer some 5.5 work at the last minute because there were higher priority issues in the LS docs).
