### ISSUE TITLE
Filebeat refactoring / restructuring

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#4277]
Filebeat must be refactored / restructured to make event publishing less complex and adding new prospector types easier.

* [x] Send events from harvester directly to spooler instead of through prospector https://github.com/elastic/beats/pull/4070
  * [x] Unify data handling across filebeat https://github.com/elastic/beats/pull/4171
  * [x] Move json field handling to log harvester https://github.com/elastic/beats/pull/4159
* [x] Extract stdin prospector from prospector package https://github.com/elastic/beats/pull/4158
* [x] Extract log prospector from prospector package, cleanup naming https://github.com/elastic/beats/pull/4273
* [ ] Generalise state handling to make it available to other prospector types https://github.com/elastic/beats/pull/4190
  * [x] Add type to registry to handle states of other prospectors https://github.com/elastic/beats/pull/4185
  * [ ] Abstract state so each prospector can have different or not state object. The exact format should not matter for the registrar.
* [x] Rename `input_type` to just `type` in config https://github.com/elastic/beats/pull/4294
* [ ] Decouple stdin and log harvester. Currently stdin uses most of the logic from the log harvester which makes these two packages overlapping.
* [ ] Replace old publisher with new and move processors to pipeline
* [ ] Think about future data model of prospector types. See https://github.com/elastic/beats/pull/4180 as an example. Will we have harvester types?
* [ ] Cleanup channel / outlet handling across filebeat. Currently it all depends too much on Outleter.
* [ ] Store fields information in _meta directory with each prospector type and collect it from there.

**Comment by ruflin** [comment]
@ph Pinging you on this one as I'm not sure you are aware of it. Perhaps we can also close this issue by now?

**Comment by ph** [comment]
Oh Lets close it, I didn't about this issue :)
