### ISSUE TITLE
Import/export dashboards via the Kibana API

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#4409]
Thanks to https://github.com/elastic/kibana/pull/10858, a new API for importing and exporting Beats dashboards is added. 

The export API receives a list of dashboards ids to be exported into a single JSON file. The JSON file contains not only the dashboards, but also the visualizations, searches, and the index pattern (by default). This allows us to group all the dashboards (including visualizations and searches) of a module into a single JSON file, that makes it easier to import using the import API. The Beats are using the export API only to export the dashboards, including the dependencies, without the index pattern that is separately generated by each Beat.

The import API receives the JSON file to be imported.

Thinks that still need to be done (after the #4413 is merged):
- [x] TLS config
- [x] Configure username/password for Kibana
- [x] Add make import-dashboards 
- [ ] Add make export-dashboards
- [ ] fix test `es_loader_test` to test with an older of version of Elasticsearch
- [x] add system test in libbeat to load the dashboards in Kibana
- [x] export dashboards in the new format for the other Beats
- [ ] redo mysql and golang dashboards to use time series visual builder
- [ ] Filebeat auditd dashboard fails with an error (https://github.com/elastic/beats/issues/4595)
- [ ] Update docs 
- [ ] Add export dashboards option to the Beat executable https://github.com/elastic/beats/pull/4725
- [x] Create a `module.yml` for all the modules, not only for those that contain more than one dashboard

**Comment by kvch** [comment]
This issue is for an old version of beats, I suggest to try out the latest version of beats. If this is still a problem in the newly released version feel free to reopen this issue. Thanks.
