### ISSUE TITLE
Beats doc updates in 6.0

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#4540]
**GA**

- [x] [DeDe] Document index setting change in the breaking changes. See https://github.com/elastic/beats/issues/5614
- [x] [DeDe] Add link that points from release notes to breaking changes doc.
- [x] [DeDe] Change getting started guides to show how to pass credentials by updating the config file - we do not want to recommend passing credentials at the command line.
- [x] [DeDe] Add docs about manually loading the template (LS users need to do this). See https://github.com/elastic/beats/issues/5615 and https://github.com/elastic/beats/issues/5080
- [x] [DeDe] Update docs to reflect https://github.com/elastic/beats/pull/4867 (by default, the user doesn't need to configure the credentials for Kibana as they are taken from the Elasticsearch).
- [x] [DeDe] Deprecate document_type in LS examples. 
- [x] [DeDe] Verify that the latest version of the breaking changes documentation reflects Pius's comments below.
- [x] For auditbeat kernel metricset:
  - [x] Document how to check if auditd is running, how to stop it, and how to disable it from starting at boot. `service auditd status`, `service auditd stop`, `chkconfig auditd off`
  - [x] Document how to stop journald from listening to audit messages to save CPU and disk. `systemctl mask systemd-journald-audit.socket`
- [x] Add info about setting a custom index name to the GS doc. See https://github.com/elastic/beats/issues/4254
- [x] Set up redirects for topics that have moved in 6.0.
- [x] For metricbeat:
  - [x] We removed `cpu_ticks` and replaced it with `cpu.metrics` and `core.metrics`. [diff](https://github.com/elastic/beats/pull/4553/files#diff-a641598f5625c7a21eb70c1662e5d693) https://github.com/elastic/beats/pull/4909
- [x] Docs around how to import/export dashboards are changing significantly to use Kibana API for importing dashboards. 
- [x] Change doc structure to accommodate prospector types. See https://github.com/elastic/beats/issues/4398
- [x] Add/update compatibility statements for all modules in all Filebeat and Metricbeat (and others?); make compatibility sections consistent, including for 3rd party Outputs (Kafka/Redit).
- [x] Add Beats usage with Cloud
- [x] Add a link to the ES doc regarding removal of _types

**RC1 and RC2**

- [x] [DeDe] Document modules.d layout for Metricbeat. See https://github.com/elastic/beats/issues/5207
- [x] Solution pages - link off to docs - Beats doc landing pages need to be enhanced to make the user experience better.
- [x] Remove import_dashboards from packaging. See https://github.com/elastic/beats/pull/4586
-  [x] [Monica] Update docs about how to create new dashboards in the dev guide: https://github.com/elastic/beats/pull/5229 https://www.elastic.co/guide/en/beats/devguide/current/new-dashboards.html
https://www.elastic.co/guide/en/beats/devguide/6.x/export-dashboards.html
- [x] [DeDe] Add screen shot of Icinga dashboard.
- [x] Verify that compatibility statements in the Filebeat module documentation are correct.

**Beta 1 and 2**

- [x] [DeDe] Document new command line with sub-commands. See https://github.com/elastic/beats/issues/4490. 
- [x] [DeDe] Add docs for auditbeat. Implement a structure for config options that's similar to the one described here: https://github.com/elastic/beats/issues/4422
- [x] [DeDe] Update shared gs topics about template loading and importing dashboards
- [x] [Tudor] Add docs around importing ML jobs
- [x] [Tudor] Update breaking changes section of doc (see note from Pius below). See https://github.com/elastic/beats/issues/4737
- [x] [Tudor] Write the upgrade guide for 5.x to 6.x #5068
- [x] [Tudor] Heartbeat packages were renamed to heartbeat-elastic. This affects the command to start the service too.
- [x] [DeDe] Update getting started docs about dashboard loading. See https://github.com/elastic/beats/pull/4675
- [x] [kvch] Update Filbeat module development guide
- [x] Add docs for PRs labeled as `needs_docs`:
  - [x] [DeDe] Metricbeat test modules. https://github.com/elastic/beats/pull/4656
  - [x] Update broker/pipeline setup. https://github.com/elastic/beats/pull/4650 Urso added in https://github.com/elastic/beats/pull/4884
  - [x] [DeDe] Add filebeat modules config reloading. See https://github.com/elastic/beats/pull/4566
  - [x] [DeDe] Move to a modules.d layout. See https://github.com/elastic/beats/pull/4537 
  - [x] [DeDe] Add support for json logging to file. See https://github.com/elastic/beats/pull/4523
  - [x] [DeDe] UDP prospector type with plain harvester. See https://github.com/elastic/beats/pull/4452
  - [x] Add Fields and Tag to monitor config. https://github.com/elastic/beats/pull/4141

Moved backlog to https://github.com/elastic/beats/issues/5632

**Comment by ppf2** [comment]
We will also want to update the [breaking changes](https://www.elastic.co/guide/en/beats/libbeat/master/breaking-changes.html) section of the doc.  For example, there are breaking changes [here](https://www.elastic.co/guide/en/beats/libbeat/master/release-notes-6.0.0-alpha2.html) but theses are not in the breaking changes section of the documentation.

Also, there is another breaking change I am aware of that does not appear to be documented today.  Which is the fact that filebeat will not start now unless you have a module or prospector defined (and the default prospector for /var/log/*.log is disabled by default).

**Comment by ppf2** [comment]
Adding: https://github.com/elastic/beats/issues/4633

**Comment by urso** [comment]
Pipeline changes will require doc updates as well: #4598

**Comment by andrewkroh** [comment]
For auditbeat kernel metricset:
- Document how to check if auditd is running, how to stop it, and how to disable it from starting at boot. `service auditd status`, `service auditd stop`, `chkconfig auditd off`
- Document how to stop journald from listening to audit messages to save CPU and disk. `systemctl mask systemd-journald-audit.socket`

**Comment by tsg** [comment]
I checked the heartbeat one because `heartbeat-elastic` is already used here: https://www.elastic.co/guide/en/beats/heartbeat/6.0/setup-repositories.html and I also mentioned it briefly in the Upgrading guide. I think that covers it.

**Comment by brandonmensing** [comment]
@dedemorton Can we add a link to the ES doc regarding removal of _types?
From here: https://www.elastic.co/guide/en/beats/libbeat/6.0/breaking-changes-6.0.html#breaking-changes-types
To here:
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html

**Comment by dedemorton** [comment]
> @dedemorton Can we add a link to the ES doc regarding removal of _types?

@brandonmensing Yup will do. Your timing is good because I'm must now making some remaining doc updates related to removal of _types.

**Comment by brandonmensing** [comment]
@dedemorton Reminder comment for the types link :)

**Comment by dedemorton** [comment]
Re the breaking changes content: I think it's fairly clear from the wording (now) that "Breaking changes in 6.0" only describes the main changes that affect upgrade. Plus there is a link to the release notes for additional breaking changes. I think we're covered. It's an extra hop for users, but they might actually like that we distill the most important changes into a topic with more detail.

Plus...it's not a simple copy/paste to move the content. We pull in the changelog for the release notes. I don't like the idea of duplicating content, so I am planning to leave the relnotes as-is. I have added more links though to help people navigate between the BC and relnotes.

**Comment by dedemorton** [comment]
I've moved any pending items to #5632. Closing out this issue.
