### ISSUE TITLE
Beats features status

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#4581]
- Beats:
    - [ ] Auditbeat (Experimental - in 6.0 is build on top of Metricbeat)
    - [ ] Heartbeat (in 6.0 is Beta) https://github.com/elastic/beats/issues/3952
    - [ ] Packetbeat, Filebeat, Metricbeat, Winlogbeat (GA)
- [ ] Filebeat modules (Beta) -> GA (in 6.0)
- [ ] Filebeat/Metricbeat config reloading (in 6.0 is Beta) -> GA
- Processors:
     - [ ] add_docker_metadata (in 6.0 is Beta)
     - [ ] add_kubernetes_metadata (in 6.0 is Beta)
- [ ] Expose go metrics (Doesn't exist)

cc-ed @brandonmensing @ruflin
