### ISSUE TITLE
Publisher Pipeline

### ISSUE THREAD

**Issue by urso** [elastic/beats#4598]
- [x] Introduce new publisher pipeline with BC layer #4492 
- [x] Move processors, tags and fields into publisher pipeline #4554 
- [x] Remove compat layer:
  - [x] Update packetbeat to new pipeline #4599
  - [x] Update filebeat to new pipeline #4641 #4644 
  - [x] Update metricbeat to new pipeline #4699 
  - [x] Update winlogbeat to new pipeline #4690 
  - [x] Update heartbeat to new pipeline #4591 
  - [x] Remove bc/publisher package
    - [x] Remove bc layer #4776 
    - [x] merge libbeat/beat and publisher/beat packages #4821 
- [x] Improve ACK handler:
  - [x] Add support for pipeline-global ACK handler #4641 
- [x] Make pipeline parameters configurable (remove old configurations) #4650 
- [x] Add checks to libbeat/filebeat/metricbeat to reject 5.x queue/spooler/filters setting on startup #4726 
- [x] improve pipeline/output metrics #4663 
- [x] Update packetbeat code generator #4956 
- [x] Documentation updates
  - [x] removed unused settings from docs: #4753
    - filebeat: `filebeat.spool_size`, `filebeat.publish_async`, `filebeat.idle_timeout`,
    - libbeat: `queue_size`, `bulk_queue_size`,
    - metricbeat`filters` in modules
  - [x] Document libbeat queue settings: #4884 
    - `queue.<queue_type>` with default (and only available) `mem`:
    - mem queue settings: `events`, `flush.min_events`, `flush.timeout`.
  - [x] Document local `tags`, `fields` and `processors` settings in heartbeat monitors, filebeat prospectors, winlogbeat eventlogs, metricbeat modules, packetbeat flows/plugins. #4753 
  - [x] Update developer docs to use new publisher pipeline
