### ISSUE TITLE
Filtering exported fields (Phase 1)

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#462]
The goal is to configure each Beat not to export all fields. There should be two options how to reduce the number of exported fields:
- __Configuration options__, by adding configuration options for most common use cases. 
- __Generic filtering__ for more specific use cases, based on conditionals. A proposal is described in #451 and it is part of the Phase 2.

__Configuration options__

The configuration options are specific to each Beat. The biggest advantage is the performance. We can apply the actions at the beginning, before even creating the event. 

There are already few configuration options, already implemented, in Packetbeat, Topbeat and Filebeat that restrict the number of fields to be exported like the `send_request` or `send_response` from Packetbeat or `stats` from Topbeat to specify the type of statistics to collect.

But new ones are requested like:

Topbeat

- [x] Make optional exporting cpu usage per core: https://github.com/elastic/beats/issues/424

Filebeat

- [x] Remove or include only some fields: https://github.com/elastic/filebeat/issues/78
- [x] Exclude specific files: https://github.com/elastic/filebeat/issues/298

**Comment by monicasarbu** [comment]
Closing as all the features are implemented and it will be available in the next release.
