### ISSUE TITLE
Filebeat modules: machine learning jobs

### ISSUE THREAD

**Issue by tsg** [elastic/beats#4680]
Include ML jobs in the filebeat modules. As part of this ticket, sample ML job configurations and specific ML dashboards are included for the Nginx module.

ToDos:

* [x] Add infra for loading ML jobs to the modules. https://github.com/elastic/beats/pull/4506
* [x] Add ML jobs for the Nginx module. https://github.com/elastic/beats/pull/4609
* [x] Adjust ML datafeed settings. https://github.com/elastic/beats/pull/4676
* [x] Don't load the ML configurations if the ES version is 5.4. #4681
