### ISSUE TITLE
Document breaking changes in 6.0

### ISSUE THREAD

**Issue by tsg** [elastic/beats#4737]
From the CHANGELOG:

*Affecting all Beats*

- [x] Rename `kubernetes` processor to `add_kubernetes_metadata`. #4473 <-- `kubernetes` is new anyway, and in beta
- [x] Rename `*.full.yml` config files to `*.reference.yml`. #4563 <-- mention it in the upgrade guide
- [x] The `scripts/import_dashboards` is removed from packages. Use the `setup` command instead. #4586 <-- done
- [x] Change format of the saved kibana dashboards to have a single JSON file for each dashboard #4413 <-- not really important from the user POV
- [x] Rename `configtest` command to `test config`. #4590 <-- `configtest` still works so not really a breaking change? Perhaps mention it in the upgrade guide?
- [x] Remove setting `queue_size` and `bulk_queue_size`. #4650 <-- done
- [x] Remove setting `dashboard.snapshot` and `dashboard.snapshot_url`. They are no longer needed because the
  dashboards are included in the packages by default. #4675 <-- minor
- [x] Introduce beat version in the Elasticsearch index and mapping template #3527 <-- is this breaking in any way?
- [x] Usage of field `_type` is now ignored and hardcoded to `doc`. #3757 <-- done in 5.x already
- [x] Change vendor manager from glide to govendor. #3851 <-- not user facing
- [x] Rename `error` field to `error.message`. #3987 <-- minor
- [x] Change `dashboards.*` config options to `setup.dashboards.*`. #3921 <-- minor, since the main way of importing the dashboards in 5.x was `import_dashboards`
- [x] Change `outputs.elasticsearch.template.* to `setup.template.*` #4080

*Filebeat*

- [x] Rename `input_type` field to `prospector.type` #4294 <-- done
- [x] The `@metadata.type` field, added by the Logstash output, is now hardcoded to `doc` and will be removed in future versions. #4331. <-- minor
- [x] Remove code to convert states from 1.x. #3767 <-- i think only relevant in the sense that we should mention that upgrades have to be done major by major
- [x] Remove deprecated config options `force_close_files` and `close_older`. #3768 <-- minor
- [x] Change `clean_removed` behaviour to also remove states for files which cannot be found anymore under the same name. #3827 <-- minor
- [x] Remove `document_type` config option. Use `fields` instead. #4204 <-- done
- [x] Move `json_error` under `error.message` and `error.key`. #4167 <-- minor

*Heartbeat*

- [x] Renamed the heartbeat RPM/DEB name to `heartbeat-elastic`. #4601 <-- mention in the upgrade guide

*Metricbeat*
- [x] Change all `system.cpu.*.pct` metrics to be scaled by the number of CPU cores.
  This will make the CPU usage percentages from the system cpu metricset consistent
  with the system process metricset. The documentation for these metrics already
  stated that on multi-core systems the percentages could be greater than 100%. #4544 <-- this was actually already done in 5.5
- [x] Remove filters setting from metricbeat modules. #4699 <-- done

*Packetbeat*

- [x] Remove the already unsupported `pf_ring` sniffer option. #4608 <-- mionor
- [x] Remove deprecated `geoip`. #3766 <-- minor
- [x] Replace `waitstop` command line argument by `shutdown_timeout` in configuration file. #3588 <-- minor

*Winlogbeat*

- [x] Remove metrics endpoint. Replaced by http endpoint in libbeat (see #3717). #3901 <-- this functionality doesn't exist, stop asking questions

Another one, from #4540:

- [x] Also, there is another breaking change I am aware of that does not appear to be documented today. Which is the fact that filebeat will not start now unless you have a module or prospector defined (and the default prospector for /var/log/*.log is disabled by default). <-- done

**Comment by urso** [comment]
missing in filebeat:
- removed: `filebeat.spool_size`, `filebeat.publish_async`, `filebeat.idle_timeout`

**Comment by tsg** [comment]
Another one we shouldn't forget:

- [ ] cgo is enabled in all beats now

**Comment by tsg** [comment]
Almost forgot:

* [ ] It is no longer possible to enable two outputs (of different kind) at the same time.

We should also add a deprecation log in 5.6 for this.

**Comment by tsg** [comment]
There's one more that we missed:

* [ ] The module level processors in metricbeat need to specify the fields by their full name, not relative the the module.

**Comment by dedemorton** [comment]
@tsg I think we can close this now, right? Looks like the requirement for using the fully qualified name is mentioned here: https://www.elastic.co/guide/en/beats/libbeat/current/breaking-changes-6.0.html#breaking-changes-filters

**Comment by dedemorton** [comment]
Closing because the work on this for 6.0 is done. If the breaking changes need additional updates, let's open a new issue.
