### ISSUE TITLE
Meta: Workaround Metricbeat tests timeouts on Travis

### ISSUE THREAD

**Issue by tsg** [elastic/beats#4802]
Meta issue to group attempts for find a temp workaround for the failing Travis tests:

* [x] #4798 - Try `travis_wait` - doesn't work
* [x] #4801 - Split proxy_dep in the docker compose file
* [x] #4801 Try reducing the memory usage.

**Comment by tsg** [comment]
We might have improved things by starting the containers in three batches and reducing the heap size from the ES instance, but probably not for long. Closing for now.
