### ISSUE TITLE
Loading dashboards improvements

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#4863]
The purpose of this issue is to collect all small issues/improvements that need to be done for loading the dashboards
- [x] In Cloud, the default username and password for Kibana is the same as for Elasticsearch. We can have the default in `setup.kibana` to get the username and password from Elasticsearch configuration, if not set https://github.com/elastic/beats/pull/4867
- [x] When trying to load 5.x dashboards to Kibana 5.x, but they are missing, we should print an error instead of `INFO Kibana dashboards successfully loaded.` https://github.com/elastic/beats/pull/4867
- [x] Remove the warning from the 6.x dashboards containing TSVB viz, as they are loaded only to Kibana 6.x https://github.com/elastic/beats/pull/4979
- [x] Allow loading the dashboards in a configurable index https://github.com/elastic/beats/pull/4949
- [x] Write docs about how to migrate 5.x dashboards to 6.x https://github.com/elastic/beats/pull/4929

**Comment by monicasarbu** [comment]
Closing the issue as all the improvements were implemented.
