### ISSUE TITLE
New naming conventions for the dashboards

### ISSUE THREAD

**Issue by tsg** [elastic/beats#4984]
We decided to follow common Dashboard naming conventions with the Logstash team. In short:

* Dashboards are named like this: "[Filebeat Nginx] Access logs"
* Visualizations and searches are named like this: "Top processes [Filebeat Nginx]"

This is a meta ticket for documenting the guidelines and updating the Beats dashbaords:

* [x] Add dashboard guidelines to the dev guide
* [x] Update Filebeat dashboards https://github.com/elastic/beats/pull/4952
* [x] Update Metricbeat dashboards elastic/beats#4979 
* [x] Update Packetbeat dashboards elastic/beats#5008 
* [ ] Update Packetbeat searches & vis
* [ ] Update Heartbeat dashboards
* [x] Update Auditbeat dashboards https://github.com/elastic/beats/pull/5182

**Comment by kaiyan-sheng** [comment]
I believe we have ci jobs to make sure naming conventions are correct. But I think we might still missing the documentation in dev guide.

**Comment by andresrc** [comment]
Let's add it to the dev guide.

**Comment by mtojek** [comment]
Dashboards updated. Unassigning.
