### ISSUE TITLE
Improve Logging in Libbeat

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#5000]
Libbeat uses its own logging implementation. But the library has its limitation. This issue should be used as a meta issue to discuss potential issues with the library and also if moving forward the internal library should be improved or potentially replaced by either just and interface or a specific logging library as a dependency.

There are a few related Github issues which should be tracked with this Github issue:

* [x] https://github.com/elastic/beats/issues/2764
* [x] https://github.com/elastic/beats/issues/4295
* [ ] https://github.com/elastic/beats/issues/4678
* [x] https://github.com/elastic/beats/issues/3114 (fixed via a whitelist of gauges names (temp hack))
* [ ] https://github.com/elastic/beats/issues/1807
* [x] https://github.com/elastic/beats/issues/5042

This issue will be updated with new information.

**Comment by ruflin** [comment]
@andrewkroh Could you have a look at the above ot check how many boxes we can check with your new implementation?

**Comment by andrewkroh** [comment]
I ticked two more checkboxes.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.

**Comment by acbox** [comment]
This issue was closed with these two outstanding:

- https://github.com/elastic/beats/issues/4678
- https://github.com/elastic/beats/issues/1807

I'm here specifically because I would also like log level to be changed dynamically via HTTP. Any plans for this on the horizon? Thanks.

**Comment by andrewkroh** [comment]
@acbox I saw a recent change at https://github.com/elastic/elastic-agent-libs/pull/82 that makes the level changeable. I don't know if there are plans to expose this via an API.
