### ISSUE TITLE
Filebeat module for Elasticsearch 

### ISSUE THREAD

**Issue by tsg** [elastic/beats#5301]
This is the meta ticket for implementing a Filebeat module for collecting and parsing the logs of Elasticsearch.

* [x] Bring up topic of more structured logging with Elasticsearch team https://github.com/elastic/elasticsearch/issues/31046
* [x] Server Fileset
  * [x] Add basic fileset: https://github.com/elastic/beats/pull/7124
  * [x] Add support for log lines from ML.
  * [x] Add enhanced structure: https://github.com/elastic/beats/pull/5394
* [x] Slowlog Fileset https://github.com/elastic/beats/pull/7473
  * [x] Add basic Fileset: Ingest data with timestamp extraction + test file
  * [x] Enhanced processing of log lines
* [x] Deprecation Fileset https://github.com/elastic/beats/pull/7474
  * [x] Add basic Fileset: Ingest data with timestamp extraction + test file
  * [x] Enhanced processing of log lines
* [x] GC log Fileset
  * [x] Add basic Fileset: Ingest data with timestamp extraction + test file https://github.com/elastic/beats/pull/7305
  * [x] Enhanced processing of log lines
* [x] GC log jvm9 Filset
  * [x] Add basic Fileset: Ingest data with timestamp extraction + test file https://github.com/elastic/beats/pull/7390
  * [x] Enhanced processing of log lines
* [x] Audit log fileset https://github.com/elastic/beats/pull/7365
  * [x] Add basic Fileset: Ingest data with timestamp extraction + test file
  * [x] Enhanced processing of log lines

**Comment by joshuar** [comment]
I've submitted a PR for the beginnings of an Elasticsearch module in #5394 .

**Comment by ruflin** [comment]
I updated this issue to track all filesets in more detail.

**Comment by immon** [comment]
Doesn't `Cluster Log` cover the same as `Server Fileset`? I was about to work on it but either I don't understand a difference or this is the same.

**Comment by joshuar** [comment]
@immon I believe so, see the discussion on https://github.com/elastic/beats/pull/7124.  I've removed the Cluster section.

**Comment by ruflin** [comment]
++ I assume we can also merge gc for jvm and jvm9 as it's one fileset, just 2 grok patterns.

**Comment by ruflin** [comment]
@joshuar @immon @jakommo @radoondas @inqueue How do you feel about closing this issue? Is anything major missing? I will continue to follow up with the Elasticsearch team about the structure of the logs but I think the auditlog discussion here is a good starting point: https://github.com/elastic/elasticsearch/issues/31046

**Comment by immon** [comment]
@ruflin I still don't have a jvm9 version of https://github.com/elastic/beats/pull/7484 which adds detailed data on GC times, heap size etc.
I'm struggling with it a bit since there is no 1:1 translation between jvm8 and jvm9 logs.

**Comment by ruflin** [comment]
@immon Could we solve this by having 2 different metricsets and our users need to select manually which one they want to enable? In general I'm still wondering if all jvm8 and jvm9 logs look almost identical from different apps running on jvm or if the ES one is very specific? If not, we should think about creating a jvm Filebeat module.

**Comment by immon** [comment]
@ruflin this is not about application logs, but garbage collection logs. JVM9 [reimplemented GC logging](http://openjdk.java.net/jeps/271) and besides log format change they introduced different log messages exposing different metrics (at least with the GC options ES is using).
I'm not keen to have a manual selection of metricset but I won't be able to dig out the same metrics as @inqueue in his PR. In a longer-term it means that kibana visualization for GC will have some metrics empty.

**Comment by immon** [comment]
just created https://github.com/elastic/beats/pull/7628 for a basic support for jvm9 gc metrics

**Comment by ruflin** [comment]
Closing this issue was we have a module now. @ycombinator FYI
