### ISSUE TITLE
Auditbeat GA

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#5432]
This issue tracks the tasks required to move Auditbeat from a beta release to a GA release.

### Changes

- [x] Refactoring Auditbeat Modules Auditbeat enhancement #5422 #5675
- [x] Unify the Auditbeat Event Schema Auditbeat enhancement #5423
- [x] Add recursive watches to file integrity module Auditbeat enhancement #5421
  - [x] Use fsevents for macOS #5266
  - [x] fsnotify-backed recursive watcher for Linux / Windows #5833
- [x] Add a way to exclude files in the integrity module #5342 #5888
- [ ] Spooling to disk #TBD (Will not be include in the Auditbeat 6.2 release.)

### Docs

- [x] Document running Auditbeat under Docker Auditbeat docs #5132 

### Testing

- [x] Add Auditbeat to [beats-tester](https://github.com/elastic/beats-tester) https://github.com/elastic/beats-tester/pull/69

**Comment by andrewkroh** [comment]
Testing Issues for 6.2

- [ ] `World Writable File Count [Auditbeat File Integrity]` visualization should filter out symlinks.
- [ ] Add a breaking changes section the Auditbeat docs that explains the changes in 6.2 GA vs prior beta versions
- [ ] Remove `cfgwarn.Beta` logging from the two modules.
