### ISSUE TITLE
Double `@timestamp` key when using the JSON decoder

### ISSUE THREAD

**Issue by tsg** [elastic/beats#5437]
Initially reported on [discuss](https://discuss.elastic.co/t/6-0-0-rc1-json-overwrite-keys-not-working-with-timestamp/105189), the bug is about adding two `@timestamp` keys when using JSON decoding on a doc that has a valid `@timestamp` key in it.

* [x] Hot fix in the 6.0 branch #5436 
* [x] Forward port to master #5444
* [x] Add integration tests on JSON decoding that check for double `@timestamp` #5455
* [ ] Refactor the `MergeJSONFields` function to work with `beat.Event` instead of `common.MapStr`

**Comment by kvch** [comment]
An issue for the initial bug is opened: https://github.com/elastic/beats/issues/5440

**Comment by kvch** [comment]
Resolved in later versions.
