### ISSUE TITLE
Metricbeat module for Logstash

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#5439]
This is the meta issue for adding a new Metricbeat module for collecting visualising Logstash metrics, similar to the ES and K modules we have today.

* [x] Add module skeleton https://github.com/elastic/beats/pull/5540
* [ ] Add the main relevant metrics
* [ ] Sync metric naming between Logstash Filebeat Module and Metricbeat Module
* [ ] Dashboard/(s)

**Comment by cachedout** [comment]
We've got a pretty good handle on this these days now that a Metricbeat module for Logstash exists  and we haven't seen any activity on this meta-issue for quite some time. I recommend that we close this and track any additional needed work in individual issues. (If there any objections, of course, please feel free to re-open this.)
