### ISSUE TITLE
Beats doc updates in 6.x

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#5632]
FYI: I'm planning to move the roadmap for docs to a project instead of a meta issue because the meta issue format isn't working well. I end up doing a lot of work that never makes it onto this list.

**6.x**
- MOVED TO ROADMAP Document the fields.yml and backport to 6.0, if possible. See https://github.com/elastic/beats/issues/6049
- [x] [DeDe] Make sure GS guides accurately reflect requirement for using sudo (Most of the Beats require to sudo commands. Exception is Filebeat and Heartbeat (only if icmp is not configured)). Look at the soln docs as a source of truth for recommendations.
- MOVED TO ROADMAP Add topic [about exporting GeoIP info ](https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-geoip.html) to the documentation for all the Beats
- MOVED TO ROADMAP Add more about machine learning jobs. The setup command is documented, but we probably need to add info about required privileges plus maybe have some conceptual info. _Update 8/14: We've documented the privileges required. Reached out to dev to see if we need to say more in the Beats docs._

**Old Defects (open too long)**

REMOVED THE LIST HERE BECAUSE IT'S DOUBLE-TRACKING

**Defects related to developer docs**

REMOVED THE LIST HERE BECAUSE IT'S DOUBLE-TRACKING

**Future:**

- MOVED TO ROADMAP Add docs that are more task-based and focused on solutions, such as "Monitoring your infrastructure"
- REMOVED, COVERED BY https://github.com/elastic/beats/issues/7320. Refactor files in libbeat so that they can be more easily used by projects like apm. This includes moving the files that are not part of the Platform Reference into a directory called `include` under `libbeat\docs.

**Backlog:**

REMOVED ANYTHING HERE THAT IS ALREADY BEING TRACKED IN AN ISSUE

- [ ] Improve docs about running Beats on containers. Highlight support for getting logs and metrics from apps running on containers and bring all the topics into a single section. 
- [ ] Edit this content as time allows:
  - [ ] Metricbeat docs about the Kafka module.
  - [ ] Options added to output config doc since last edit (make sure all additions in #2597 have been edited)
- [ ] Packetbeat docs: Update New Protocol guide to describe the generator for Packetbeat. Include info about protocol analyzer generator. See https://github.com/elastic/beats/issues/1111.  
- [ ] Character encoding of source files
- [ ] Add topic about using Beats with Kafka?
- [x] Resolve https://github.com/elastic/beats/issues/861)
- [ ] Add new topic that explores Heartbeat deployment scenarios
- [ ] Add new topic that explains how Heartbeat works
- [ ] INVESTIGATE: Heartbeat: Add developer guide content when Heartbeat is further along
  
**Resolved**

- [x] Random edits:
- [x] Check FAQ meta issue and determine if any items from the issue should be added to the docs for the next release: https://github.com/elastic/beats/issues/3599  - [x] Config file format (backlog)
  - [x] Filebeat Modules tutorial - possibly rewrite as task-based topics
  - [x] Jolokia module docs
- [x] https://github.com/elastic/beats/issues/3340 (problem here might be that it's not obvious that processors can be applied to modules because we point off to another topic that describes the shared options. Instead of doing this, maybe we should put the config options in a shared file that gets pulled into the docs for all modules. https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-metricbeat.html
- [x] https://github.com/elastic/beats/issues/4268 (carlos said he might take a crack at this one)
- [x] https://github.com/elastic/beats/issues/4826 (need to document permissions for things like running ingest pipelines, setting up dashboards, index patterns, etc).
- [x] Clean up CLI docs so that the user sees one list of commands rather than a list separated into two sections (for beats that add their own options). This will involve some conditional coding to implement.
- [x] REMOVED Organize FAQ topics (either alphabetically or logically). See https://github.com/elastic/beats/issues/2258 - I'm removing this from my list in favor of more important work because it's low-value. Maybe someday. 

**6.4**

- [x] Add missing config info (paths) to the module docs for the Kibana and Elasticsearch modules: https://github.com/elastic/beats/issues/7835
- [x] [DeDe] Update dashboards. Need to show the latest version of the dashboards.
- [x] Follow up: document http endpoint. See https://github.com/elastic/beats/issues/3933. (backport to 6.2, if possible)
- [x] Follow up: document headers and ssl for metricsets. See https://github.com/elastic/beats/issues/3948 (backport to 6.2, if possible)
- [x] [DeDe] Filebeat system module startup instructions (Brandon) #4567 (backport to 6.2, if possible)
- [x] Document backoff setting. See https://github.com/elastic/beats/issues/5419. Fixed in https://github.com/elastic/beats/pull/6903
- [x] Old defect triage. Resolved 20+ defects.

**6.3**

- Make sure these get reviewed:
  - [x] Spooling to disk: https://github.com/elastic/beats/pull/6902
  - [x] https://github.com/elastic/beats/pull/7192
  - [x] Backoff settings: https://github.com/elastic/beats/pull/6903
- [x] [DeDe] Refactor prospector/intput docs. Add a list of prospectors/inputs in the Filebeat docs. Currently, we have a list of the  [type](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#_literal_type_literal), but it would be nice to have more visibility (maybe add a separate section about from where to get the logs, via udp, redis slow logs). Also see https://github.com/elastic/beats/pull/5944 for work related to renaming prospectors to inputs. The UDP input, in particular, needs more detail about configuration (see https://github.com/elastic/beats/pull/4452) Also see https://github.com/elastic/beats/issues/6122 and https://github.com/elastic/beats/issues/6375 and https://github.com/elastic/beats/pull/6266
- [x] Change title of topic about ingest node to say "Parse data" instead of "Parse logs" because "logs" does not make sense in all contexts where ingest node is used with beats.
- [x] Update Metricbeat getting started to show how to enable/disable by using the modules.d directory. See https://github.com/elastic/beats/issues/5325
- [x] [DeDe] Need Beats users to know about the additional commands for importing dashboards that are covered here: https://www.elastic.co/guide/en/beats/devguide/current/import-dashboards.html#import-dashboards. Right now the info is only obvious to developers...users need to know these options, too. Make it more clear in the Getting Started guides that these options exist. (backport to 6.2, if possible)
- [x] Add pointer to SSL settings in the Heartbeat monitor docs. See https://github.com/elastic/beats/issues/5599
- [x] Document beat user permission required to use ingest pipelines (backport to 6.0+, if possible). See https://github.com/elastic/beats/issues/4826
- [x] REMOVED Improve retrievability of reference info about config options. It's still too hard to find stuff. (We are improving the search, so I'm closing this one)

**6.0+**

Marking these items as 6.0 so we remember to backport them.

- [x] Clarify docs about config reloading. See https://github.com/elastic/beats/issues/5676.
- [x] [Tudor] Filebeat modules: Machine learning jobs. See https://github.com/elastic/beats/pull/4506. setup command is documented, but we probably need to add info about required privileges plus maybe have some conceptual info.
language indicating the version of kibana that's required to see the dashboards.
- [x] Follow up. Make sure that all PRs labeled as `needs_docs` have documentation, specifically:
  - [x] Use packetbeat protocols to publish beat.Event to new pipeline https://github.com/elastic/beats/pull/4599 (backport in #4878 )
  - [x] [urso] Convert heartbeat to new publisher pipeline https://github.com/elastic/beats/pull/4591 (backport in #4878 )

**6.1+** (list is a work-in-progress...created as a place holder)

- [x] Convert format of the Filebeat modules doc for Kafka, PostgresSQL, and Traefik (any modules added after 6.0) to match the other module docs. 
- [x] Conditionally code pre-release content. See https://github.com/elastic/beats/issues/5652

**6.2**

- [x] Make sure the docs get updated with info about the password keystore. See https://github.com/elastic/beats/pull/5687
- [x] Document autodiscover for kubernetes: https://github.com/elastic/beats/pull/6055. See https://github.com/elastic/beats/pull/6065

**Comment by dedemorton** [comment]
I'm closing this meta issue because I will no longer be using it to track the doc roadmap starting with Beats 6.5 and later.
