### ISSUE TITLE
Refactors for 7.0 (Breaking changes I want to make)

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#6106]
This is a running list of things to consider changing for 7.0. Feel free to add your own with attribution.

- [ ] Refactor the logging configuration (remove all the `to_files`, `to_syslog` settings etc.).
- [ ] Make Windows event log the default log output for Windows.
- [x] Set escape_html to false: elastic/beats#7445 elastic/beats#9914 @urso
- [x] Remove notion of **prospector** in the filebeat config. (@ph) PR https://github.com/elastic/beats/pull/8909
- [ ] Cleanup the methods used by `go-plugins`
- [ ] Default Template Mappings for IP fields are keyword type elastic/beats#7847 elastic/beats#9303  @ruflin
- [x] Remove ports from LS and Redis https://github.com/elastic/beats/issues/7881 elastic/beats#9934  @urso
- [x] Dissect `*` and named skip field change https://github.com/elastic/beats/issues/8054, PR At https://github.com/elastic/beats/pull/8750 (@ph)
- [x] Make beats log to journald by default on systems with systemd (add `-e` by default to systemd unit) (@jsoriano) elastic/beats#8942 
- [x] Dedot docker and k8s labels by default, ~or use [new queryable object type](https://github.com/elastic/elasticsearch/issues/25312) elastic/beats#9286~ (@kaiyan-sheng) 
- [x] Remove calls to `cfgwarn.CheckRemoved5xSetting(s)` (@ph) https://github.com/elastic/beats/pull/9002
- [ ] Remove 5.x dashboard directories, add 7 directories? elastic/beats#8927 
- [x] Assert any 'deprecated' comment in beats. (@ph)
- [ ] Change types to double in metricbeat modules for big gauges (@jsoriano, see #8991, #9271)
- [x] Rename `custom.*` to `journald.custom.*` fields (@kvch, already on master, needs changelog entry)
- [x] New location of registry of Journalbeat (@kvch, already on master, needs BC and changelog)
- [x] Deprecate fields/tags and introduce add_fields/add_tags processors https://github.com/elastic/beats/issues/4518 elastic/beats#9973 (@urso)
- [x] Remove ES 1.x and 5.x support in template/dashboard loading code
- [x] Unify module names for the same services elastic/beats#9395 (@jsoriano)
- [ ] Fixed any issues with the _xpack deprecation elastic/beats#9424

**Comment by ph** [comment]
Added https://github.com/elastic/beats/issues/7881

**Comment by jsoriano** [comment]
I have added a point to make beats log to journald by default when running on systemd, open to discussion, I'll open a PR.

@exekias I have added also a point about dedoting labels so we don't forget about this.

**Comment by ruflin** [comment]
I added a point about removing the 5.x dashboard directories to the above list. We should probably add a directory for 7 as the data structure for Kibana will change. @elastic/apm-server This might also effect you.

I put it on the service meeting agenda today.

**Comment by ph** [comment]
@jsoriano 

> I have added a point to make beats log to journald by default when running on systemd, open to discussion, I'll open a PR.

Can you create an issue for that, I don't know how big of a task it is.

**Comment by ph** [comment]
@ruflin I believe your ECS migration will take care of:  Default Template Mappings for IP fields are keyword type #7847

**Comment by ph** [comment]
@urso @ruflin @exekias I have added your name to the list of items you have added to this list, feel free to either remove the items or delegate the work.

**Comment by ruflin** [comment]
The IP stuff is not directly related to ECS but parts of it might be resolved through ECS.

**Comment by jsoriano** [comment]
@ph for the systemd unit logging to journald I mean something like #8942

**Comment by ph** [comment]
FYI I've added the following methods to fails on removed options, if you want to provide better feedback use them and it make it easy for us to remove them in 8.0.

https://github.com/elastic/beats/blob/74779e4b31880eb098fae97d5d29472a4f018e17/libbeat/common/cfgwarn/removed.go#L77-L85

**Comment by urso** [comment]
recent changes:
- [ ] Deprecate fields/tags and introduce add_fields/add_tags processors https://github.com/elastic/beats/issues/4518 (@urso)
- [ ] Remove ES 1.x and 5.x support in template/dashboard loading code

**Comment by urso** [comment]
I think we can close this one.

@andrewkroh @ruflin @ph @kaiyan-sheng @kvch @jsoriano Any of the items mentioned still open?

**Comment by jsoriano** [comment]
I didn't check if we should change some potentially big gauges from long to float, but I think this wouldn't be so breaking.

**Comment by kaiyan-sheng** [comment]
Nothing open on my side 👍For dedot we do have https://github.com/elastic/beats/issues/10773 to track some cleanup work.

**Comment by urso** [comment]
Not sure if all check boxes can be ticked off. But 7.0 is out for quite a while. Closing this.
