### ISSUE TITLE
Meta: Refactor prospector to input

### ISSUE THREAD

**Issue by ph** [elastic/beats#6122]
Track the ongoing task for refactoring the prospector to input.

- [x] Rename the prospector interface to the input interface https://github.com/elastic/beats/pull/6078
- [x] UDP prospector https://github.com/elastic/beats/pull/6118
- [x] Log prospector https://github.com/elastic/beats/pull/6120
- [x] stdin prospector https://github.com/elastic/beats/pull/6116
- [x] docker prospector https://github.com/elastic/beats/pull/6278
- [x] redis prospector https://github.com/elastic/beats/pull/6119
- [x] Convert modules yaml and json file to prospector and check for `event.type` https://github.com/elastic/beats/pull/6121
- [x] Update all the python test to not use any prospector words. https://github.com/elastic/beats/pull/6284
- [x] Update filebeat configuration yaml to remove any prospector words https://github.com/elastic/beats/pull/6290
- ~~update the documentation.~~ Move to #6375
- [x] create PR for changelog entries for all input.

**Comment by ph** [comment]
@ruflin I've created this high level list, the PRs link in this issue are marked as `in progress` until we merge #6078, all of them target a feature branch.

**Comment by ruflin** [comment]
Thx. Lets get #6078 in and from there, there is no way back 🎉

**Comment by ph** [comment]
@ruflin I've rebased all the PRs for this feature and will let the CI run them.

**Comment by ph** [comment]
@dedemorton concerning the point of updating the documentation to reflect the change from `prospector` to `input`, It will be a bit more than search and replace because we will have to redirect 302 some pages?

**Comment by ph** [comment]
@ruflin I've created the last few PRs. 💃

**Comment by ph** [comment]
Done! 🕺
