### ISSUE TITLE
Add scripts for the unified release process

### ISSUE THREAD

**Issue by tsg** [elastic/beats#633]
To improve the way all Elastic projects are being built, tested and released, a common interface needs to be implemented by all of them. This ticket is for tracking the changes needed for the beats project.

We need to provide the following scripts:
- `dev-tools/set_version VERSION`
  - Used for changing eg 2.0.0-SNAPSHOT to 2.0.0, or changing 2.0.0-SNAPSHOT to 2.0.1-SNAPSHOT
  - Just makes changes, doesn’t commit anything
- `dev-tools/get_version`
  - Returns the current version 
- `dev-tools/deploy`
  - Builds and tests the project from the current checkout
  - Deploys the project to a staging repository called `${PROJECT}_${VERSION}_${SHA}`
- `dev-tools/post_publish VERSION`
  - Performs any tasks that should be performed after a version has been published, eg adding bwc indices, setting version numbers on other branches etc.  
  - Only called from master which should know what to do with older branches

Tasks:
- [x] #629 Create a single place to update the version for all Beats to make it easier to automate. 
- [x] #634 Implement `set_version` and `get_version` scripts
- [x] #654 Move `beats-packer` in the main `beats` repository and adjust it to work based on the current folder rather than checking out from Github.
- [ ] #747 Implement `deploy` script
- [ ] Implement `post_publish` script

**Comment by christiangalsterer** [comment]
Would be great if the new process could also support community beats by defining an api/extension points/file structure convention. If a community beat would follow these conventions it could be build and released with this new process including support for different platforms.

**Comment by tsg** [comment]
@christiangalsterer I think that's a good idea, lets see if we can make it happen effort wise and from the messaging point of view. 

Btw, have a look at https://github.com/elastic/beats-packer, it (ab)uses travis-ci to build all the packages and uploads them to an S3 bucket. I think we could adapt that fairly easy to also do community beats.

**Comment by urso** [comment]
@mikemadden42 @andrewkroh You think we can close this one, or is there some more work left to do?
