### ISSUE TITLE
Add license paragraph to the header of each file

### ISSUE THREAD

**Issue by ph** [elastic/beats#6506]
With the opening of x-pack and the fact that the repository will now contain both files licensed
under Apache 2 and the Elastic EULA. I believe we should add license headers to our files. Doing
this will make sure there is no ambiguity, I think having a specific directory won't be enough.

Also, this will make consistent with Elasticsearch and Logstash x-pack, both of them are already doing this.

## Tasks

- [ ] Target .go, python, Makefile, maybe our YML?
- [ ] Add a new check to `make check` to make sure we don't publish new files without the header.
- [ ] Add a tool to add the headers automatically.

**Comment by andrewkroh** [comment]
FYI: I have a script for this that I use in other projects. https://github.com/elastic/go-sysinfo/blob/master/.ci/scripts/check_copyright.go

**Comment by ph** [comment]
@andrewkroh Awesome! I had something similar in ruby to add the license to the file, https://github.com/ph/license-header

**Comment by andrewkroh** [comment]
Headers and a CI check are added to the .go files in https://github.com/elastic/beats/pull/7391.

@tsg, do you know if we need headers on the other file types? Otherwise I think this issue can be closed.

**Comment by urso** [comment]
@andrewkroh @ph I assume we can close this one.

**Comment by ph** [comment]
ye
