### ISSUE TITLE
Ensure external defined fields don't break mapping

### ISSUE THREAD

**Issue by exekias** [elastic/beats#6546]
We recently introduced [safemapstr.Put](https://github.com/elastic/beats/pull/6434) as a way to ensure that field maps escaping our control (defined outside beats) don't break Elasticsearch mappings.

This is a meta issue to ensure all affected parts of the code has been updated to make use of it:

- [x] Kubernetes metadata & autodiscover #6490

- [x] Kubernetes module elastic/beats#6490
- [x] Docker metadata & autodiscover elastic/beats#6544
- [x] Docker module elastic/beats#6545
- [ ] Dropwizard
- [ ] Prometheus
- [ ] HTTP module
- [ ] Graphite
- [ ] Jolokia
- [ ] Munin
