### ISSUE TITLE
Set default metricsets for modules

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#6668]
Recently the feature to set default metricsets for a module were introduced. If a module is enabled an no metricsets are set, this list of metricsets is used. Now for each module the metricsets must be defined. In general this is all metricsets which are GA but there might be some exceptions like prometheus where the default one is only collector.

This issue is to track the progress on setting the defaults metricsets for all modules.

 * [x] aerospike https://github.com/elastic/beats/pull/6669
 * [x] apache https://github.com/elastic/beats/pull/6673
 * [x] ceph #6682
 * [x] couchbase #6683
 * [x] docker https://github.com/elastic/beats/pull/6718
 * [x] dropwizard https://github.com/elastic/beats/pull/6719
 * [x] elasticsearch https://github.com/elastic/beats/pull/6755
 * [x] etcd https://github.com/elastic/beats/pull/6756
 * [x] ~~golang~~
 * [x] graphite https://github.com/elastic/beats/pull/6757
 * [x] haproxy https://github.com/elastic/beats/pull/6758
 * [x] ~~http~~
 * [x] ~~jolokia~~
 * [x] kafka https://github.com/elastic/beats/pull/6759
 * [x] kibana https://github.com/elastic/beats/pull/6762
 * [x] kubernetes https://github.com/elastic/beats/pull/6764
 * [x] logstash https://github.com/elastic/beats/pull/6763
 * [x] memcached https://github.com/elastic/beats/pull/6765
 * [x] mongodb https://github.com/elastic/beats/pull/6766
 * [x] munin https://github.com/elastic/beats/pull/6767
 * [x] mysql https://github.com/elastic/beats/pull/6769
 * [x] nginx #6770 
 * [x] php_fpm #6768 
 * [x] postgresql #6761
 * [x] prometheus #6747 (and #6636)
 * [x] rabbitmq #6743 
 * [x] redis #6742
 * [x] system #6689 
 * [x] uwsgi #6688
 * [x] vsphere #6676
 * [x] windows #6675
 * [x] zookeeper #6674

**Comment by ruflin** [comment]
@jsoriano I started working from the top of the list.

**Comment by ruflin** [comment]
@jsoriano When changing each module I also directly check https://github.com/elastic/beats/issues/6672 So I add `enabled: true` to the reference config file (if there is one) and remove `enabled: *` from the short config. 

Other changes I do:

*  Add a note to the docs
* Add an entry to the changelog

**Comment by jsoriano** [comment]
I start from the bottom then :)

**Comment by ruflin** [comment]
All changelog entries which have to be added later. Lets use this comment to collect them.

```
- Set `container`, `cpu`, `diskio`, `healthcheck`, `info`, `memory` and `network` in docker module as default. {pull}6718[6718]
```

**Comment by ruflin** [comment]
I left the `golang` module untouched as it's still experimental and I think in this stage we should not have defaults.

**Comment by ruflin** [comment]
I checked off http and suggest not to add any defaults. For the json metricset it is always required to set a correct path as `/` is probably not the one that is expected. And for the server one not sure if the expectation of enabling the http module would be that a port is opened.

**Comment by ruflin** [comment]
Similar thing to the above applies for Jolokia and I also checked it off. The jmx metricset always requires manual configuration so it does not make much sense to have it as a default.

**Comment by ruflin** [comment]
Closing as all changes have been merged and changelog PR is open here https://github.com/elastic/beats/pull/6781
