### ISSUE TITLE
Restructuring: Clean up conditional coding in doc files

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#6813]
We need to:

- [x] Clean up existing conditional coding. For example, in some places, we use asciidoc attributes to render text conditionally. I haven't been very good at unsetting attributes after they are no longer needed within a book. To unset the attribute, we need to use: `:attribute_name!:` Once an attribute is defined within a book, it stays in scope until it's undefined. So some of the attribute definitions are redundant.  Currently this doesn't affect the output, but might in the future if we move all the content to a single book.
- [ ] Evaluate the conditional coding defined in the book. The books use a mixture of ifdef/ifndef statements and ifeval statements to conditionally render sections. The ifeval statements are based on beat names. I don't think we should be mentioning beat names in libbeat. We might want to change to use ifdef settings keyed off of attributes instead to keep the libbeat content beat-agnostic in all ways. 
- [ ] Document the conditional coding strategy because it's a bit of a tangled ball of yarn atm. 
- [ ] Make the conditional coding in libbeat Beat-agnostic...meaning that it should not refer to specific beats. Shared files in libbeat should use attributes, rather than Beat names, to set conditional sections.

**Comment by dedemorton** [comment]
We also need to document our conditional coding strategy (after it's cleaned up).

**Comment by dedemorton** [comment]
https://github.com/elastic/beats/pull/8811 contains some fixes related to this issue.

**Comment by dedemorton** [comment]
I'm no longer planning to make these changes in the individual Beats guides. The next generation all-in-one version of the shipper docs will not use as much conditional coding but follow cleaner principles.
