### ISSUE TITLE
Meta: Filebeat to consume syslog event

### ISSUE THREAD

**Issue by ph** [elastic/beats#6871]
Required steps for Syslog event parsing.

- [x] Extract of TCP elastic/beats#6700
- [x]  Extract of UDP elastic/beats#6439
- [x] Syslog Parser RFC3164 elastic/beats#6842 _(in review)_
- [x] Support TLS elastic/beats#6873
- [ ] Syslog Parser RFC5424 elastic/beats#6872
- [x] Support timezone parsing and add a settings for the timezone. elastic/beats#7057

**Comment by ph** [comment]
@kvch FYI, I have added timezone parsing to the meta issue.

**Comment by faec** [comment]
Syslog input now supports RFC5424
