### ISSUE TITLE
Improve metric collection and reporting

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7027]
Currently Beats report all metrics in one document. To report metrics more granular through different documents several changes to Beats metric collection and monitoring reporting are needed. This issue is to track the changes.

* [x] Introduce namespace to make collection of metrics to different API endpoints possible. https://github.com/elastic/beats/pull/6836
* [x] Report state stats: https://github.com/elastic/beats/issues/7521
* [ ] Add support for gauge metric types in Metricbeat to automate gauge detection on reporting
* [ ] Update existing monitoring output and remove module specific stats as they are reported separately
* [ ] Support reporting of arrays in Monitoring or manual definition on how data should be reported.
