### ISSUE TITLE
Central Management

### ISSUE THREAD

**Issue by exekias** [elastic/beats#7028]
Beats central management will allow users to configure & manage Beats centrally from Kibana. This is a meta issue to group all efforts for the first version of this feature:

Fixes: 

- [x] Bug when unenrolling a beats https://github.com/elastic/beats/issues/9452

Tasks:

- [x] Elasticsearch license checking and built-in roles: https://github.com/elastic/elasticsearch/issues/30493
   - [x] Need to backport these two PRs to `6.x` whenever the rest of Beats management is ready:
      * [x] https://github.com/elastic/elasticsearch/pull/30520
      * [x] https://github.com/elastic/stack-docs/pull/80
- [x] Beats initial enrollment https://github.com/elastic/beats/issues/7032
- [ ] Kibana management UI - kibana repo https://github.com/elastic/kibana/issues/18858
	- [x] https://github.com/elastic/kibana/issues/20837 Create beat enrollments screen(s)
	- [x] https://github.com/elastic/kibana/issues/20849 Create ui adapters
	- [x] https://github.com/elastic/kibana/issues/20844 table search and action controls
	- [x] https://github.com/elastic/kibana/issues/20834 Beats List Screen
	- [x] https://github.com/elastic/kibana/issues/20845 Shared Beat table
	- [x] https://github.com/elastic/kibana/issues/20836 Tag list screen
	- [x] https://github.com/elastic/kibana/issues/20843 Shared Tags table view
	- [x] https://github.com/elastic/kibana/issues/20838 Tag creation screen
	- [ ] https://github.com/elastic/kibana/issues/20835 Beat activity view
	- [x] https://github.com/elastic/kibana/issues/20840 Beat details - Config
	- [ ] https://github.com/elastic/kibana/issues/20846 config creation / view slide in view
	- [ ] https://github.com/elastic/kibana/issues/20842 Beat details - logs
	#### Tasks currently awaiting efforts from other teams
	- [ ] Activity view (awaiting logging UI in EUI)
	#### Overlay work (tasks that do not impede a working demo/beta)
	- [x] License check
	- [x] user permission check in UI and associated error messaging
- [x] Kibana license checking
- [x] Beats central management manager #8263
- [x] Basic telemetry for Beats central management https://github.com/elastic/beats/issues/7979 
- [x] Add docs https://github.com/elastic/beats/issues/8470

**Comment by exekias** [comment]
Pull request to merge Central Management branch to Beats master is now open: https://github.com/elastic/beats/pull/8559

I plan to backport elastic/elasticsearch#30520 & elastic/stack-docs#80 to `6.x` tomorrow, I may need a hand with that if you have some time @ycombinator :smiley_cat:

**Comment by ycombinator** [comment]
@exekias Backport PRs are up: https://github.com/elastic/elasticsearch/pull/34305 and https://github.com/elastic/stack-docs/pull/124.

**Comment by ph** [comment]
I will close this so we can track the remaining individual items instead.
