### ISSUE TITLE
Update kafka support

### ISSUE THREAD

**Issue by urso** [elastic/beats#7034]
- [x] Update kafka client library (sarama) #7025 
- [x] Test lz4 compression (kafka 0.11, 1.0) #4647,  #6414, #6540 
- [ ] Test with different kafka versions (set kafka version setting)
  - [ ] 0.9
  - [ ] 0.10
  - [ ] 0.11
  - [x] 1.0
  - [x] 1.1 #7655 
  - [ ] 2.0
- [ ] Metricbeat module enhancements #3005 
- [x] Update Documentation to include new versions #7665
