### ISSUE TITLE
Monitor the Elastic Stack with Metricbeat

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7035]
Make it possible to fetch logs from the Elastic Stack with Metricbeat.

This is a meta issue to track the ongoing work.

* [x] Kibana
  * [x] Kibana `stats` metricset: https://github.com/elastic/beats/pull/6746
  * [x] Add xpack config to all metricsets
    * [x] Add xpack structure to `stats` metricset for `kibana_stats` docs: https://github.com/elastic/beats/pull/7525
    * [x] Add xpack structure to `stats` metricset for `kibana_settings` docs: https://github.com/elastic/beats/pull/7664
  * [x] Verify parity in documents indexed internally by Kibana (current mechanism) with documents indexed by Metricbeat (new mechanism): https://github.com/elastic/elastic-stack-testing/issues/25
  * [x] Document how users can switch over from Kibana internal collection to Metricbeat for collecting+shipping metrics for X-Pack Monitoring: https://github.com/elastic/stack-docs/issues/86
* [x] Elasticsearch
  * [x] Ads `index_summary` metricset: https://github.com/elastic/beats/pull/6918
  * [x] Add `shard` metricset: https://github.com/elastic/beats/pull/7006
  * [x] Add `ml job` metricset: https://github.com/elastic/beats/pull/7196
  * [x] Add `index_recovery` metricset: https://github.com/elastic/beats/pull/7225
  * [x] Add `cluster_stats` metricset: elastic/beats#7638
  * [x] Add `ccr_stats` metricset: elastic/beats#8335
  * [x] Add xpack config to all metricsets
    * [x] Add xpack structure to `index` metricset: https://github.com/elastic/beats/pull/8260
    * [x] Add xpack structure to `index_summary` metricset: https://github.com/elastic/beats/pull/7102
    * [x] Add xpack structure to `shard` metricset: https://github.com/elastic/beats/pull/7097
    * [x] Add xpack structure to `ml_job` metricset: https://github.com/elastic/beats/pull/8129
    * [x] Add xpack structure to `index_recovery` metricset: elastic/beats#8106
    * [x] Add xpack structure to `cluster_stats` metricset: https://github.com/elastic/beats/pull/7810
    * [x] Add xpack structure to `ccr_stats` metricset: elastic/beats#8336
  * [x] Create new `xpack.monitoring.elasticsearch.collection.enabled` setting: https://github.com/elastic/elasticsearch/pull/33474
  * [x] Verify parity in documents indexed internally by Elasticsearch (current mechanism) with documents indexed by Metricbeat (new mechanism)
  * [x] Document how users can switch over from Elasticsearch internal collection to Metricbeat for collecting+shipping metrics for X-Pack Monitoring
* [x] Logstash
  * [x] Enhance `node` metricset for `logstash_state` documents: https://github.com/elastic/beats/pull/11506
  * [x] Enhance `node_stats` metricset for `logstash_stats` documents: https://github.com/elastic/beats/pull/11511
  * [x] Verify parity in documents indexed internally by Logstash (current mechanism) with documents indexed by Metricbeat (new mechanism): https://github.com/elastic/elastic-stack-testing/pull/250
  * [x] Document how users can switch over from Logstash internal collection to Metricbeat for collecting+shipping metrics for X-Pack Monitoring: https://github.com/elastic/logstash/issues/10920
* [x] Beats including APM-Server
  * [x] Make `GET /` Beats API return instance UUID: https://github.com/elastic/beats/pull/12180
  * [x] Add `stats` metricset with xpack structure: https://github.com/elastic/beats/pull/12181
  * [x] Add `state` metricset with xpack structure
  * [x] Verify parity in documents indexed internally by Beats (current mechanism) with documents indexed by Metricbeat (new mechanism): https://github.com/elastic/elastic-stack-testing/pull/249
  * [x] Document how users can switch over from Beats internal collection to Metricbeat for collecting+shipping metrics for X-Pack Monitoring: https://github.com/elastic/beats/issues/12647
* [x] Common
  * [x] Implement date base index naming for index: https://github.com/elastic/beats/pull/7586
  * [x] Assure that all metricsets (non-xpack path) report `service.name`

**Comment by tsullivan** [comment]
Does this meta issue also need to talk about removing the internal collectors from the products, and removing the _bulk endpoint from the ES monitoring plugin? If not, where is that being tracked?

**Comment by ycombinator** [comment]
> Does this meta issue also need to talk about removing the internal collectors from the products, and removing the _bulk endpoint from the ES monitoring plugin? If not, where is that being tracked?

Good question! Since @ruflin created the issue originally I'll defer to him on his intent, but my 2 cents would be to keep this issue for just making sure that Metricbeat **can** monitor the entire stack. Separately, in a (probably much later) release, we'll want to remove internal collectors and the `_bulk` endpoint from the ES monitoring plugin. 

If @ruflin agrees with this scoping, I can create a separate issue for the removal work.

**Comment by ruflin** [comment]
This issue is only to track the creation of the modules in Metricbeat. There is no issue to track the removal of the endpoint and I don't think we should have one yet as I'm not even sure anymore if we should do this short term. Let's take this discussion offline.

**Comment by robcowart** [comment]
Is there any targeted date for collecting all of the metric data available via the REST APIs with Metricbeat?

**Comment by ruflin** [comment]
There will be already a few modules and metricsets in the upcoming 6.4 release as experimental. More to come in the future.

**Comment by robcowart** [comment]
Good to hear. I am actually close to finishing some cron scheduled scripts to monitor a customer's cluster located close to you @ruflin. They are a platinum user, but had issues with the blocking behavior of X-Pack Monitoring resulting in outages. So I am moving them to a polling-based model.

Something more formal than my scripts, would definitely be the right long-term strategy. So I would prefer to move them towards a metricbeat solution.

Perhaps I will leverage the current metricbeat, and strip out of my scripts the values that it already provides. That way we can transition them over time as new functionality becomes available.

What are the thoughts here around adding dashboards, alerting and ML jobs for these metricsets? I am happy to contribute what I create for this customer.

**Comment by ruflin** [comment]
Glad to hear it becomes of use for you and the user. Will get back to you about the dashboards, ml jobs contribution in the next days. Thanks for considering it.

**Comment by pickypg** [comment]
Hi @robcowart 

> They are a platinum user, but had issues with the blocking behavior of X-Pack Monitoring resulting in outages.

Could you elaborate on what you mean here? X-Pack monitoring is internally a polling based solution where, every interval (10s by default), we collect the relevant stats by polling the various APIs, so I am perhaps misinterpreting what you mean here, but I want to be sure that we do not have a problem.

> What are the thoughts here around adding dashboards, alerting and ML jobs for these metricsets?

In the long run, we may go in this direction, but early on our efforts are focused on enabling the curated UI experience. Unfortunately, that means that attempting to simultaneously support separate dashboards would slow down our shift toward Metricbeat / metricsets as we would be forced to validate every change against them. I would be particularly happy to revisit this discussion point once we get the workflow into Metricbeat.

**Comment by ycombinator** [comment]
All items in the checklist are now completed. Closing this issue.
