### ISSUE TITLE
Fetch logs from the Elastic Stack with Filebeat

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7036]
Make it possible to fetch logs from the Elastic Stack with Filebeat.

This is a meta issue to track the ongoing work.

* [x] Elasticsearch https://github.com/elastic/beats/issues/5301
* [x] Kibana: https://github.com/elastic/beats/pull/7052
* [x] Logstash https://github.com/elastic/beats/pull/5481
* [ ] APM-Server
* [ ] Check that all filesets report `service.name`

**Comment by urso** [comment]
@ycombinator Any idea if we can close this or tick off some checkboxes?

**Comment by ycombinator** [comment]
Thanks for the assignment and ping @urso. I ticked off some checkboxes :) and will look into the remaining items.

**Comment by jlind23** [comment]
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.
