### ISSUE TITLE
[Meta Issue] Increase Kubernetes monitoring coverage

### ISSUE THREAD

**Issue by exekias** [elastic/beats#7058]
We have support for Kubernetes metrics from kubelet & most of kube-state-metrics, we should increase module coverage to also support Kubernetes internal services:

- [x] apiserver elastic/beats#7059
- [x] kube-proxy elastic/beats#10431
- [x] kube-scheduler
- [x] CoreDNS (1.11) elastic/beats#10432
- [x] kube-controller-manager
- [x] etcd https://github.com/elastic/beats/issues/9093

Filebeat:

- [x] Support /var/log/containers path for non-docker scenarios https://github.com/elastic/beats/issues/8988

Metricbeat:

- [x] Implement service account token based HTTP authorization elastic/beats#7518

Logs. Review where it makes sense to implement a module, for sure we want:

- [ ] [Auditing](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/)

Metadata processor

- [x] Include owner object reference info (replication controller, deployment, etc) elastic/beats#7231

- [x] Seamless integrate it with kubernetes metricsets: elastic/beats#7148

As for [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/tree/release-1.3/Documentation):

- [x] Resource Quotas elastic/beats#6659
- [ ] ConfigMap
- [ ] Secret
- [ ] Daemonset
- [ ] Replication Controller
- [ ] Volume & Volume Claims, also check elastic/beats#6977 
- [ ] Job
- [x] CronJob https://github.com/elastic/beats/issues/12183
- [ ] Service
- [ ] HPA

Review:
- [x] elastic/beats#6638

- [x] elastic/beats#6639

Also we should consider joining these with kubelet sourced metrics, for total correlation: elastic/beats#6637

**Comment by f0** [comment]
#6659

**Comment by exekias** [comment]
Not yet, although it may make sense to include it on the list. Having that this is a new component, it may take some time until we see it in production scenarios. We cannot rely on `metrics-server` being available as of today.

Definitely we will fetch metrics from it at some point

**Comment by f0** [comment]
@exekias   does KubeDNS includes Coredns? (new default with 1.11)

**Comment by exekias** [comment]
@f0 I still have to take a look, but it looks like the answer is yes, I'm including it in the list so we don't forget :)

**Comment by eloyekunle** [comment]
The tasks look good. Going to pick one of this to contribute to.

**Comment by sorantis** [comment]
Latest groups of metrics exposed by [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics):
-  [CronJob Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cronjob-metrics.md)
-  [DaemonSet Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/daemonset-metrics.md)
-  [Deployment Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/deployment-metrics.md)
-  [Job Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/job-metrics.md)
-  [LimitRange Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/limitrange-metrics.md)
-  [Node Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/node-metrics.md)
-  [PersistentVolume Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/persistentvolume-metrics.md)
-  [PersistentVolumeClaim Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/persistentvolumeclaim-metrics.md)
-  [Pod Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md)
-  [Pod Disruption Budget Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/poddisruptionbudget-metrics.md)
-  [ReplicaSet Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/replicaset-metrics.md)
-  [ReplicationController Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/replicationcontroller-metrics.md)
-  [ResourceQuota Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/resourcequota-metrics.md)
-  [Service Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/service-metrics.md)
-  [StatefulSet Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/statefulset-metrics.md)
-  [StorageClass Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/storageclass-metrics.md)
-  [Namespace Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/namespace-metrics.md)
-  [Horizontal Pod Autoscaler Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/horizontalpodautoscaler-metrics.md)
-  [Endpoint Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/endpoint-metrics.md)
-  [Secret Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/secret-metrics.md)
-  [ConfigMap Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/configmap-metrics.md)
-  [Ingress Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/ingress-metrics.md)
-  [CertificateSigningRequest Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/certificatessigningrequest-metrics.md)
-  [VerticalPodAutoscaler Metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/verticalpodautoscaler-metrics.md)

**Comment by FedeBev** [comment]
Hi there, could you confirm that `state_deamonset` or something similar to replicaset state is not supported yet? 
Did I get it right?
Thanks

**Comment by ChrsMark** [comment]
> Hi there, could you confirm that `state_deamonset` or something similar to replicaset state is not supported yet?
> Did I get it right?
> Thanks

This right! It is not supported yet.

https://github.com/elastic/beats/issues/17010
