### ISSUE TITLE
Remove deprecated event and reporting interfaces from Metricbeat

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7099]
To clean up the Metricbeat and simplify it the old interfaces should be removed. This issue is to track the removal. 

* [ ] Remove `mb.PushReporter` interface
  * [ ] Convert http/server metricset to PushReporterV2 https://github.com/elastic/beats/pull/7100
  * [ ] Convert graphite/server metricset to PushReporterV2
  * [ ] Convert kubernetes/event metricset to PushReporterV2
* [ ] Remove `mb.Reporter` interface
* [ ] Remove `mb.ReportingMetricSet` interface
* [ ] Remove `mb.PushMetricSet` interface

**Comment by ycombinator** [comment]
@ruflin Just want to double check that this issue is still relevant?

**Comment by ruflin** [comment]
@ycombinator Don't know how many of the above already happened, but I think we should still clean this up to remove technical debt, but I let @exekias to chime in here.
