### ISSUE TITLE
Improve dashboard handling, exporting, loading

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7262]
This meta issue is to track changes related to Dashboard loading

* [x] Add support to export dashboards to each beat https://github.com/elastic/beats/pull/7239
* [x] Decode versioned JSON dashboards for better PR reviews
  * [x] Implement decoding / encoding script for collection
  * [x] Modify dev dashboard exporter script https://github.com/elastic/beats/pull/7241
  * [x] Apply decoding to each Beat
    * [x] Metricbeat https://github.com/elastic/beats/pull/7224
    * [x] Heartbeat https://github.com/elastic/beats/pull/7260
    * [x] Auditbeat https://github.com/elastic/beats/pull/7259
    * [x] Filebeat https://github.com/elastic/beats/pull/7251
    * [x] Packetbeat
    * [x] Winlogbeat
* [x] Create new directory for generated Kibana files to allow global directory for cross module dashboards and unify handling of dashboards. https://github.com/elastic/beats/pull/7261
* [x] Apply new dashboard collection to Beats
    * [x] Metricbeat
    * [x] Heartbeat
    * [x] Auditbeat
    * [x] Filebeat
    * [x] Packetbeat
    * [x] Winlogbeat

**Comment by ruflin** [comment]
Closing as now all dashboards in Beats are in the decoded format.
