### ISSUE TITLE
Implement state reporting for Beats

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#7521]
This is a meta issue to track the implementation of the state reporting to the API and X-Pack Monitoring

* [x] Metricbeat modules https://github.com/elastic/beats/pull/7075
  * [x] Elasticsearch template https://github.com/elastic/elasticsearch/pull/31809
* [x] Filebeat modules https://github.com/elastic/beats/pull/7532
* [x] Filebeat inputs https://github.com/elastic/beats/pull/7530
* [x] Output name https://github.com/elastic/beats/pull/7522
* [ ] Queue name https://github.com/elastic/beats/pull/7537
* [x] Host info https://github.com/elastic/beats/pull/7508
* [x] Update templates: https://github.com/elastic/elasticsearch/pull/32085
* [ ] Update template version https://github.com/elastic/elasticsearch/pull/32088

The reported event looks as following:

```
{
  "beat": {
    "name": "ruflin"
  },
  "host": {
    "architecture": "x86_64",
    "name": "ruflin",
    "os": {
      "build": "17E202",
      "family": "darwin",
      "platform": "darwin",
      "version": "10.13.4"
    }
  },
  "input": {
    "count": 1,
    "names": [
      "redis"
    ]
  },
  "module": {
    "count": 3,
    "names": [
      "system"
    ]
  },
  "output": {
    "name": "elasticsearch"
  },
  "queue": {
    "name": "mem"
  },
  "service": {
    "id": "0e1b1913-73db-4512-b17a-8209fa45eaa4",
    "name": "metricbeat",
    "version": "7.0.0-alpha1"
  }
}
```

For now processor were left out as they need some additions to the interface to be reported.

This ticket is kept open until the changes are also applied to the Elasticsearch template and all PR's are merged.

**Comment by ruflin** [comment]
The reported event looks as following:

```
{
  "beat": {
    "name": "ruflin"
  },
  "host": {
    "architecture": "x86_64",
    "name": "ruflin",
    "os": {
      "build": "17E202",
      "family": "darwin",
      "platform": "darwin",
      "version": "10.13.4"
    }
  },
  "module": {
    "count": 3,
    "names": [
      "system"
    ]
  },
  "output": {
    "name": "elasticsearch"
  },
  "queue": {
    "name": "mem"
  },
  "service": {
    "id": "0e1b1913-73db-4512-b17a-8209fa45eaa4",
    "name": "metricbeat",
    "version": "7.0.0-alpha1"
  }
}
```

For now processor were left out as they need some additions to the interface to be reported.

This ticket is kept open until the changes are also applied to the Elasticsearch template and all PR's are merged.

**Comment by hiiamok** [comment]
Hi,

we are experiencing a problem since the implementation of the state reporting.
We are using "Filebeat" and "Metricbeat" inside one Application. 
During the initialisation a panic is thrown, because the name "module" is used in both beats.
Error Message: "panic: name module already used"

Can you suggest a workaround or possible fix?
Would it be possible to change the name to something unique, or instead of throwing a panic just returning an error?

Best regards

**Comment by cachedout** [comment]
@hiiamok IMHO, it might be better to file this as a brand-new issue along with steps to reproduce it so we can more easily troubleshoot what's going on here.
