### ISSUE TITLE
[Meta] Add beatless to run beat on serverless infrastructure

### ISSUE THREAD

**Issue by ph** [elastic/beats#7880]
Beatless is a new beat designed to beat lightweight and be able to run on existing cloud infrastructure. The first version will focus on AWS. The development of the feature is currently under x-pack sub folder. And the work is merged into a feature branch https://github.com/elastic/beats/tree/feature/beatless

### Features:
  - First providers AWS and Local
  - Accepts new events from:
    - STDIN (mostly used for easier testing)
    - Cloudwatch
    - Kinesis
    - API Gateway
  - The architecture should support running multiple functions concurrently but provider implementation can restrict that.
  - A provider is a singleton in the configuration.

### Tasks:
- [ ] Enforce Elastic license on files
- [ ] Display if the beat is OSS or not.
- [ ] Xpack binaries https://github.com/elastic/beats/pull/7783
- [ ] Basic beats skeleton https://github.com/elastic/beats/pull/7837
- [ ] implement license check, currently beatless require a basic license on the target cluster. This will be cached in memory and periodically checked.
- [x] Create a global registry https://github.com/elastic/beats/pull/7392
- [ ] Wrap the global registry into a beat specific registry handling types assertion.
- [ ] Local provider
  - [ ] STDIN function type
- [ ] Add support for a sync publisher, most function SDK expect the ack when the function return.
- [ ] AWS lambda provider.
    - [ ] Api Gateway
        - [ ] integration tests
    - [ ] Cloudwatch
        - [ ] integration tests
    - [ ] Kinesis
        - [ ] integration tests
    - [ ] Make the integration test run on Travis (assert on cloud?)
- [ ] Support modules
- [ ] Support processors
- [ ] Add metadata from the provider.

#### Medium priority
- [ ] CLI command to push the config + artifact to the provider.

#### Low priority
- [ ] Disable features for faster startup
    - [ ] Seccomp
    - [ ] Logging to file
    - [ ] Remove unsupported spooling to disk
    - [ ] Remove unsupported

### Nice to have:
  - [ ] cloudtrail support
  - [ ] Wrap some heartbeat monitor into lambda beat.
  - [ ] better local validation
  - [ ] GCP PoC
  - [ ] add a post compile check for the package size. (Some provider impose limits on size)
  - [ ] Allow to read the DLQ https://docs.aws.amazon.com/lambda/latest/dg/dlq.html

### Config Architecture:

```yaml
beatless.provider.aws:
  enabled: true
  # .... Provider configuration
  # Credentials for pushing the function.
  functions:
    - type: cloudwatch

      stream: messages
      fields:
        logs_type: cloudwatch-messages
      limits:
        timeout: 5s
        concurency: 20
    - type: kinesys
      name: kinesis-ingress
      stream: firehose
    - type: s3
      bucket: logs.elastic.co

output.elasticsearch:
  host: abc
  username: elastic
  password: abc123
```

## Licensing of Serverlessbeat
- [ ] Do we want to restrict the usage of Serverlessbeat for ES cluster with the X-Pack Basic license (https://github.com/elastic/dev/issues/1013)

**Comment by ph** [comment]
Functions can embed customs processors.

**Comment by ph** [comment]
Added a notes concerning monitory of beatless, it actually make sense that we use a module which will be preconfigured to work on event of data. 

Probably a custom processor that will drop events that we don't need and just extract the monitoring data.

**Comment by ph** [comment]
Before working on the CLI integration I'd like to have some integration tests done, in #8170 we support the following trigger on AWS: SQS, Cloudwatch Logs, Kinesis and the API Gateway.

The following are the steps required to be able to run and asserts that a function is actually doing the right thing.

- build beatless
- push beatless to AWS
- Create data for the specific trigger (SQS, Kinesis, ApiGateway)
- teardown the function
- Assert the data in ES


The above will required:
- AWS credentials available in the test environment
- An ES cluster available.

If possible I want something close to how testing modules works in Filebea.

**Comment by ph** [comment]
@tsg @monicasarbu The todo items in this issue are up to date.

**Comment by ph** [comment]
Currently working on integration tests
