### ISSUE TITLE
[Filebeat][meta] Add Suricata module

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#8153]
This is the meta issue to track the task of adding a new Filebeat module that reads the [Suricata EVE JSON output](https://suricata.readthedocs.io/en/latest/output/eve/eve-json-format.html).

- [x] Add ECS fields to fields.yml. (@adriansr) #8313 
  - [x] A convenient way to import this would be nice (like simply copying a fields-ecs.yml file to `_meta/`). https://github.com/elastic/ecs/pull/108
- [x] For Filebeat 7.0 rename `source` to `?` in accordance with ECS. (@adriansr) #8313
  - According to the [ECS logging use case](https://github.com/elastic/ecs/blob/973c93f5a241675c742790ffbf1097e24a6b835e/use-cases/logging.md) ~~this field should be `source.path`.~~ (Is this correct?)
  - Finally decided on `log.source` to better fit the tcp/syslog inputs.
- [x] Package X-Pack modules with the Elastic licensed Filebeat version. #8403 #8615
- [x] Add and test the Suricata module.
  - https://github.com/elastic/beats/pull/8089
  - Add a way to verify from Go that a JSON document's fields are contained in fields.yml. We will be validating the document after it has gone through the Ingest Node pipeline and is queried from ES. -> #8476
  - Document that the module is only included in Elastic licensed packages.
- [ ] Write documentation for the module that explains how to set it up and use it.
  - [x] Define tested Suricata versions.
- [x] Backport module to 6.x and work-around the conflict of the ECS `source.ip` with the Filebeat 6.x `source` field.

**Comment by andrewkroh** [comment]
@ruflin Can you help me in determining what Filebeat's `source` should be renamed to.

@andrewvc Could `mapval` be used to validate that a documents fields are contained in fields.yml as described above? Apart of the python system tests, is anyone aware of any fields.yml validation code in Go?

**Comment by ruflin** [comment]
`source` should become `file.path` I think. I need to update the use case.

@andrewkroh For the field validation I remember @simitt put something together for apm-server quite some time ago.

**Comment by simitt** [comment]
We have a test [PayloadAttrsMatchFields](https://github.com/elastic/apm-server/blob/e0e849c3e94042db07573f0c1e6684439f29b88e/tests/fields.go#L46) checking that attributes from the payload are indexed except for specific exceptions and a [KeywordLimitation](https://github.com/elastic/apm-server/blob/master/tests/json_schema.go#L168) test checking that every string indexed as `keyword` follows the 1024 default length restriction in the json spec. Those tests are applied e.g. for [transactions](https://github.com/elastic/apm-server/blob/master/processor/transaction/package_tests/attrs_test.go). There you also find more tests regarding allowed/forbidden/required/optional attributes.

**Comment by ruflin** [comment]
Update: Looks like I missed the first link from @simitt which contains the code on the apm-server side to check the fields: https://github.com/elastic/apm-server/blob/e0e849c3e94042db07573f0c1e6684439f29b88e/tests/fields.go#L46

**Comment by adriansr** [comment]
Hi @ruflin, any update on the new `source` mapping for Filebeat?

You suggest `file.source`, but what about when input is not from a file? `tcp`, `syslog` etc? Currently `source` is the IP address for example.

**Comment by tsg** [comment]
Adding the module checklist:

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] Integration tests
* [ ] System tests
* [ ] Automated checks that all fields are documented
* [ ] Documentation
* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Fields follow naming conventions: https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html
* [ ] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
