### ISSUE TITLE
[meta] pcap file improvements

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#8255]
Users regularly use .pcap file ingestion in packetbeat even though it is described as "useful only for testing Packetbeat" in the docs. A few improvements could address the common pitfalls users face:
- [ ] in flight / partial transactions are lost once the end of the pcap file is reached.
- [ ] (discuss) command-line switch to set `@timestamp` from PCAP timestamp (i.e. --pcap-time)
- [ ] New command-line option (e.g. --pcap file.pcap) that is equivalent to `-t --pcap-time -I file.pcap`
- [ ] Investigate common warning `Time in pcap went backwards: 0`.

**Comment by adriansr** [comment]
The rationale behind the new `--pcap` option would be to add an option with the appropriate settings for production use. I'm mostly worried about users not using `-t` option and complaining about the ingestion taking too long. Simulated-time ingestion only makes sense for testing.

**Comment by adriansr** [comment]
> in flight / partial transactions are lost once the end of the pcap file is reached.
Seems that this could be mitigated increasing the value of `packetbeat.shutdown_timeout`.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
According to https://discuss.elastic.co/t/packetbeat-something-wired-with-warn-time-in-pcap-went-backwards/72142/3, the "Time in pcap went backwards" warning can occur on TCP retransmits.

**Comment by marbeauregard** [comment]
Can i get some assistance with the following error message:

root@ubuntu:/home/zeekelk/Downloads/PCAP-03-11# packetbeat run -I SAT-03-11-2018_0145 -t
Exiting: Sniffer main loop failed: Sniffing error: Read Error
