### ISSUE TITLE
[META] Heartbeat Next Phase

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#8393]
This meta issue tracks the next phase of HB development

### Beat

- [ ] Centralized Config
- [ ] Autodiscovery - Basics
- [ ] Telemetry
- [ ] AWS Autodiscovery 
  - Note: Existing issue on cloud autodiscovery https://github.com/elastic/beats/issues/8282 

### UI

- [ ] Dashboard Improvements
- [ ] Add Data in Kibana
- [ ] Centralized config integration
- [ ] Just the minimal things to make heartbeat an option
- [ ] Initial spec for heartbeat app UI
- [ ] Setup of heartbeat app in kibana feature branch

**Comment by andrewvc** [comment]
We'll track this in another tool.
