### ISSUE TITLE
Add docs and edit strings for Beats Central Management

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#8470]
We need to update the documentation for the new Beats Central Management feature: https://github.com/elastic/beats/issues/7028

To do list for beta:

- [x] Review UI text strings and messages.
  - [x] Make text strings clear, concise, and consistent [Gail]
  - [x] Suggest changes to improve usability and general user experience for Beats users [DeDe]
- [x] Add topic about Beats Central Management to the Kibana docs (high-level overview content parallel to what we provide for similar UIs). [DeDe]
- [x] Add topic(s) about Beats Central Management to the Beats docs (deep dive on concepts and tasks required to use the UI). [DeDe]
- [x] Update getting started and reference content about configuration to include links to the docs about central management [DeDe]
- [x] Removed from this list; now tracked in https://github.com/elastic/beats/issues/9363. ~Improve docs about config settings to make sure they play well with the new UI (best effort, stretch goal). [DeDe]~ [removing because this is a longer term goal]
- [x] Update security docs to show requirement for beats_admin role. [DeDe]
- [x] Removed from this list; now tracked in https://github.com/elastic/beats/issues/9001: ~Document public API (best effort). First effort might be manual, but we would like to generate these docs eventually.~

**Comment by exekias** [comment]
I've started a new branch to work on initial docs in the beats side: https://github.com/elastic/beats/compare/master...exekias:cm-docs?expand=1

**Comment by dedemorton** [comment]
PR with the doc additions is here: https://github.com/elastic/beats/pull/9054

**Comment by dedemorton** [comment]
Closing this issue. The remaining items are tracked in issue #9363 and #9001.
