### ISSUE TITLE
Beats doc refactoring and restructuring

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#8493]
This meta issue lists all refactoring efforts that are required. These efforts might impact projects that reuse content from libbeat:

**libbeat**

- [ ] ~Break source file for outputs (outputs.asciidoc) into multiple files: #8492~
- [x] Break processor file into multiple files.  https://github.com/elastic/beats/pull/14410
- [ ] Move command reference to top level in the navigation: #7739
- [ ] Clean up conditional coding in doc files: #6813
- [x] Remove conditional coding for attributes that are no longer used by APM.
- [ ] Clean up TOC entries for config sections: #6188
- [x] Cleanup and reconcile shared attribute definitions used in the docs: https://github.com/elastic/beats/issues/6144
- [ ] Organize libbeat files logically into folders and rename for consistency: https://github.com/elastic/beats/issues/8496
- [ ] Improve organization of the processor docs: https://github.com/elastic/beats/issues/7486
- [ ]  Fix the part/chapter structure of the books: #8494
- [ ]  Clean up product references (use attributes)

**Heartbeat**

- [x] Break heartbeat monitor docs into separate sections: #7234

**Metricbeat**

- [ ] Improve config docs for modules by using shared file for common options: #7160

**Functionbeat**

- [x] Create separate topics for different function types: https://github.com/elastic/beats/issues/13908

**All beats**
- [x] Use attribute to resolve libbeat paths: use attribute to resolve libbeat paths: https://github.com/elastic/beats/issues/8578
- [ ] Improve reference content about configuration options (so it works better with CM UI). https://github.com/elastic/beats/issues/9363
- [ ] Refactor attributes to use consistent naming and provide consistent IDs settings. See the related comment here: https://github.com/elastic/beats/pull/13818#issuecomment-535889985

**Comment by dedemorton** [comment]
Closing this meta issue because we will not be refactoring the Beats documentation.
