### ISSUE TITLE
Transition Beats to ECS

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#8655]
With 7.0 Beats will transition to ECS: https://github.com/elastic/ecs This meta issue is to track all changes needed in Beats. The list will be extended over time

# Migration Strategy 

The overall migration strategy is to add a alias layer to 7.x which is opt-in to be backward compatible with 6.x data if needed. For some of the core fields used in the Infra / Logging UI aliases are introduced in 6.x for the 7.x data.

* [x] Introduce migration file to track migration https://github.com/elastic/beats/pull/9381

## 6.x (6.6 / 6.7)

* [x] Add field aliases for 1-1 for Infrastructure UI and Logs UI https://github.com/elastic/beats/pull/9283
  * [x] beat.hostname -> host.hostname
  * [x] docker.container.name -> container.name
  * [x] docker.container.image -> container.image
  * [x] meta.cloud.availability_zone -> cloud.availability_zone
  * [x] meta.cloud.machine_type -> cloud.machine.type
  * [x] meta.cloud.project_id -> cloud.project.id
  * [x] meta.cloud.provider -> cloud.provider
  * [x] metricset.module -> dataset.module
  * [x] fileset.module -> dataset.module
* [x] Add breaking changes fields
  * [x] event.dataset for Metricbeat https://github.com/elastic/beats/pull/9393
  * [x] event.dataset for Filebeat https://github.com/elastic/beats/pull/9457
  * [x] event.duration for metricbeat (unit change) https://github.com/elastic/beats/pull/9393
  * [x] log.source.ip & log.path https://github.com/elastic/beats/pull/9435
* [x] Correctly represent aliases in the asciidoc
  * [x] Backport https://github.com/elastic/beats/pull/9498

## 7.0

* [x] Remove old fields which had a 1-1 mapping like beat.hostname
* [x] Make `agent.*` overwritable for apm-server https://github.com/elastic/beats/pull/9952
* [x] Make sure all alias from the migration contain the `migrate: *` flag

# Fields changes

* [x] Introduce structured file to document field migration for later automated migration: https://github.com/elastic/beats/pull/8878
* [x] Import ECS 1.0.0 Beta 2 field definitions
  * [x] Direct attempt elastic/beats#9014 (may be discarded)
  * [x] Update http field set elastic/beats#9645
  * [x] Import various small changes from ECS Beta 2 elastic/beats#9738
  * [x] Update `os` field set in all relevant places elastic/beats#9763
  * [x] Import the geo field set
* [x] ~~Some ECS field definitions casually refer to other ECS Readme sections in the Beats docs. We need to address this better~~ Moved to later.
* [x] Import https://github.com/elastic/ecs/pull/308, where user.group becomes the `group` field set elastic/beats#10275
* [x] Review all fields using `text` indexing. All fields except `message` and `error.message` should be `keyword`. If a field requires `text` indexing, it should be added as a multi-field under the `keyword` field.
  * [x] Review or adjust Auditbeat. https://github.com/elastic/beats/pull/10518
  * [x] Review or adjust Filebeat. https://github.com/elastic/beats/pull/10372
  * [x] Review or adjust Heartbeat. https://github.com/elastic/beats/pull/10518
  * [x] Review or adjust Journalbeat. https://github.com/elastic/beats/pull/10518
  * [x] Review or adjust libbeat.
  * [x] Review or adjust Metricbeat. elastic/beats#10318 
  * [x] Review or adjust Packetbeat. https://github.com/elastic/beats/pull/10518
  * [x] Review or adjust Winlogbeat. https://github.com/elastic/beats/pull/10373

## Libbeat adjustments

* [x] Rename beat.name to agent.type https://github.com/elastic/beats/pull/8873 
* [x] Rename beat.version to agent.version https://github.com/elastic/beats/pull/8873
* [x] Rename beat.hostname to agent.hostname https://github.com/elastic/beats/pull/8873
* [x] Introduce config option to enable / disable alias https://github.com/elastic/beats/pull/9805
* [x] Add `agent.id` and `agent.ephemeral_id` elastic/beats#9404

### Beats processors

* [x] Review all processors for necessary changes, and list changes required below
* [x] add_cloud_metadata https://github.com/elastic/beats/pull/9265
  * [x] Remove nesting under `meta.*`, `cloud.*` should be at the top level.
  * [x] Rename to cloud.instance.id
  * [x] Rename to cloud.machine.type
  * [x] ECS doesn't have cloud.project_id or project.id. Should we address this in ECS or leave project_id as is? No
* [x] add_docker_metadata https://github.com/elastic/beats/pull/9412
  * [x] Use the field set `container.*` at the top level, not nested under `docker.*`, and make sure to review field names vs ECS https://github.com/elastic/beats/pull/9412
* [x] Decide what to do with docker.container.labels as alias does not work here (object)
  * Decision is we don't migrate the labels, it's a breaking change.
* [x] add_host_metadata (fields already in ECS schema, some additional fields like build or codename exist which is ok)
  * [x] Use host.hostname https://github.com/elastic/beats/pull/9943
  * [x] Add `host.os.name` elastic/beats#9405
* [x] add_locale https://github.com/elastic/beats/pull/9458
  * [x] We've taken out timezones as offsets in seconds from ECS. But we still need to add the tz name to ECS. We may want to change the default? https://github.com/elastic/beats/pull/9458
* [x] add_process_metadata https://github.com/elastic/beats/pull/9949
  * the names seem to match very well, but some fields are missing from ECS. We should add them for 7.0.0 and make sure Beats is in sync. (additional fields are ignored for now)
* [x] dns (no option default values to change)

## Auditbeat

* [x] Add missing ECS field defs used by Auditbeat elastic/beats#9318
* [x] Review current Auditbeat GA modules for ECS compatibility elastic/beats#10111
  * [x] Perform minor changes outlined in this review
* [x] Review new SecOps Auditbeat modules for ECS compatibility

## Filebeat

* [x] The redis input has a ` read_timestamp` which should be changed to `event.created` elastic/beats#9924

## Filebeat modules

* [x] Rename fileset.name to event.dataset https://github.com/elastic/beats/pull/8879
* [x] Rename fileset.module to event.module https://github.com/elastic/beats/pull/8879
* [x] Convert `source` field to ECS https://github.com/elastic/beats/pull/8902
* [x] Rename `offset` to `log.offset` https://github.com/elastic/beats/pull/8923
* [x] Rename `source_ecs` to `source` elastic/beats#8983
* [ ] How do we migrate lower case for http.request.method?
* [x] Changes likely to affect multiple modules at once
  * [x] Output timestamp when Filebeat read an event to `event.created`, and not `read_timestamp` elastic/beats#10139
  * [x] Use `[source|destination].address` for the ambiguous address (prior to parsing an IP, socket, domain) everywhere elastic/beats#10141
  * [x] Transition HTTP size and timing metrics to use ECS fields elastic/beats#10188
  * [x] [Optional] Finish event duration migration: remove all old fields, mention them in ecs-migration as `alias: false` and with `scale:`, use the shared Ingest Node code, to reduce compilations. elastic/beats#10274
  * [x] Finish transition to ECS of the user_agent output: get rid of all the field renames in the pipelines. 10472, #10441
  * [x] Remove deprecated field `url.hostname`. #10469

### Filebeat Module migrations

* [x] apache2
  * [x] access elastic/beats#9245
  * [x] error elastic/beats#8963
* [x] auditd: log elastic/beats#10192
* [x] elasticsearch: audit, deprecation, gc, server, slowlog elastic/beats#9293
* [x] haproxy: log elastic/beats#9117
* [x] icinga: debug, main, startup elastic/beats#9294
* [x] iis
  * [x] access elastic/beats#9084
  * [x] error elastic/beats#9955
* [x] kafka: log elastic/beats#9297
* [x] kibana: log elastic/beats#9301
* [x] logstash: log, slowlog elastic/beats#9935
* [x] mongodb: log elastic/beats#10009 
* [x] mysql: error, slowlog elastic/beats#10008
* [x] nginx
  * [x] access elastic/beats#9081
  * [x] error elastic/beats#10007
* [ ] osquery: result elastic/beats#10088
* [x] postgresql: log elastic/beats#9308
* [x] redis: log, slowlog elastic/beats#9315
* [x] system:
  * [x] auth elastic/beats#9138
  * [x] syslog elastic/beats#9135
* [x] Update Suricata vs [Mike's spreadsheet](https://docs.google.com/spreadsheets/d/1ZgUrh16w7yzv3FRLXpnKNuFL2KOgHSCtCA6Gipm-_Jk/edit#gid=119975656) elastic/beats#10006
* [x] traefik: access elastic/beats#9005
* [x] Revisit all modules doing int coercions in Grok, to see if we need to coerce using `:long` instead 
 elastic/beats#9598
* [x] Add service.type to modules: https://github.com/elastic/beats/pull/10042

## Metricbeat modules

* [x] Rename metricset.name to event.dataset #8941

* [x] Rename metricset.module to event.module elastic/beats#8941
* [x] Add service.type to modules. elastic/beats#8965
* [x] Decide on metricset.namespace on where the field should go.
  * We keep this for now in metricset.namespace as metricset.* still exists and does not fit ECS:
* [x] Transition container and kubernetes fields to use container fields?
* [x] Update all data.json files
* [x] Map system metricsets (and others) to process in ECS https://github.com/elastic/beats/pull/10218
  * [x] Check hostname fields
  * [x] Check network data fields
  * [x] ~~`network` metricset~~ elastic/beats#10325
  * [x] `process` metricset elastic/beats#10332
  * [x] Zookeeper module https://github.com/elastic/beats/pull/10286
  * [x] Kubernetes events: https://github.com/elastic/beats/pull/10284
  * [x] Mongodb module: https://github.com/elastic/beats/pull/10368
  * [x] Elastic stack modules: https://github.com/elastic/beats/pull/10350
  * [x] Http module: https://github.com/elastic/beats/pull/10315

## Packetbeat

* [x] Convert Packetbeat basic fields to ECS elastic/beats#9121
* [x] Convert protocols to ECS https://github.com/elastic/beats/issues/7968

## Journalbeat

* [x] Convert read_timestamp to event.created https://github.com/elastic/beats/pull/10043

## Heartbeat

* [x] Add event.dataset: https://github.com/elastic/beats/pull/9408

## Winlogbeat

* [x] Any changes to Winlogbeat needed? #10333

## Varia

* [x] Temporary fix for dashboards elastic/beats#9031 
* [x] Populate `ecs.version` in all relevant places https://github.com/elastic/beats/pull/9284
* [x] Finish the transition of `user_agent` parsing to ECS for all web access logs.
* [x] Better representation of field aliases in the documentation elastic/beats#9269 
* ~~Part 2 to improve alias representation in docs  elastic/beats#9288~~ (can also happen later)

See also all [issues tagged "ecs"](https://github.com/elastic/beats/issues?utf8=%E2%9C%93&q=label%3Aecs)

## Others

* [x] Apply renaming to all Kibana files https://github.com/elastic/beats/pull/9998
* [x] Apply renaming to ML jobs (ouf of the scope of this issue, ML team will handle it)
* [x] Check where docs need updating https://github.com/elastic/beats/pull/10370
* [x] Introduce add_labels / add_tags processor https://github.com/elastic/beats/pull/9973
* [ ] Introduce script to show breaking field changes: https://github.com/elastic/beats/pull/10405

## Open questions:

* Should we rename `co.elastic.logs/fileset` to `co.elastic.logs/dataset` for autodiscovery (@exekias )
* Should we change the `metricsets` config option in Metricbeat?
* Proposal by @ruflin Keep it for now as we keep also the field fileset and metricset around

## Notes 
* The code side is not changed as part of this migration.
* The filebeat generated files must often be updated. Use the following to commands: `INTEGRATION_TESTS=1 GENERATE=1 nosetests tests/system/test_modules.py -v`, x-pack: `MODULES_PATH=./module INTEGRATION_TESTS=1 GENERATE=1 nosetests tests/system/test_xpack_modules.py  -v`.

**Comment by webmat** [comment]
@ruflin 
- I've created a section listing all modules. It's we can expand modules to one line per fileset only when needed. I get the feeling we'll end up doing some of them 1 PR for the whole module.
- I've also checked the tasks that were listed and have been merged (e.g. beat.name). If any of those required follow-up work, please add subtasks.

**Comment by ruflin** [comment]
@exekias We must change it in the docs too. Would this solve the issue?

**Comment by exekias** [comment]
If we completely rename the thing, I would say yes, annotations must follow

**Comment by webmat** [comment]
@ruflin I've updated the "Beats processors" section. The list and fields to change should be pretty comprehensive now. Please take a look, to confirm I haven't missed something.

cc @roncohen

**Comment by webmat** [comment]
@ruflin Just added this to the "Field changes" section. I think this would be best solved by moving ECS docs to asciidoc on the doc website:

- Some ECS field definitions casually refer to other ECS Readme sections in the Beats docs. We need to address this better

**Comment by sophiec20** [comment]
For our UI ML Module automated testing, we do the following:
- restore a data snapshot
- call the Kibana API data recogniser
- call the Kibana API module setup - this creates ML jobs, datafeeds and visualisations and dashboards
- the run the ML jobs
- then check ML results are visible
- then check you can click through to the newly created dashboards (this bit is manual)

We currently use
- filebeat-* where `fileset.module": "nginx" AND "fileset.name": "access"`
- filebeat-* where `fileset.module": "apache2" AND "fileset.name": "access"`
- auditbeat-*  where `"event.type": "syscall"` for docker containers and hosts (tbc if ECS changes exist in 7.0)   

As we start with data snapshots in our existing test framework, is the beats team able to supply snapshots of indices containing
a) pure new 7.0 ECS data and b) backward compatible indices?
With (a) being the priority.

**Comment by ruflin** [comment]
With 7.0 you will be able for the above queries to just rely on `event.dataset: nginx.access` as an example. BTW we also renamed apache2 to apache to be in line with the metricbeat module.

I assume the data you are looking for is nginx and apache data for the logs. What I could produce is a few lines of example data based on our test suite logs. Would that be enough? Or you need larger logs? If you have larger log files for nginx and apache I can easily create the data.

**Comment by sophiec20** [comment]
@ruflin Can we please start with some example data snapshots? 
(We do have larger logs, but I'm not sure if we retained them in their original raw format as they were anonymised.  Will need to check and will share with you if we can).

**Comment by ruflin** [comment]
Our tests logs can be found here: 

* apache.acess: https://github.com/elastic/beats/tree/master/filebeat/module/apache/access/test
* nginx.access: https://github.com/elastic/beats/tree/master/filebeat/module/nginx/access/test

I initially thought I provide you with a snapshot or es_archiver zip file from ES. But I think it's easier if the one that works on these files ingests the data himself. Like this also your apache files can be used and it does not have to go through me anymore.

To make the module work with any file path, `var.paths` must be adjusted in the module config: https://github.com/elastic/beats/blob/master/filebeat/modules.d/apache.yml.disabled

For testing use the snapshot builds:

* OS X https://beats-ci.elastic.co/job/elastic+beats+master+multijob-package-darwin/gcsObjects/
* Linux & Windows: https://beats-ci.elastic.co/job/elastic+beats+master+multijob-package-linux/gcsObjects/

**Comment by ruflin** [comment]
@webmat Above I did check the checkbox around http.request.method to normalise it. I suggest we skip this for now.

**Comment by webmat** [comment]
@ruflin Understood. If I can get around to it in time would you have any objections, though?

Not 100% sure I can (e.g. if we don't have what we need in field generation), but I'd like to get it done if possible.

**Comment by ruflin** [comment]
@webmat No objections :-)

**Comment by ruflin** [comment]
Closing this issue as all the checkboxes have been done except the following 3:

* http method lower case: We will figure out something at a later stage
* osquery module: According to @webmat conversion to ECS does not make sense
* Breaking changes files: PR is open and will be merged soonish.

A big thank you to everyone that contributed to getting this massive effort done.
