### ISSUE TITLE
Consul Metricbeat module

### ISSUE THREAD

**Issue by sayden** [elastic/beats#8697]
This is the checklist for releasing Consul Metricbeat module to GA.

## Planned functionality
* [ ] Agent metricset
* [ ] Master metricset

## GA

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] Integration tests
* [ ] System tests
* [ ] Automated checks that all fields are documented
* [ ] Documentation
* [ ] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [ ] Fields follow naming conventions: https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html
* [ ] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)

PR is in progress here https://github.com/elastic/beats/pull/8631
