### ISSUE TITLE
MS SQL Metricbeat module

### ISSUE THREAD

**Issue by sayden** [elastic/beats#8698]
This is the checklist for releasing Microsoft SQL Metricbeat module to GA.

* [X] `db` metricset https://github.com/elastic/beats/pull/9414 (merged)
  * [X] Supported versions are documented
  * [X] Supported operating systems are documented (if applicable)
  * [X] Integration tests
  * [X] System tests
  * [X] Automated checks that all fields are documented
  * [X] Documentation
  * [X] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
  * [X] Fields follow naming conventions: https://www.elastic.co/guide/en/beats/devguide/master/event- 
 conventions.html
  * [X] Dashboards exists (if applicable)
  * [X] Kibana Home Tutorial (if applicable)
* [X] `performance` metricset (to be merged). Some progress in this closed PR https://github.com/elastic/beats/pull/8250 Queries that will be done can be seen [here](https://github.com/elastic/beats/pull/8250/files#diff-1a92985745c8b7ded4b6c2268ee2cbe3)  and the current outdated fields data [here](https://github.com/elastic/beats/pull/8250/files#diff-a01f59c7858d8135d5642c9a4ddf764a)
  * [X] Supported versions are documented
  * [X] Supported operating systems are documented (if applicable)
  * [X] Integration tests
  * [X] System tests
  * [X] Automated checks that all fields are documented
  * [X] Documentation
  * [X] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
  * [X] Fields follow naming conventions: https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html
  * [X] Dashboards exists (if applicable)
  * [X] Kibana Home Tutorial (if applicable)

## GA

* [ ] Supported versions are documented Issue about this here https://github.com/elastic/beats/issues/10538
* [ ] ~~Supported operating systems are documented (if applicable)~~
* [X] Integration tests
* [X] System tests
* [X] Automated checks that all fields are documented
* [X] Documentation
* [X] Example `data.json` exists and an automated way to generate it exists (`go test -data`)
* [X] Fields follow naming conventions: https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html
* [X] Dashboards exists (if applicable)
* [X] Kibana Home Tutorial (if applicable)
* [ ] Create blog post

**Comment by swtrux** [comment]
What version of Elastic will the MS SQL Metricbeat module be available in?

**Comment by sayden** [comment]
Closing as the module is already released
