### ISSUE TITLE
[Meta] Functionbeat next phase

### ISSUE THREAD

**Issue by ph** [elastic/beats#9013]
## Priority

GA:
- [x] Better expose cloudformation error in the CLI https://github.com/elastic/beats/issues/8912 PR: #9409
- [x] Kinesis CLI PR: #10116
- [x] Refactor permission and roles creation, allow user to override them.

Next phase
- [x] Add support Keystore #9009 
- [ ] Use a random names for the debloy bucket.
- [ ] Integrations tests
  - [ ] cloudwatch https://github.com/elastic/beats/issues/8850
  - [ ] SQS
  - [ ] API Gateway
  - [ ] Kinesis
- [ ] Support modules https://github.com/elastic/beats/issues/8266
- [ ] Add metadata from the provider.
- [x] Allow to export the cloudformation template.
- [x] Move back to goformation original repository instead of the fork. https://github.com/elastic/beats/issues/8857
- [ ] CLI command to push the config + artifact to the provider.
    - [ ] API gateway CLI
- [ ] Multi region support for AWS https://github.com/elastic/beats/issues/9018
- [ ] MFA support : https://github.com/elastic/beats/issues/9371
## Monitoring / Telemetry 
- [ ] Report monitoring events as part of the logs
 - [ ] Limit the rate of reporting
- [ ] Allow a function to monitor monitoring events (it should be a module)
 - [ ] Make it easy to push a function to acts as a monitoring collector (part of the CLI)

#### Low priority
- [ ] Disable features for faster startup
    - [ ] Seccomp
    - [ ] Logging to file
    - [ ] Remove unsupported spooling to disk

#### Testing

- [x] Assert two binaries in the generated packages https://github.com/elastic/beats/issues/9116
- [ ] Add tests for beats-tester, this will need more investigation?

### Other Provider

- [ ] Azure functions: https://github.com/elastic/beats/issues/9232

**Comment by felix-lessoer** [comment]
@ph Any updates on this ticket?

**Comment by ph** [comment]
@felix-lessoer Not yet, but we are still looking at it.

**Comment by jlind23** [comment]
We endeavor to address Functionbeat use cases via the new Serverless Forwarder project (https://github.com/elastic/elastic-serverless-forwarder)with a better integration with serverless functionality provided by major cloud providers. Enhancements to the current Functionbeat will therefore be limited.
