### ISSUE TITLE
[META] Heartbeat 7.0 TODO

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#9017]
This PR is for organizing what's critical for 7.0

- [x] Add synthetic PK option for hb monitors: https://github.com/elastic/beats/pull/9697
- [x] Add location fields to root of config: https://github.com/elastic/beats/pull/8620
- [x] Add 'uptime' as dataset field elastic/beats#9408 
- [x] Add URL fields from ECS elastic/beats#9570 
- [x] Add agent.id and agent.ephemeral_id for beat elastic/beats#9404 

Nice to have
- [ ] Support autodiscover hints https://github.com/elastic/beats/issues/8552
- [ ] Multiple conn attempts https://github.com/elastic/beats/issues/8482 and https://github.com/elastic/beats/issues/7291

**Comment by geekpete** [comment]
Is this other TODO still relevant or needing updates?
https://github.com/elastic/beats/blob/master/heartbeat/TODO.md

**Comment by andrewvc** [comment]
Nothing else needed here.

**Comment by andrewvc** [comment]
@geekpete good call, that document should be removed in favor of GH issues.
