### ISSUE TITLE
Doc to-do list

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#9026]
Remaining work for 6.5 docs:

My list was getting kind of long so I'm consolidating the list here. FYI @karenzone 

**Journalbeat:**

- [x] Verify download paths
- [x] Remove release state override and backport to all branches.
- [x] Add linux command examples to the shared files.
- [x] Update the command reference (for journalbeat and functionbeat).
- [x]  For 6.5.1, add topics about loading dashboards.

**Infrastructure and logging:**

- [x] Update solution docs with Felix's review feedback from https://github.com/elastic/stack-docs/pull/142
- [x] Add UI docs to the Kibana Reference (karen).

**Functionbeat:**

- [x] Verify download paths
- [x] Remove release state override and backport to all branches.
- [x] Mark topics as X-pack
- [x] Add an FAQ topic that explains that you need to deploy functionbeat in the same region where the services (cloud watch logs/sqs) you're monitoring are deployed.
- [x] Remove the following topics because they are not relevant to functionbeat:
  - [x] Set up project paths: Nothing can be really change in provider container.
  - [x] HTTP Endpoint: This will not be accessible
  - [x] FAQ topics that aren't relevant:
    - [x] Logstash connection doesn’t work?
    - [x] Need to limit bandwidth used by Functionbeat?
    - [x] @metadata is missing in Logstash?  SSL client fails to connect to Logstash?
  - [x]  The following sections under security because they are not relevant to functionbeat:
    - [x] Secure communication with Logstash by using SSL
    - [x] Use Linux Secure Computing Mode (seccomp)
- [x]  Change logging topic to indicate where that the logs are only available in the cloudwatch log group of the functionbeat lambda. Maybe mention AWS panel.
- [x] Remove topic about Repositories for APT and YUM 

**Central management:**

- [x] Add content/edit the docs Carlos created and get the docs building.
- [x] Update the GS guides to indicate that the ingest pipelines need to be loaded. See related PR here: https://github.com/elastic/beats/issues/9037
- [x] In the docs for all of the beats make sure there are links to the CM docs. 
- [x] Make sure it's clear that users still need to run the setup command to load the index template and dashboards.
 - [x] Make sure it's clear the beats enrolled in CM ignore the local config 
- [x] Update security section with central management info.
- [x] Remaining tasks here: https://github.com/elastic/beats/issues/8470
- [x] Add Kibana topics for the CM docs (verify with G).

**Comment by dedemorton** [comment]
Closed out all issues
