### ISSUE TITLE
Check Beats overflow handling

### ISSUE THREAD

**Issue by urso** [elastic/beats#9271]
Indexing/transporting unsigned integers >2^63 has been a problem, due to consumers (libs/language/Elasticsearch) not naturally supporting integers of this size. With https://github.com/elastic/beats/pull/8991 we automatically cap values to `2^63-1` that can overflow. This might not always be the right solution (see [comment](https://github.com/elastic/beats/pull/8991#issuecomment-437027167)).

We should check the list of known issues if the masking is ok or not:
- [ ] Unexpectedly huge byte values returned for system.memory.swap.used.bytes elastic/beats#6271 
- [x] Metricbeat - non incremental network usage metrics elastic/beats#2783
- [ ] Integer overflow in Beats metrics elastic/beats#5433
- [ ] `system.fsstat.total_files` hits long MAX elastic/beats#5386 
- [ ] `memstat.rss` reports negative values elastic/beats#7505
- [ ] Max uint64 used as infinite limit in cgroups elastic/beats#5854

Note: Also to figure out if we want to backport elastic/beats#8891 or not.

@andrewkroh @ruflin  @jsoriano @kvch Please add issues from github/discuss I did miss :)

**Comment by jsoriano** [comment]
@urso #6271 is an overflow caused by how we calculate some values, it should be considered a bug on the calculation and there is no need to handle it in a special way.

I'm not sure to understand why #2783 is in this list :slightly_smiling_face:
If this is for the overflows caused by very big numbers I think that there is no general solution, if they are very big gauges we could collect them as doubles. If they are continuously increasing values or counters, then I think capping them is fine.

**Comment by urso** [comment]
> I'm not sure to understand why #2783 is in this list 🙂

The list contains known issues. I didn't look into the actual issues. Just add every issue/discussion you are aware of to the list.

We have to see if #8991 is the right solution for some of these(e.g. close the issue), or if we have to fix the actual issue. If we find #8991 is a good solution for some, we might consider to backport it to 6.x. Otherwise we will have to fix the particular issue within the module! E.g. #2783 is very old. If we find #8991 is good here, close it. Otherwise fix it (it's open for quite some time).

**Comment by urso** [comment]
@jsoriano Any progress on identifying metricsets that need to handle values?

**Comment by fearful-symmetry** [comment]
#5854 is related. There's a lot of things that are explicitly designed to squash uint64-sized values. Trying to comb through metricbeat for examples of this is going to be...a long effort.

**Comment by jsoriano** [comment]
> @jsoriano Any progress on identifying metricsets that need to handle values?

I don't remember to actively look for cases per metricset :(

@fearful-symmetry thanks for pointing to this issue, I have added it to the list.
