### ISSUE TITLE
[Meta] Filebeat NetFlow input

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#9399]
# Filebeat NetFlow input release checklist

This checklist is intended to track progress of NetFlow support in Filebeat (#8434).

For this input and associated modules to go GA, the following criterias should be met:

* [x] Filebeat `netflow` input. (#9365)
* [x] Documentation for `netflow` input. (#9388)
* [x] Community ID support. (#9538)
* [x] Fields yml updated
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html) (#9537)
* [x] Add BiFlow support (#9537)
* [x] Dashboards exists (#10180)

**Comment by adriansr** [comment]
ECS fields for Biflow support:
*Non-Biflow flows:*
`event.kind: event`
`event.category: network_traffic`
`event.action: netflow_flow`

*Biflow flows:*
`event.kind: event`
`event.category: network_session`
`event.action: netflow_flow`

*Netflow options:*
`event.kind: event`
`event.category: network_traffic`
`event.action: netflow_options` 

https://tools.ietf.org/html/rfc5103#section-6.3 shows how we would map `source.*` and `destination.*` to `client.*` and `server.*`
*Information Element Field = 0x00, 0x01, 0x03*
`source.*` -> copy_to -> `client.*`
`destination.*` -> copy_to -> `server.*`

*Information Element Field = 0x02*
`source.*` -> copy_to -> `server.*`
`destination.*` -> copy_to -> `client.*`
