### ISSUE TITLE
Move topology map to Packetbeat

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#946]
Currently the topology map is a configuration option of the outputs, so it applies for all Beats even if it makes sense only to Packetbeat. Also, topology map information is available only for Elasticsearch and Redis outputs. 

TODOs:
- [ ] move the topology map implementation from libbeat to Packetbeat
- [ ] move the configuration from outputs under another section that is Packetbeat specific
- [ ] configure where to store the topology map, in addition to the outputs
