### ISSUE TITLE
Restructure Beats 1.1 documentation and later to add nesting to TOC

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#970]
This meta issue tracks the work that is required to restructure the Beats documentation. The work involves several different PRs that will need to be merged at the same time to avoid breaking the doc build:

- [x] Merge PR for 1.0.1 #971 (we don't need this PR if we are no longer building the 1.0.1 docs)
The changes for 1.0.1 are limited to adding float tags and fixing links so that nothing will be broken.  There will be no additional restructuring of the 1.0.1 doc. 

- [x] Merge PR for 1.1 #972 
This PR for 1.1 to add restructured topics

- [x] Merge PR that changes chunk level for all Beats doc to 1 https://github.com/elastic/docs/pull/79

- [x] Cherry pick or merge structural changes into master https://github.com/elastic/beats/pull/978
