### ISSUE TITLE
Support Redis Streams and Consumer groups monitorization in Metricbeat

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#9876]
Redis 5.0 introduced the concept of [streams](https://redis.io/topics/streams-intro), an append-only data structure that can be accessed in a variety of ways. It allows the implementation of consumer groups as introduced by Kafka.

There are some things that can be monitored here:
* [ ] streams length (`XLEN`) could be added to `key` metricset
* [ ] `XINFO` metrics could be also added to the `key` metricset, or to an specific `stream` metricset
* [ ] metrics about consumers and consumer groups
   * [ ] number of pending messages (`XPENDING`)
   * [ ] consumer stats (`XINFO CONSUMERS`)
   * [ ] consumer group stats (`XINFO GROUPS`)

And extra things to do:
* [ ] Add a dashboard for this use case
