### ISSUE TITLE
[Meta] Kibana 7 dashboards

### ISSUE THREAD

**Issue by urso** [elastic/beats#9899]
Saved objects format in Kibana is changing: https://github.com/elastic/kibana/issues/27210

For keeping compatiblity between different Kibana and Beats versions when 7.0 is released we need to maintain kibana 6 and 7 dashboards in Beats. So to reduce the load on developers we will provide automation via `make update` to automatically create Kibana 6.x compatible dashboards.

- [ ] (Automatically) port kibana dashboards to new saved-objects format
- [ ] provide dev tool to transform Kibana 7 dashboards to Kibana 6.x
- [ ] integrate dev tool into `make update`
- [ ] Add Kibana 6 and 7 dashboards
  - [ ] Metricbeat
  - [ ] Auditbeat
  - [ ] Filebeat
  - [ ] Journaldbeat
  - [ ] Heartbeat
  - [ ] Packetbeat
  - [ ] Winlogbeat
- [ ] Add support for 6/7 directory when loading dashboards
- [ ] Remove logic loading 5.x dashboards by writing to `.kibana` index

**Comment by ruflin** [comment]
As because of the ECS change field name changes in the Dashboards, there is not a straight forward migration from 7 to 6 dashboards. As I expect Kibana to do the conversion automatically on loading also in 7 I would suggest for now we keep the old format so no conversion is needed (yet).

**Comment by spalger** [comment]
So sorry to say this, but after some investigation it turned out that I was totally wrong about the necessity for beats to upgrade the exports they use to create dashboards. I was not under the impression that the dashboard import API supported saved object migrations but they totally do and we've verified that imports from beats 6.x work properly with the changes @mikecote and I are planning for Kibana 7.0...

Again, so sorry for the wasted time and ruffling feathers for nothing, but thank you so much for your help in the process.

**Comment by ruflin** [comment]
@graphaelli @jsvd This means also no affects on APM and Logstash.
